"""
campaign_people.py - the Embers and everyone they have met.

Player-known framing only. Sources: the Unexpected Journey accounts 001-011
and the campaign tracker (Player Characters, NPCs). Nothing here should say
more than a player at the table could.

References to other records use "kind:slug":
    pc:   the-embers/      npc:  dossiers/      item:  armory/
    place: atlas/          fac:  war-intel/     quest: quests/

`records` maps a journey number to what that journey added. The highest
number shows open on the page; the rest fold under "Previous Journeys".
"""

IMG = 'https://lh3.googleusercontent.com/d/'

# ---------------------------------------------------------------------------
# THE EMBERS
# ---------------------------------------------------------------------------

PCS = [
    dict(
        slug='aratos', name='Aratos Stormblessed', short='Aratos',
        race='Human', klass='Barbarian', portrait=IMG + '1FocmkAQsG7XDRJPrGZMtQerhkHxSvYNV',
        sub="Barbarian of the Ancestral Guardians; a Knight Radiant of Cathan's line",
        affiliation='Knights Radiant; the Embers', first=1, last=11, status='Active',
        overview=[
            "A vision came to Aratos like a summons: scaled warriors marching in ranks, and one command in it, fight. He set out for Kalaman to warn the Knights of Solamnia.",
            "He is a barbarian whose ancestors gather around him when he rages, and a Knight Radiant of Cathan's line, as is his cousin Aeimos. He was first to speak his oath at the reliquary door and first to challenge the monument at Bracken Hollow. He carries the Emberwake, a cursed axe he took as a trophy at Vogler.",
        ],
        pursuit="Trying to hold to the path of restraint he chose, after the Emberwake's fury took him at Bracken Hollow.",
        state="Unconscious on the hill at Bracken Hollow, ringed by the spectral warriors of the horn. The monument marked him with the black glow.",
        line="Took the head off the monument at Bracken Hollow in a fury that was not his own, and had to be brought down by Roshi.",
        links=['item:the-emberwake-greataxe', 'item:horn-of-sir-cthondor', 'quest:the-emberwakes-curse',
               'quest:the-leviathan-axe', 'quest:the-first-mission', 'pc:aeimos', 'npc:theros-flametongue',
               'fac:the-knights-radiant', 'place:bracken-hollow', 'npc:ked'],
        records={
            1: ["Woke from a dream of scaled warriors marching in ranks, with one command in it: fight",
                "Recognized the ambushers on the road from that dream and charged"],
            2: ["Brought lightning against the creature of living sand"],
            3: ["Told Becklin of his vision at Gertrude's smithy and asked her help warning the knights",
                "Reunited with his cousin Aeimos, who stole his ring before saying hello",
                "Drove lightning through the beast beneath Crustdurn Isle"],
            4: ["Shared his vision with Becklin, who promised a letter for Kalaman",
                "Stayed at Darrett's side when the mock battle at High Hill turned real"],
            5: ["Saw a colossal tree split between flame and frost, and a stern figure who told him to choose: blades of fury, or an axe of cold restraint",
                "Scouted the woods and recognized one of the larger figures on patrol from the fight on the road"],
            6: ["Tried to bluff a cliffside watcher and ended up with a blade at his throat",
                "Felt his axe run cold while a voice demanded he prove himself",
                "Killed the Red Army's messenger with a javelin through the heart",
                "Was asked by Becklin to bring a chest from Thornwall Keep to Darrett if she did not return"],
            7: ["Dueled Theros Flametongue on the burning docks with his ancestors gathered around him",
                "Brought down the dragon machine with a javelin and a bolt of lightning",
                "Took Theros's still-warm axe as a trophy"],
            8: ["Took up the Emberwake Greataxe on the river",
                "Saw Cathan Twice-Born and Lord Soth in the water, and was told he would have to choose soon",
                "Silenced Lord Bakaris in the council chamber",
                "Named himself a Knight Radiant; Marshal Vendri acknowledged the title"],
            9: ["Spoke his oath at the reliquary door and lit the word Valor",
                "Was named a child of Cathan by the spirit of Sir Cthondor",
                "Was left the horn by Aeimos"],
            10: ["Saw the tree of fire and frost in the campfire, and the King, who warned that the same weakness runs in his blood",
                 "Lost himself to the axe in a sparring match and cut down the squire Roberto, who survived",
                 "Found he cannot hand the axe away or set it down",
                 "Knelt at the reliquary and chose the cold side of the tree; the flames died and the axe briefly took another shape"],
            11: ["Opened a wolf from shoulder to flank with the Emberwake; green flame leapt to the next",
                 "Drew the truth about the hill out of Boyd and Corvin",
                 "Promised Ked the Embers would protect him with their lives",
                 "Challenged the monument and was marked with the black glow",
                 "Blew the Horn of Sir Cthondor; five spectral warriors answered",
                 "Lost himself to the axe's fury, took the monument's head, and was struck senseless by Roshi"],
        },
    ),
    dict(
        slug='kakashi', name='Kakashi', short='Kakashi',
        race='Human', klass='Wizard', portrait=IMG + '1USG7Cr8dArWVq8HCEe99o3IQMOBCD26K',
        sub='Wizard in training, testing for the White Robes of High Sorcery',
        affiliation='High Sorcery (White Robes candidate); the Embers', first=1, last=11, status='Active',
        overview=[
            "Kakashi is a wizard who keeps a raven familiar. He passed a mage trial beside Jasper and met the others in the ambush on the road to Vogler.",
            "Since the night the moons aligned on his watch he has wanted greater magic, urgently. He reads what others miss: the cipher in Fizban's recipe, the curse on Aratos's axe, the spellwork over Bracken Hollow. Wyhan has set him to test for the White Robes.",
        ],
        pursuit="Growing his power and earning his White Robes, while puzzling over a vision of a tower.",
        state="Inside Bracken Hollow with less than a day to break its spell. Still awaiting his White Robes exam.",
        line="Saw the lattice of spellwork over Bracken Hollow and its three knots, and found the three recesses beneath the hill.",
        links=['item:boilerdrake-heart', 'item:moon-marked-spellbook', 'quest:the-white-robes',
               'quest:kakashis-tower-vision', 'quest:kakashis-buried-past', 'npc:wyhan',
               'fac:the-mages-of-high-sorcery'],
        records={
            1: ["Saw through the false key in the mage trial and passed alongside Jasper",
                "Was given a moon-marked spellbook, shared with Jasper"],
            2: ["Saw the moons align on his watch and heard voices say he was not strong enough, not yet"],
            3: ["Sent his raven to scout the shack on Crustdurn Isle",
                "Opened the fight below with a burst of ice"],
            4: ["Spoke for Ispin at the Brass Crab and quieted the room",
                "Was left a spell by Fizban as a parting gift"],
            5: ["Sent his raven to follow Cudgel at a distance"],
            6: ["Stilled a panicking crowd with a flash of power, then with gentleness",
                "Loosed a lightning strike that sounded like a thousand birds"],
            7: ["Finished the last operator inside the wreck and was dropped by the blast",
                "Remembered a village burning, and a past he had tried to bury",
                "Pulled the Boilerdrake Heart from the wreckage"],
            8: ["Attuned to the Boilerdrake Heart",
                "Presented his High Sorcery scroll to Wyhan; he will test for the White Robes"],
            9: ["Understood that the reliquary door was testing the virtues of knighthood",
                "Pushed the Boilerdrake Heart past its limits against the wraith"],
            10: ["Recognized Fizban's recipe as a cipher",
                 "Saw an elven woman in a pail of water, warding a round room of relics, who told him: you have to fight, keep them safe",
                 "Had Wyhan confirm the cipher and name the spell",
                 "Judged that breaking the hold of Aratos's axe would take divine magic"],
            11: ["Called his raven back and carried Wyhan's list down the road",
                 "Gathered willowbark, pine resin and graveyard moss",
                 "Dug bones from a fresh grave and raised a skeleton on the hill",
                 "Struck the monument first, with lightning",
                 "Fell to the moons' light, and as he fell saw a lattice of spellwork over the village with three knots in it",
                 "Dimmed the black ring and turned a blow away from Aratos",
                 "Read the rings as receivers and found the cavern with three recesses"],
        },
    ),
    dict(
        slug='jasper', name='Jasper Quickwit', short='Jasper',
        race='Halfling', klass='Rogue', portrait=IMG + '1zX6MfbMgXijkdr9IOJLbGnWdMS3wtoR1',
        sub="Rogue bound to the Dragon's Eye thieves' guild",
        affiliation="Dragon's Eye; the Embers", first=1, last=11, status='Active',
        overview=[
            "Jasper is a rogue who passed a mage trial behind an apprentice's mask. The Dragon's Eye, a thieves' guild, bound him with a deadly coin and set him a task: find the moving Tower of Wayreth and steal the Orb of Dragonkind.",
            "He scouts ahead alone and shoots from cover. He counted the Red Army camp outside Vogler, saw that the dragon was a machine, and noticed Corvin watching Ked. When Old Man Jenkins packed to flee Vogler, Jasper stayed, saying the town was good and its people needed help.",
        ],
        pursuit="Carrying out the task the Dragon's Eye set him: stealing the Orb of Dragonkind from the moving Tower of Wayreth.",
        state="In Bracken Hollow with the rest. Lucky's warning from the river still stands: time is running out on the Orb.",
        line="Read Corvin in Boyd's shelter, and went down into the cavern beneath the hill with Kakashi.",
        links=['item:winged-boots', 'item:leeching-arrows', 'item:dragons-eye-coin',
               'quest:the-orb-of-dragonkind', 'quest:the-white-robes', 'quest:finbar',
               'npc:lucky', 'npc:seredyn', 'npc:finbar', 'fac:the-dragons-eye'],
        records={
            1: ["Passed the mage trial beside Kakashi by reading the runes for the word that opened the door",
                "Struck from hiding in the ambush on the road"],
            2: ["Dreamed of Lucky and the coin, and of the task: find the moving Tower of Wayreth and steal the Orb of Dragonkind",
                "Was caught and nearly swallowed by the living sand"],
            3: ["Vanished into the shadows of the cavern; his arrows found the killing angles on the beast"],
            4: ["Slipped out to General Goods to meet Old Man Jenkins, who knew the guild's phrase",
                "Bought winged boots with the party's shared gold and called it a slick deal",
                "Killed a traitor before he could cut Darrett down",
                "Shot the half-ogre through the head"],
            5: ["Crept alone to the edge of the Red Army camp and counted one to two hundred soldiers",
                "Used the Dragon's Eye coin to pass as a guard when a patrol came too close",
                "Told Jenkins the town was good and its people needed help, and was given healing potions and leeching arrows"],
            6: ["Used one of the leeching arrows on the cliffside"],
            7: ["Rose over the docks on the winged boots and saw that the dragon was a machine with a crew inside"],
            8: ["Saw Lucky in the river, warning that time was running out",
                "Overheard the council's private deliberation",
                "Caught a shimmer of illusion on one figure leaving the council chamber and knew the Dragon's Eye had reached Kalaman",
                "Presented his High Sorcery scroll to Wyhan; he will test for the White Robes"],
            9: ["Slipped out of the necromancer's darkness and broke his concentration with a shot",
                "Found a note in Thieves' Cant marked with the Dragon's Eye: We need to talk"],
            10: ["Followed Finbar, no longer wearing Old Man Jenkins's face, into Kalaman by night",
                 "Met Seredyn, head of the Kalaman branch, at Finn's Bar",
                 "Was told Wyhan is his best lead to the tower, and that leaving it will be harder than entering",
                 "Told Roshi only that he had visited an old friend"],
            11: ["Spotted Bracken Hollow through the trees",
                 "Dropped the first wolf and the last",
                 "Saw Corvin watching Ked and judged he was working toward something",
                 "Called out that ordinary weapons were doing half their work",
                 "Put a leeching arrow into the monument",
                 "Went down into the cavern beneath the hill with Kakashi"],
        },
    ),
    dict(
        slug='roshi', name='Roshi', short='Roshi',
        race="Elf", klass='Paladin of Kiri-Jolith', portrait=IMG + '1aY9zew4XAuhOWbXfOB2Vfm7FKDzfZonc',
        sub="Devoted protector carrying Ispin's legacy",
        affiliation='The Embers', first=1, last=11, status='Active',
        overview=[
            "Roshi took the road to Vogler for the funeral of Ispin Greenshield. On the way, near the remnants of an old holy place, she felt a sacred calling settle on her.",
            "She puts herself between danger and other people, as she did against the half-ogre at High Hill and the messenger at Vogler's gate. Her hands heal, which no one in living memory had seen. She carries Ispin's green shield and a moon-touched sword.",
        ],
        pursuit="Living up to Ispin's example as a shield for others, and growing into her sacred calling.",
        state="Hurt but standing after the hill at Bracken Hollow. Wears the periapt that kept her alive.",
        line="Brought the fallen back on the hill at Bracken Hollow, then dropped Aratos before his fury could turn on his friends.",
        links=['item:ispins-green-shield', 'item:moon-touched-sword', 'npc:ispin-greenshield',
               'npc:becklin-uth-viharin', 'quest:the-emberwakes-curse'],
        records={
            1: ["Felt a sacred calling settle on her at an old holy place on the road",
                "Grappled one of the ambushers and demanded answers"],
            2: ["Gave the dead knights solemn care",
                "Was struck hard by the sand creature and nearly killed"],
            3: ["Ate crab ramen at the Brass Crab despite the danger to her health",
                "Was swallowed by the beast beneath Crustdurn Isle"],
            4: ["Told the story of Ispin and the bear den",
                "Received Ispin's Green Shield at Thornwall Keep",
                "Held against the half-ogre until her blade lit with divine fire"],
            5: ["Healed a fisherman by laying on hands, and was asked whether the gods had touched her"],
            6: ["Found Than at Thornwall Keep and asked for help delaying a massacre",
                "Drew the mounted messenger onto herself so Jeyev could ride"],
            7: ["Went down in the blast and was kept from death by the magic she carried",
                "Loosed a last arrow toward Becklin's attackers; it went wide"],
            8: ["Saw Ispin in the river asking whether she had protected the villagers, and answered that she had done what she could",
                "Offered Becklin's armor to Darrett"],
            9: ["Offered the door her truth and lit the word Foresight",
                "Charged the necromancer; radiant rose-thorns burst from her blade"],
            10: ["Picked up the parchment Fizban dropped",
                 "Spoke the incantation that taught all five the Green Flame Blade",
                 "Sensed that Jasper was holding something back",
                 "Bought a healer's kit"],
            11: ["Hid inside an illusory griffon and let a wolf run onto her sword",
                 "Struck the monument with her moon-touched sword as it hummed in the moonlight",
                 "Fell to the moons' light and was held from death by the periapt",
                 "Laid hands on Kakashi, then cried out and healed them all",
                 "Dropped Aratos with one blow when the fury would not leave him"],
        },
    ),
    dict(
        slug='mayriel', name='Mayriel', short='Mayriel',
        race='Elf', klass='Cleric of Paladine', portrait=IMG + '1VKa7NEkNHE6cGsNfNBckPyjOvvKLPrkM',
        sub='Cleric of Paladine; divine magic returned',
        affiliation='Faithful of Paladine; the Embers', first=1, last=11, status='Active',
        overview=[
            "Mayriel traveled with Roshi to Ispin's funeral. On the road she saw a vision of divine fire. In Vogler she saw another: a horned woman who became a five-headed dragon, and the platinum fire that shielded her from it.",
            "She heals and fights in the same breath. On the burning docks of Vogler she pledged Paladine her family signet ring, and her obedience when the god asks for it. The Dragon Queen has told her that her sword will find her.",
        ],
        pursuit="Walking her divine calling, and waiting for the sword the Dragon Queen has promised will find her.",
        state="On the hill at Bracken Hollow, under an eclipse she has seen before. She has had no vision in some time.",
        line="Knew the eclipse over Bracken Hollow for the one she saw a month ago, though it should come once a year.",
        links=['item:mayriels-signet-ring', 'item:divine-pendant', 'npc:sunscale',
               'quest:the-sword-of-the-dragon-queen', 'quest:the-emberwakes-curse', 'npc:fizban'],
        records={
            1: ["Saw divine fire and draconic terror at an old holy place on the road",
                "Understood the ambushers when they named the Shadow Queen"],
            2: ["Kept Roshi alive after the sand creature struck",
                "Drew Fizban's interest: clerics had not walked openly in centuries"],
            3: ["Saw a horned woman in dark regalia unfold into a five-headed dragon, and platinum fire rise to shield her"],
            4: ["Shared her vision with Becklin",
                "Woke to a golden finch and a pendant"],
            5: ["Healed a woman hiding a fatal wound, and was asked whether the gods had touched her"],
            6: ["Called down moonlit radiance on the cliff",
                "Fell, and was brought back with a healing potion"],
            7: ["Raised a twilight glow over her companions at the docks",
                "Killed Theros Flametongue",
                "Offered Paladine her family signet ring and her obedience when he asks"],
            8: ["Saw the Dragon Queen in the river, who promised her sword would find her",
                "Kept Sunscale, who chose her over Fizban"],
            9: ["Saw purplish-black soot at the cave mouth and remembered the river",
                "Burned the wraith with sacred flame",
                "Ended the wraith with a spiritual weapon shaped like a rose"],
            10: ["Told Aratos she has had no vision in some time, and that the silence feels suspicious",
                 "Does not know whether the promised sword is a blade or the one who carries it",
                 "Bought a healer's kit"],
            11: ["Sharpened Kakashi's eyes on the road and spotted the village with Jasper",
                 "Knew the three-moon eclipse from a month before, though it should come once a year",
                 "Heard her longbow hum its warning before the wolves howled",
                 "Blessed and strengthened her companions through both fights",
                 "Left the monument glowing with a guiding bolt and struck at its rings"],
        },
    ),
    dict(
        slug='aeimos', name='Aeimos Stormblessed', short='Aeimos',
        race='Human', klass='Monk', portrait=IMG + '1Fv4WEzpgAcrSBF7rxjmVI8sc1bLz8DqV',
        sub='Stormblessed kin to Aratos; a recurring guest',
        affiliation='Knights Radiant; Stormblessed kin', first=3, last=9, status='Companion',
        overview=[
            "Aeimos is Aratos's cousin and carries the same Stormblessed markings. He announced himself in Vogler by stealing Aratos's ring. He fights with storm-charged gauntlets.",
            "He comes and goes on his own road. He left Vogler with Fizban, returned outside Kalaman for the reliquary of Sir Cthondor, and left again to seek out the other tombs Lord Soth means to corrupt.",
        ],
        pursuit="Seeking out the knights' tombs that Lord Soth means to corrupt, on a road apart from the party's.",
        state="Off on his own road against Soth's corruption. Appears and vanishes.",
        line="Left the horn with Aratos and went where the pale woman pointed.",
        links=['item:storm-charged-gauntlets', 'item:horn-of-sir-cthondor', 'pc:aratos',
               'npc:the-pale-woman', 'npc:lord-soth', 'quest:lord-soths-corruption',
               'fac:the-knights-radiant'],
        records={
            3: ["Stole Aratos's ring as a greeting",
                "Agreed to come toward Kalaman and the knights",
                "Leapt into the beast with storm-charged fists and cut out its tongue as a trophy"],
            4: ["Left Vogler at dawn with Fizban"],
            8: ["Named by Marshal Vendri as aiding other villages alongside Fizban"],
            9: ["Shadowed the hunt until Jasper noticed him, then saw a pale woman who pointed him toward the others",
                "Spoke his oath at the door and lit the word Resolve: hopelessness is not my privilege",
                "Was named a child of Cathan",
                "Blew the horn of Sir Cthondor and saw two spectral knights answer",
                "Left the horn with Aratos and slipped away",
                "Was told by the pale woman that Lord Soth seeks to corrupt all knights until his curse is lifted"],
        },
    ),
]

# ---------------------------------------------------------------------------
# DOSSIERS
# ---------------------------------------------------------------------------
# met:      vogler | kalaman | the-road | visions      (first facet: where met)
# aff:      slug used by the second facet, with AFF_LABELS below
# standing: Ally | Neutral | Adversary | Unknown       (never a spoiler)

AFF_LABELS = {
    'kalaman': 'Kalaman',
    'vogler': 'Vogler',
    'dragons-eye': "Dragon's Eye",
    'red-dragon-army': 'Red Dragon Army',
    'knights': 'Knightly Orders',
    'high-sorcery': 'High Sorcery',
    'bracken-hollow': 'Bracken Hollow',
    'unaffiliated': 'Unaffiliated',
}
MET_LABELS = {
    'vogler': 'Vogler',
    'kalaman': 'Kalaman',
    'the-road': 'The Road',
    'bracken-hollow': 'Bracken Hollow',
    'visions': 'Dreams and Visions',
}

NPCS = [
    dict(
        slug='becklin-uth-viharin', name='Becklin Uth Viharin', role='Retired Knight of Solamnia',
        relation='Fallen mentor', affiliation='Knights of Solamnia (retired)',
        met='vogler', aff='knights', standing='Ally', last=7, status='Fallen',
        portrait=IMG + '1SsOS6K-8vuYw1Sqk4V15MIk98GEnMgu8',
        overview="Becklin Uth Viharin was a retired Knight of Solamnia living in Vogler and an old friend of Ispin Greenshield. She believed the party's warnings, gave Roshi Ispin's shield, and held the docks so the boats could leave. She fell into the Vingaard with blades in her back.",
        links=['npc:darrett-highwater', 'npc:ispin-greenshield', 'npc:cudgel-ironsmile',
               'npc:the-charred-swordswoman', 'item:ispins-green-shield', 'item:becklins-armor',
               'fac:the-knights-of-solamnia', 'place:vogler', 'quest:the-evacuation-of-vogler'],
        records={
            3: ["Heard Aratos's vision at Gertrude's smithy and did not dismiss it",
                "Met the party's return from Crustdurn Isle with gratitude and surprise"],
            4: ["Spoke at Ispin's river funeral in her Solamnic armor",
                "Sent Bakaris the Younger out of the Brass Crab",
                "Promised a letter to help the party gain an audience in Kalaman",
                "Gave Roshi Ispin's Green Shield at Thornwall Keep",
                "Cut through the traitors at High Hill beside Cudgel"],
            5: ["Kept her composure after High Hill when Cudgel could not"],
            6: ["Agreed that escape had to be prepared",
                "Took the front line with Cudgel and put the party in charge of the evacuation",
                "Asked Aratos to bring a chest from Thornwall Keep to Darrett if she did not return"],
            7: ["Held the waterfront against a charred woman in blackened armor",
                "Raised her hands toward the departing boat as if to say it was all right",
                "Was struck from behind and fell into the river"],
            8: ["Appeared to Darrett in the river among the Ashen Vigils",
                "Her armor passed to Darrett"],
        },
    ),
    dict(
        slug='fizban', name='Fizban', role='Green-robed wizard, old friend of Ispin',
        relation='Eccentric ally and guide', affiliation='Unknown; wandering',
        met='the-road', aff='unaffiliated', standing='Ally', last=10, status='Active',
        portrait=IMG + '1jIx_p6EnUosUiQHOc2K-kjU8E0u62t4W',
        overview="Fizban is a peculiar old wizard in green robes, found half-swallowed by a living sand creature on the road to Vogler. He comes and goes on his own business, takes a keen interest in Mayriel's divine magic, and can be unsettlingly insightful.",
        links=['npc:ispin-greenshield', 'npc:sunscale', 'pc:mayriel', 'pc:aeimos',
               'item:fizbans-stew-recipe', 'quest:fizbans-recipe', 'quest:meat-for-ispins-stew'],
        records={
            2: ["Was found inside a creature of living sand, which he froze solid from within",
                "Introduced himself as an old friend of Ispin",
                "Told Mayriel that clerics had not walked openly in centuries"],
            3: ["Found Mayriel shaken after her vision at the docks and told her to listen"],
            4: ["Told the tale of a stolen pie and an offended prince",
                "Insisted Ispin's shield belonged with someone still willing to stand in front of danger",
                "Left for Kalaman at dawn with Aeimos, leaving Kakashi a spell"],
            8: ["Named by Marshal Vendri as aiding other villages",
                "Greeted the party in Kalaman with sadness for Vogler",
                "Let Sunscale stay with Mayriel"],
            9: ["Proposed Ispin's stew as a remedy for despair and sent the party to hunt"],
            10: ["Dozed by the fire with his pipe",
                 "Dropped a recipe for Ispin's stew that turned out to hide the spell Green Flame Blade",
                 "Said he would stay in the city a little longer before moving on"],
        },
    ),
    dict(
        slug='darrett-highwater', name='Darrett Highwater', role="Becklin's former squire",
        relation="The Embers' proxy with Kalaman", affiliation='Vogler; Kalaman service',
        met='vogler', aff='kalaman', standing='Ally', last=10, status='Active',
        overview="Darrett Highwater was Becklin's young squire in Vogler. He survived the town's fall, accepted her armor as a promise to grow into it, and now stands as the Embers' proxy with Kalaman so they are not formally conscripted. He trains at the castle grounds and sleeps among the Voglerans.",
        links=['npc:becklin-uth-viharin', 'npc:marshal-vendri', 'item:becklins-armor',
               'quest:service-to-kalaman', 'place:the-refugee-camp'],
        records={
            4: ["Brought the party to Thornwall Keep",
                "Called the charge at High Hill and found his courage when it turned real"],
            5: ["Led the scouts into the woods, with more confidence than sense of direction"],
            6: ["Studied the town map with Becklin for places to reinforce"],
            7: ["Was carried from the front line on Jeyev's back"],
            8: ["Refused Becklin's armor on the river",
                "Saw Becklin in the water and was dragged under",
                "Accepted the armor and put it on at Kalaman's gates",
                "Told the council that Vogler sought refuge, not war",
                "Stepped forward as intermediary between the party and Kalaman"],
            9: ["Joined the stew feast late, covered in sweat and dirt from training"],
            10: ["Took his rest among the Voglerans rather than behind the walls",
                 "Helped hold Aratos back in the training yard",
                 "Offered again to stand as the party's proxy; Vendri accepted",
                 "Stays behind to look after the camp"],
        },
    ),
    dict(
        slug='marshal-vendri', name='Marshal Vendri', role='Marshal of Kalaman',
        relation='Commanding authority', affiliation='Kalaman military',
        met='kalaman', aff='kalaman', standing='Ally', last=10, status='Active',
        overview="Marshal Vendri commands Kalaman's military. He acknowledged Aratos as a Knight Radiant, takes the Embers' service through Darrett, and hands out their missions.",
        links=['npc:governor-miat', 'npc:darrett-highwater', 'npc:roberto', 'quest:the-first-mission',
               'quest:service-to-kalaman', 'place:kalaman'],
        records={
            8: ["Sat on the council and confirmed the whole region is under pressure",
                "Spoke of Fizban and Aeimos aiding other villages",
                "Acknowledged Aratos's title of Knight Radiant",
                "Asked for a name to record the party under"],
            10: ["Ran to stop Aratos in the training yard",
                 "Heard him out, and kept his eyes on the axe",
                 "Sent the Embers to find the tinkerer Tatina Rookledust",
                 "Accepted Darrett as proxy and wrote the party's name in the record",
                 "Promised to look into remedies for a cursed weapon",
                 "Sent them off with two healing potions"],
        },
    ),
    dict(
        slug='governor-miat', name='Governor Miat', role='Governor of Kalaman',
        relation='Granting authority', affiliation='Kalaman government',
        met='kalaman', aff='kalaman', standing='Neutral', last=8, status='Active',
        overview="Governor Miat rules Kalaman and holds firm control of its council. The council granted the people of Vogler refuge on the condition that the party aid the city's military efforts.",
        links=['npc:marshal-vendri', 'npc:bakaris-the-elder', 'quest:refuge-for-vogler',
               'quest:service-to-kalaman', 'place:kalaman'],
        records={
            8: ["Asked whether the people of Vogler intended retaliation",
                "Warned that other villages had come under attack as well",
                "Granted refuge in exchange for the party's service",
                "Was overheard holding firm against Lord Bakaris's interruptions"],
        },
    ),
    dict(
        slug='mayor-raven', name='Mayor Raven Uth Vogler', role='Mayor of fallen Vogler',
        relation='Grateful leader of the refugees', affiliation='Vogler refugees',
        met='vogler', aff='vogler', standing='Ally', last=10, status='Active',
        overview="Raven Uth Vogler is the mayor of Vogler. She resisted abandoning the town, then told its people the truth about the Red Dragon Army's demand. She now leads the displaced Voglerans camped outside Kalaman, and has named the party honorary Voglerans.",
        links=['place:vogler', 'place:the-refugee-camp', 'quest:refuge-for-vogler',
               'quest:the-evacuation-of-vogler', 'npc:bakaris-the-elder'],
        records={
            4: ["Offered the party lodging in her home",
                "Led the festival parade to High Hill"],
            5: ["Stepped in before Cudgel's interrogation became nothing but vengeance",
                "Heard the scouts' report of the army beyond the woods"],
            6: ["Resisted the thought of abandoning Vogler",
                "Received the Red Army's scroll at the gate",
                "Told the town the truth; Kakashi calmed the panic and set people to packing"],
            8: ["Saw to the refugees at Kalaman and asked the party to speak for Vogler before the council"],
            9: ["Named the party honorary Voglerans",
                "Expected nothing better of Lord Bakaris"],
            10: ["Made her rounds of the camp and offered her goodnights"],
        },
    ),
    dict(
        slug='cudgel-ironsmile', name='Cudgel Ironsmile', role='Mercenary captain',
        relation='Ally at Vogler', affiliation='Her own mercenary company',
        met='vogler', aff='vogler', standing='Ally', last=7, status='Unknown',
        overview="Cudgel Ironsmile is a mercenary captain whose company played the old foe in Vogler's festival battle. Part of that company sold her out to the Red Army. She fought for the town to the end and was last seen kicked through a building on the burning waterfront.",
        links=['npc:gragonis', 'npc:becklin-uth-viharin', 'npc:the-charred-swordswoman',
               'quest:the-betrayal-at-high-hill', 'quest:the-evacuation-of-vogler', 'place:vogler'],
        records={
            4: ["Lowered Ispin's boat into the river with Becklin",
                "Cut through her own traitors at High Hill, horrified"],
            5: ["Nearly lost herself to rage questioning the captured mercenary",
                "Learned that her lieutenant Gragonis took the gold",
                "Went back to her camp alone to see who remained loyal"],
            6: ["Returned with her loyal lieutenant Jeyev",
                "Laid out the choice: stay and fight, or evacuate",
                "Climbed into the cliffside fight",
                "Posted her mercenaries north of town to slow the Red Army"],
            7: ["Fought beside Becklin on the waterfront",
                "Was kicked aside through a building"],
        },
    ),
    dict(
        slug='than', name="Than Rookledust", role='Gnome tinkerer of Thornwall Keep',
        relation='Helpful eccentric', affiliation='Thornwall Keep, Vogler',
        met='vogler', aff='vogler', standing='Ally', last=7, status='Unknown',
        aliases=['Than'],
        overview="Than is a frantic gnome tinkerer who kept a workshop at Thornwall Keep. He is scattered and hard to keep on one subject, and useful anyway. What became of him after Vogler fell is not known.",
        links=['place:thornwall-keep', 'quest:the-evacuation-of-vogler', 'pc:roshi'],
        records={
            6: ["Was found by Roshi at Thornwall Keep",
                "Admitted to unstable explosives that could be set as traps",
                "Offered to help repair boats and rig a signal"],
            7: ["Launched himself from the keep's roof with the gnome-flinger and landed on his feet at the docks",
                "Shot a red draconian, which exploded as it died",
                "Ran between the fallen with potions"],
        },
    ),
    dict(
        slug='gragonis', name='Gragonis', role="Cudgel's lieutenant",
        relation='Named as the traitor', affiliation="Cudgel's company",
        met='vogler', aff='red-dragon-army', standing='Adversary', last=5, status='Unknown',
        named_only=True,
        overview="Gragonis was Cudgel Ironsmile's lieutenant. A captured mercenary said he went into the woods and came back with gold, and that some of her company had been paid to turn on Vogler. The party has heard his name and has not met him.",
        links=['npc:cudgel-ironsmile', 'quest:the-betrayal-at-high-hill', 'fac:the-red-dragon-army'],
        records={
            5: ["Named by the captured mercenary as the one who brought the gold",
                "Named by the prisoner, who said men had been paid to betray Cudgel, slaughter the militia, and leave Vogler open"],
        },
    ),
    dict(
        slug='bakaris-the-elder', name='Bakaris the Elder', role='Lord; nobleman',
        relation='Distrusted noble', affiliation='Nobility',
        met='vogler', aff='unaffiliated', standing='Neutral', last=8, status='Active',
        overview="Lord Bakaris is a nobleman who dresses in red and gold and takes offense when plans are made without him. He prefers a sealed letter to a ride into danger. He reached Kalaman's council ahead of the refugees.",
        links=['npc:bakaris-the-younger', 'quest:the-bakarises', 'npc:governor-miat', 'place:kalaman'],
        records={
            6: ["Forced his way into the planning, offended that anyone had made plans without him",
                "Preferred sending a letter under his seal to riding for help",
                "Stirred fear from the edge of the crowd"],
            8: ["Suggested on the river that more might have been done to save the village",
                "Entered Kalaman ahead of the refugees and brought the council the news first",
                "Tried to twist the hearing until Aratos silenced him"],
        },
    ),
    dict(
        slug='bakaris-the-younger', name='Bakaris the Younger', role='Young nobleman',
        relation='Disliked noble', affiliation='Nobility',
        met='vogler', aff='unaffiliated', standing='Neutral', last=8, status='Active',
        overview="Bakaris the Younger is a blond young nobleman, son of Lord Bakaris, with more arrogance than grace and very little real authority.",
        links=['npc:bakaris-the-elder', 'quest:the-bakarises'],
        records={
            4: ["Mocked the mourners' affection for Ispin at the Brass Crab until Becklin sent him off",
                "Gave away nothing useful about Kalaman or his father before the mock battle"],
            8: ["Echoed his father on the river: more might have been done",
                "Stood in the party's way outside the council and called the refugees fishfolk"],
        },
    ),
    dict(
        slug='wyhan', name='Wyhan', role="Apothecary; examiner for High Sorcery",
        relation='Sharp, transactional contact', affiliation="Kalaman apothecary; High Sorcery",
        met='kalaman', aff='high-sorcery', standing='Neutral', last=11, status='Active',
        overview="Wyhan keeps an apothecary in Kalaman. She read the High Sorcery scrolls Kakashi and Jasper carried and set both to test for the White Robes. Seredyn names her as the best lead to the Tower of Wayreth. She has sent Kakashi a list of things to gather, frostlace above all.",
        links=['quest:the-white-robes', 'quest:the-orb-of-dragonkind', 'quest:fizbans-recipe',
               'fac:the-mages-of-high-sorcery', 'place:kalaman', 'place:tower-of-wayreth', 'quest:wyhans-list'],
        records={
            8: ["Examined the High Sorcery scrolls Kakashi and Jasper carried",
                "Determined both would test for the White Robes, with a practical exam weeks out",
                "Dismissed them with little ceremony"],
            10: ["Sold Kakashi components to restore his familiar",
                 "Named a price for spell scrolls well beyond what he carried",
                 "Confirmed that the numbers in Fizban's recipe were a cipher, and that the spell was Green Flame Blade",
                 "Was named by Seredyn as Jasper's best lead to the tower"],
            11: ["Sent a list after Kakashi on the road: willowbark, pine resin, graveyard moss, and frostlace"],
        },
    ),
    dict(
        slug='sergeant-boyd', name='Sergeant Boyd', role='Retired soldier holding Bracken Hollow together',
        relation='Rescuer and host', affiliation='Bracken Hollow',
        met='bracken-hollow', aff='bracken-hollow', standing='Ally', last=11, status='Active',
        aliases=['Boyd'],
        overview="Boyd is a sergeant long retired from soldiering who made Bracken Hollow his home. Since the village closed he has kept its people fed and indoors at the right hours. He pulled Kakashi off a fresh grave, sheltered the party from the wolves, and told them how the moons turn. He says no one should have to choose who is sent up the hill.",
        links=['place:bracken-hollow', 'quest:the-spell-over-bracken-hollow', 'quest:the-ones-sent-up-the-hill',
               'npc:corvin', 'npc:ked', 'pc:kakashi', 'quest:wyhans-list'],
        records={
            11: ["Hauled Kakashi off a fresh grave: you need to go. Quickly",
                 "Loosed two arrows at the wolves in the dark and missed with both",
                 "Brought the party indoors and explained the white, red and black moons and the eclipse",
                 "Said no one had been sent up the hill, until Corvin called that less than the full truth",
                 "Told the party he would not ask them to fight the town's battles, and would not stop them",
                 "Left to carry food to the other houses and was not there when the party took Ked up the hill"],
        },
    ),
    dict(
        slug='corvin', name='Corvin', role='Villager of Bracken Hollow',
        relation='Went up the hill with the party', affiliation='Bracken Hollow',
        met='bracken-hollow', aff='bracken-hollow', standing='Unknown', last=11, status='Fled the hill',
        overview="Corvin is a broad-shouldered man in his forties with a rough beard, one of those who go out under the black moon for food. He told the party what Boyd would not: that another of the black-touched can be sent up the hill in place of the one the eclipse chooses. He believes the village must make the best of that. On the hill he kept Ked from leaving at the point of a dagger.",
        links=['place:bracken-hollow', 'npc:sergeant-boyd', 'npc:ked', 'quest:the-ones-sent-up-the-hill',
               'quest:the-spell-over-bracken-hollow', 'pc:jasper'],
        records={
            11: ["Interrupted Boyd: that's not the full truth, now is it",
                 "Said that some skills are still needed to keep the town together",
                 "Kept watching Ked, and tensed when Jasper asked him about it",
                 "Said people needed to eat, and Boyd left with food for the other houses",
                 "Talked Ked into going up the hill",
                 "Stood at Ked's back with a dagger when he tried to leave: you stay. You see this through",
                 "Knocked Ked senseless, and ran when the monument fought harder than he had ever seen it fight"],
        },
    ),
    dict(
        slug='ked', name='Ked', role='Villager of Bracken Hollow, black-touched',
        relation="Under the party's protection", affiliation='Bracken Hollow',
        met='bracken-hollow', aff='bracken-hollow', standing='Neutral', last=11, status='Unconscious on the hill',
        overview="Ked is a villager of Bracken Hollow. He was the one person in Boyd's shelter whose glow carried the black as well as the white and red, which makes him one of the handful the eclipse chooses from. Aratos gave him his word that the Embers would protect him.",
        links=['place:bracken-hollow', 'npc:corvin', 'npc:sergeant-boyd', 'pc:aratos',
               'quest:the-ones-sent-up-the-hill', 'quest:the-spell-over-bracken-hollow'],
        records={
            11: ["Curled up when Aratos pointed an axe at him: I don't want any trouble",
                 "Stood and came along after Aratos promised to protect him with their lives",
                 "Glowed brighter the nearer he came to the monument",
                 "Tried to leave, struck Corvin, and was knocked senseless",
                 "Still lying on the hill, with the eclipse not yet over"],
        },
    ),
    dict(
        slug='roberto', name='Roberto', role='Squire at Kalaman',
        relation='Sparring partner, injured', affiliation='Kalaman garrison',
        met='kalaman', aff='kalaman', standing='Neutral', last=10, status='Injured',
        overview="Roberto is a squire in Kalaman's garrison. He walked the courtyard statues with Aratos, and was later cut down by the Emberwake in a sparring match.",
        links=['pc:aratos', 'item:the-emberwake-greataxe', 'quest:the-emberwakes-curse', 'npc:marshal-vendri'],
        records={
            8: ["Walked the courtyard statues with Aratos, Lord Soth's among them",
                "Pointed him to Marshal Vendri for questions about such things"],
            10: ["Sparred with Aratos and landed one clean hit",
                 "Was cut down by the Emberwake",
                 "Alive, unconscious and badly hurt; expected to recover"],
        },
    ),
    dict(
        slug='seredyn', name='Seredyn', role="Head of the Dragon's Eye in Kalaman",
        relation="Local guild head, wary", affiliation="Dragon's Eye, Kalaman branch",
        met='kalaman', aff='dragons-eye', standing='Neutral', last=10, status='Active',
        overview="Seredyn heads the Dragon's Eye branch in Kalaman from a table at the back of Finn's Bar. He dresses richly, wears gold earrings, and walks the city behind a faint illusion. Lucky had not told him Jasper was coming.",
        links=['npc:lucky', 'npc:finbar', 'pc:jasper', 'quest:the-orb-of-dragonkind',
               'fac:the-dragons-eye', 'place:kalaman'],
        records={
            8: ["Left the council chamber shimmering faintly with illusion; he and Jasper acknowledged each other without a word"],
            10: ["Saw through Jasper's attempt at misdirection",
                 "Was surprised, then resigned, when he heard the truth of the Orb task",
                 "Named Wyhan as the lead to the Tower of Wayreth",
                 "Warned that getting into the tower might prove easier than getting out",
                 "Twitched at the corner of one eye when Lucky was named",
                 "Told Jasper to keep his visit short, cause no trouble, and let nothing come back to him"],
        },
    ),
    dict(
        slug='finbar', name='Finbar', role="Dragon's Eye contact",
        relation='Guild contact, once "Old Man Jenkins"', affiliation="Dragon's Eye",
        met='vogler', aff='dragons-eye', standing='Neutral', last=10, status='Active',
        aliases=['Old Man Jenkins', 'Jenkins'],
        overview="Finbar is a member of the Dragon's Eye who can pass unseen. In Vogler he wore the face of Old Man Jenkins at General Goods. Jasper saw through the disguise there and was given his real name. The rest of the party still knows him only as Jenkins. In Kalaman he dropped the disguise and walked Jasper to the guild.",
        links=['npc:seredyn', 'npc:lucky', 'pc:jasper', 'item:winged-boots', 'item:leeching-arrows',
               'quest:finbar', 'quest:the-orb-of-dragonkind', 'fac:the-dragons-eye'],
        records={
            4: ["As Old Man Jenkins, summoned Jasper by a note left in his pocket",
                "Explained the guild, Lucky, the coin and the task",
                "Sold Jasper a pair of winged boots"],
            5: ["Was found packing to flee Vogler",
                "Gave Jasper two healing potions and leeching arrows when Jasper chose to stay"],
            7: ["Slipped onto the boat unseen by most"],
            10: ["Watched the camp from just outside the firelight",
                 "Dropped his invisibility and the old man's face",
                 "Led Jasper to Peller's Provisions, knocked three times, and gave the passphrase",
                 "Walked him out again"],
        },
    ),
    dict(
        slug='lucky', name='Lucky Leppomanto', role="Guild master of the Dragon's Eye",
        relation="Set Jasper his task", affiliation="Dragon's Eye",
        met='visions', aff='dragons-eye', standing='Unknown', last=8, status='Active',
        aliases=['Lucky'],
        overview="Lucky Leppomanto is the guild master of the Dragon's Eye. Lucky set Jasper his task: steal the Orb of Dragonkind from the Tower of Wayreth. Jasper has seen Lucky only in a dream and in the river's apparitions.",
        links=['pc:jasper', 'npc:seredyn', 'npc:finbar', 'item:dragons-eye-coin',
               'quest:the-orb-of-dragonkind', 'fac:the-dragons-eye'],
        records={
            2: ["Appeared in Jasper's dream of the guild, the coin and the task"],
            8: ["Appeared to Jasper in the river and warned that time was running out"],
            10: ["Had told Seredyn nothing of Jasper's presence or task in Kalaman"],
        },
    ),
    dict(
        slug='theros-flametongue', name='Theros Flametongue', role='Orcish warrior with a flaming axe',
        relation='Defeated adversary, returned', affiliation='Red Dragon Army',
        met='vogler', aff='red-dragon-army', standing='Adversary', last=7, status='Slain, then risen',
        portrait=IMG + '11vuG_FppfLpj1OMBTRuGTnc5hTGlMpqS',
        overview="Theros Flametongue is a green-skinned orcish warrior who rode into Vogler on the dragon machine carrying a flaming axe. Mayriel killed him on the docks. As the boats pulled away, a figure stood over his body, flame passed across him, and he rose.",
        links=['item:the-emberwake-greataxe', 'pc:aratos', 'pc:mayriel', 'quest:theros-flametongue',
               'fac:the-red-dragon-army', 'place:vogler'],
        records={
            7: ["Leapt from the dragon machine and mocked what he had heard of Vogler's heroes",
                "Dueled Aratos at the heart of the burning dock",
                "Was killed by Mayriel's spiritual sword",
                "Lost his axe to Aratos",
                "A figure stood over his body; flame passed across him and he rose"],
        },
    ),
    dict(
        slug='the-charred-swordswoman', name='The Charred Swordswoman', role='Unidentified warrior',
        relation='Unidentified adversary', affiliation='Red Dragon Army',
        met='vogler', aff='red-dragon-army', standing='Adversary', last=7, status='Unknown',
        overview="A tall woman with charred skin, blackened armor and a massive sword, seen through the smoke at Vogler's waterfront. The party does not know her name.",
        links=['npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'fac:the-red-dragon-army', 'place:vogler'],
        records={
            7: ["Held back on the waterfront by Becklin and Cudgel as the last boat left",
                "Kicked Cudgel Ironsmile aside through a building"],
        },
    ),
    dict(
        slug='lord-soth', name='Lord Soth', role='Fallen Knight of Solamnia',
        relation='Looming antagonist', affiliation='Knights of Solamnia (fallen)',
        met='visions', aff='knights', standing='Adversary', last=9, status='At large',
        overview="Lord Soth was once a celebrated Knight of Solamnia. He fell through selfishness and personal failure and lives in disgrace under a curse. He works through servants to corrupt knights and their legacies, and means to continue until the curse is lifted. Aratos has seen him in the river's apparitions, and the party has fought one of his servants.",
        links=['quest:lord-soths-corruption', 'quest:the-leviathan-axe', 'pc:aratos', 'pc:aeimos',
               'npc:sir-cthondor', 'npc:the-pale-woman', 'fac:the-knights-of-solamnia',
               'place:the-reliquary-of-sir-cthondor'],
        records={
            8: ["Appeared to Aratos in the river opposite Cathan Twice-Born; the two told him he would have to choose soon",
                "His statue stands in Kalaman's courtyard among knights once honored"],
            9: ["A necromancer died in his service while corrupting the tomb of Sir Cthondor",
                "Said by the pale woman to seek the corruption of all knights: their image, their legacies, and the memory of what they were"],
        },
    ),
    dict(
        slug='sir-cthondor', name='Sir Cthondor', role="Knight of the hidden reliquary, at rest",
        relation='Freed spirit', affiliation="The reliquary of the Knights Radiant",
        met='kalaman', aff='knights', standing='Ally', last=10, status='At rest',
        overview="Sir Cthondor was a knight whose tomb lies in a hidden reliquary of the Knights Radiant outside Kalaman. A necromancer serving Lord Soth raised his spirit as a wraith. Freed, he named Aratos and Aeimos children of Cathan and sounded his horn to send the risen dead back to rest.",
        links=['place:the-reliquary-of-sir-cthondor', 'item:horn-of-sir-cthondor', 'npc:lord-soth',
               'pc:aratos', 'pc:aeimos', 'fac:the-knights-radiant', 'quest:meat-for-ispins-stew'],
        records={
            9: ["Stood at the center of the tomb, horn in the crook of his arm, as he does in the murals",
                "Rose as a wraith in violet shadow when the necromancer's ritual went far enough",
                "Was freed by Roshi's spiritual weapon",
                "Named Aratos and Aeimos children of Cathan and told them they had proven themselves",
                "Blew his horn and returned the risen knights to rest"],
            10: ["Aratos knelt before his statue and asked the honored dead for help carrying the axe"],
        },
    ),
    dict(
        slug='the-pale-woman', name='The Pale Woman', role='Unidentified figure',
        relation='Mysterious guide to Aeimos', affiliation='Unknown',
        met='kalaman', aff='unaffiliated', standing='Unknown', last=9, status='Active',
        overview="A pale, beautiful woman with pointed ears and long flowing hair who appears to Aeimos, points, and vanishes. He could not tell what she was. She has spoken once.",
        links=['pc:aeimos', 'npc:lord-soth', 'quest:lord-soths-corruption'],
        records={
            9: ["Appeared behind Mayriel during the hunt and pointed toward the others",
                "Told Aeimos that Lord Soth seeks to corrupt all knights until his curse is lifted",
                "Pointed into the distance when he asked where to go"],
        },
    ),
    dict(
        slug='sunscale', name='Sunscale', role='Golden finch',
        relation="Mayriel's companion", affiliation='Unknown',
        met='vogler', aff='unaffiliated', standing='Ally', last=8, status='Active',
        overview="Sunscale is a golden finch that appeared to Mayriel in Vogler. It had kept company with Fizban; given the choice in Kalaman, it stayed with her.",
        links=['pc:mayriel', 'npc:fizban', 'item:divine-pendant'],
        records={
            4: ["Mayriel woke to a golden finch and a pendant"],
            7: ["The golden finch swept into view as Mayriel pledged her ring; its radiance restored the party enough to move"],
            8: ["Returned to Fizban, then made its choice and stayed with Mayriel"],
        },
    ),
    dict(
        slug='ispin-greenshield', name='Ispin Greenshield', role='Late adventurer, friend to many',
        relation='Honored dead', affiliation='None',
        met='vogler', aff='unaffiliated', standing='Ally', last=8, status='Dead',
        overview="Ispin Greenshield was an old human adventurer, remembered fondly by elves and townsfolk alike. His funeral in Vogler drew Roshi and Mayriel onto the road. He asked that it be an evening of stories.",
        links=['item:ispins-green-shield', 'pc:roshi', 'npc:becklin-uth-viharin', 'npc:fizban',
               'place:vogler', 'item:fizbans-stew-recipe'],
        records={
            1: ["Letters of his death drew Roshi and Mayriel toward Vogler"],
            4: ["Was sent down the Vingaard in a shrouded boat at sunset",
                "Was remembered at the Brass Crab: the volcano ridden on a shield, the bear den and the honey, the wyrmling",
                "His green shield passed to Roshi"],
            8: ["Appeared to Roshi in the river, asking whether she had truly protected the villagers"],
            9: ["Fizban cooked what he said was Ispin's stew recipe, and it fed the refugee camp for a night"],
        },
    ),
]

# Named, but with nothing behind the name worth a page. One line each.
UNFILED = [
    ('Jeyev', "Cudgel's loyal lieutenant, shaved-headed. Rode out to gather her loyal mercenaries in Journey 006 and carried Darrett off the front line in 007."),
    ('Tatina Rookledust', "A tinkerer several days' travel from Kalaman. Marshal Vendri believes she can explain the mechanical dragon. Not yet met."),
    ('Cathan Twice-Born', "Ancestor of Aratos and Aeimos. Appeared to Aratos in the river in Journey 008, opposite Lord Soth. Sir Cthondor's spirit named the cousins children of Cathan in Journey 009."),
    ('The King', "A hooded, kingly figure among the ancestral spirits who appear when Aratos rages. Came to him twice in Journey 010 with warnings: the same blood flows through my veins. The same weakness."),
    ('Gribb Brack', "A farmer in Bracken Hollow, a few houses down from Boyd's shelter. Boyd says he would know about frostlace. Not yet met."),
    ('Marigold', "A healer and something of a mystic. Her cottage stands just outside Bracken Hollow, and she travels between villages tending the sick. She was away on the night the village closed."),
    ('Nora', "A villager of Bracken Hollow who is unwell. Corvin named her in Journey 011, when he said people needed to eat."),
    ('Gertrude', "Smith in Vogler. Aratos met Becklin at her smithy in Journey 003."),
]
