"""
campaign_people.py - the Embers and everyone they have met.

Player-known framing only. Sources: the Unexpected Journey accounts 001-011
and the campaign tracker (Player Characters, NPCs). Nothing here should say
more than a player at the table could.

References to other records use "kind:slug":
    pc:   the-embers/      npc:  dossiers/      item:  armory/
    place: atlas/          fac:  war-intel/     quest: quests/

`records` maps a journey number to what that journey added. The highest
number shows open on the page; the rest fold under "Previous Journeys".
"""

IMG = 'https://lh3.googleusercontent.com/d/'

# ---------------------------------------------------------------------------
# THE EMBERS
# ---------------------------------------------------------------------------

PCS = [
    dict(
        slug='aratos', name='Aratos Stormblessed', short='Aratos',
        race='Half-Elf', klass='Barbarian', portrait=IMG + '1FocmkAQsG7XDRJPrGZMtQerhkHxSvYNV',
        sub="Barbarian of the Ancestral Guardians; a Knight Radiant of Cathan's line",
        affiliation='Knights Radiant; the Embers', first=1, last=11, status='Active',
        overview=[
            "A vision came to Aratos like a summons: scaled warriors marching in ranks, and one command in it, fight. He set out for Kalaman to warn the Knights of Solamnia.",
            "He is a barbarian whose ancestors gather around him when he rages, and a Knight Radiant of Cathan's line, as is his cousin Aeimos. He was first to speak his oath at the reliquary door and first to challenge the monument at Bracken Hollow. He carries the Emberwake, a cursed axe he took as a trophy at Vogler.",
        ],
        pursuit="Trying to hold to the path of restraint he chose, after the Emberwake's fury took him at Bracken Hollow.",
        state="Unconscious on the hill at Bracken Hollow, guarded by the spectral warriors of the horn. The monument marked him with the black glow.",
        line="Took the head off the monument at Bracken Hollow in a fury that was not his own, and had to be brought down by Roshi.",
        links=['item:the-emberwake-greataxe', 'item:horn-of-sir-cthondor', 'quest:the-emberwakes-curse',
               'quest:the-leviathan-axe', 'quest:the-first-mission', 'pc:aeimos', 'npc:theros-flametongue',
               'fac:the-knights-radiant', 'place:bracken-hollow', 'npc:ked'],
        records={
            1: ["Woke from a dream of scaled warriors marching in ranks, with one command in it: fight",
                "Recognized the ambushers on the road from that dream and charged",
                "Told the others his dream after the ambush and asked for their help"],
            2: ["Recognized the dead knights' armor as that of the Knights of Solamnia and found their briefing on attacks against local farmers",
                "Hurled his javelin through the frozen sand creature in a streak of lightning"],
            3: ["Told Becklin at Gertrude's smithy that he carried a warning for her order, and agreed to speak with her later at the Brass Crab",
                "Reunited with his cousin Aeimos, who stole his ring before saying hello",
                "Asked Aeimos to join the journey to the Knights of Solamnia",
                "Drove lightning through the beast beneath Crustdurn Isle, then hauled on Aeimos's rope for the killing blow"],
            4: ["Told Becklin his vision and Mayriel's; she promised a letter for Kalaman",
                "Sought out the Bakaris house to ask about Kalaman and found only the son",
                "Called for one attacker to be taken alive when the mock battle at High Hill turned real",
                "Kept Darrett close through the first of the fighting"],
            5: ["Saw a colossal tree split between flame and frost, and a stern, ancient warrior at its foot, who told him to choose: blades of fury, or an axe of cold restraint",
                "Scouted the woods and saw a broad figure on patrol, built like the creatures from the road"],
            6: ["Worked on Lord Bakaris with Kakashi, hailing him as the savior the town needed",
                "Tried to bluff a cliffside watcher and ended up with a blade at his throat",
                "Felt his axe run cold as his swing missed, and heard the elder warrior's voice say one word: prove",
                "Threw his javelin as a bolt of lightning through two of the enemy",
                "Gave up his attack to pour a healing potion into Mayriel",
                "Killed the Red Army's messenger with a javelin through the heart",
                "Was asked by Becklin to bring a chest from Thornwall Keep to Darrett once things settled"],
            7: ["Brought Becklin's chest down from Thornwall Keep with Roshi during the evacuation",
                "Helped Than clear draconians from Thornwall Keep during the evacuation",
                "Charged Theros Flametongue and drew first blood, his ancestors gathered around him",
                "Had his axe torn from his hands, fought on with his sword and took the axe back up",
                "Brought down the dragon machine with his javelin of lightning as the elder warrior's rough old voice said one word in his ear: good",
                "Went down when the machine crashed and was healed by Mayriel",
                "Threw the javelin again; cold ran down his arm, the elder warrior's voice asked if he was worthy, and the javelin changed shape for a moment before it changed back and missed",
                "Took Theros's still-warm axe from beside the body"],
            8: ["Took up the Emberwake Greataxe on the river",
                "Saw Cathan Twice-Born and Lord Soth in the water, and was told he would have to choose soon",
                "Silenced Lord Bakaris in the council chamber",
                "Named himself a Knight Radiant; Marshal Vendri acknowledged the title"],
            9: ["Spoke his oath at the reliquary door and lit the word Valor",
                "Felt the Emberwake sit heavier in his hands than it should",
                "Held the necromancer in place when he tried to slip away in the darkness",
                "Was named a child of Cathan by the spirit of Sir Cthondor",
                "Cut off the necromancer's head for the party to show the city",
                "Was left the horn by Aeimos"],
            10: ["Saw the tree of fire and frost in the campfire, and the King, who warned that the same weakness runs in his blood",
                 "Asked a bird to warn the camp of danger",
                 "Told Mayriel of ancestors who were given visions of warning and did nothing, and of two paths, fire and ice",
                 "Lost himself to the axe in a sparring match and cut down the squire Roberto, who survived",
                 "Turned the axe toward Darrett, who held his arm until the rage passed",
                 "Took the axe back from Darrett, could not hand it to Roshi, and found he cannot part with it",
                 "Saw the King among his companions in Kalaman: don't let it overtake you",
                 "Stood before Sir Cthondor's statue and chose resolve; the flames died and for a moment he held the Leviathan Axe"],
            11: ["Opened a wolf from shoulder to flank with the Emberwake; green flame leapt to the next",
                 "Drew the truth about the hill out of Boyd and Corvin",
                 "Promised Ked the Embers would protect him with their lives",
                 "Challenged the monument; its black ring flared and he was marked with the black glow",
                 "Blew the Horn of Sir Cthondor; five spectral warriors answered",
                 "Lost himself to the axe's fury, took the monument's head, and was struck senseless by Roshi"],
        },
    ),
    dict(
        slug='kakashi', name='Kakashi', short='Kakashi',
        race='Human', klass='Wizard', portrait=IMG + '1USG7Cr8dArWVq8HCEe99o3IQMOBCD26K',
        sub='Wizard in training, testing for the White Robes of High Sorcery',
        affiliation='High Sorcery (White Robes candidate); the Embers', first=1, last=11, status='Active',
        overview=[
            "Kakashi is a wizard who keeps a raven familiar. He passed a mage trial beside Jasper and met the others in the ambush on the road to Vogler.",
            "Since the night the moons aligned on his watch he has wanted greater magic, urgently. He reads what others miss: the cipher in Fizban's recipe, the curse on Aratos's axe, the spellwork over Bracken Hollow. Wyhan has set him to test for the White Robes.",
        ],
        pursuit="Growing his power and earning his White Robes, while puzzling over a vision of a tower.",
        state="Inside Bracken Hollow with less than a day to break its spell. Still awaiting his White Robes exam.",
        line="Saw the lattice of spellwork over Bracken Hollow and its three knots, and found the three recesses beneath the hill.",
        links=['item:boilerdrake-heart', 'item:moon-marked-spellbook', 'item:armor-of-the-fallen', 'item:ring-of-protection',
               'quest:the-white-robes',
               'quest:kakashis-tower-vision', 'quest:kakashis-buried-past', 'npc:wyhan',
               'fac:the-mages-of-high-sorcery'],
        records={
            1: ["Confirmed the spell of opening in the mage trial, suspected the key was a trap, and passed alongside Jasper",
                "Received with Jasper a moon-marked spellbook and a scroll sending them on to Kalaman",
                "Sent a raven to carry his lightning in the ambush on the road"],
            2: ["Saw the three moons merge on his solo watch and heard three voices say he was not strong enough, not yet",
                "Recognized Fizban's incantation, revived Roshi with a healing potion and dragged her clear"],
            3: ["Heard from the Brass Crab's barkeep that the fishers were having trouble",
                "Found divine traces on the fish statue at the docks",
                "Sent his raven over the river and found the abandoned shack on Crustdurn Isle through its eyes",
                "Opened the fight below with a burst of ice"],
            4: ["Backed Roshi's claim to Ispin's shield",
                "Was left a note and the spell Shield by Fizban as a parting gift",
                "Struck his staff on the ground and got Bakaris the Younger to say his father would judge the mock battle",
                "Took the winged boots and fought from the air at High Hill",
                "Found the Red Army note on the half-ogre and shared it with the party"],
            5: ["Sent his raven to follow Cudgel at a distance; it had not returned by night's end",
                "Hid himself and Darrett under an illusory boulder at the edge of the camp"],
            6: ["His raven brought word that Cudgel was returning, and later counted four watchers on the cliff",
                "Worked on Lord Bakaris with Aratos, pressing him to ride to Kalaman in person",
                "Stilled a panicking crowd with a flash of power, then with gentleness",
                "Asked the messenger to let the women and children leave, and was refused",
                "Conjured a scream for help to turn the messenger's head",
                "Loosed a blue lightning strike that sounded like a thousand birds and left the messenger badly hurt"],
            7: ["Helped Than clear draconians from Thornwall Keep during the evacuation",
                "Struck Theros in the face with his Chidori, lightning that sounded like a thousand birds",
                "Turned a bolt of lightning aside with a shield of force",
                "Reached into the wreck and killed the last operator, and was dropped by the blast",
                "Remembered something he had pushed away long ago: a village set aflame, people burning and crying",
                "Pulled the Boilerdrake Heart from the wreckage; it burned his hand",
                "Urged the party to leave, help the villagers who had escaped and spread word of what they had seen"],
            8: ["Attuned to the Boilerdrake Heart",
                "Presented his High Sorcery scroll to Wyhan; he will test for the White Robes"],
            9: ["Understood that the reliquary door was testing the virtues of knighthood: six symbols shown, four of them correct",
                "Touched the door, offered what drives him, and lit the word Foresight",
                "Pushed the Boilerdrake Heart past its limits against the wraith",
                "Read the bone armor as necrotic and the horn as a thing made to call aid",
                "Told Fizban they needed to talk after dinner",
                "Asked around for what he needs to call his raven back"],
            10: ["Took the Armor of the Fallen and felt it bind to his soul; if he dies, it is lost",
                 "Read the numbers in Fizban's recipe as a wizard's cipher",
                 "Was turned away from Wyhan's door at night",
                 "Met Darrett before dawn and asked him to listen for anything unusual",
                 "Saw an elven woman in a pail of water, warding a round room of relics, who told him: you have to fight, keep them safe",
                 "Bought what he needs to call his raven back, and gave Wyhan the recipe's numbers from memory",
                 "Judged Aratos's axe cursed, and that a spell to lift it most likely lies with clerics and paladins"],
            11: ["Called his raven back and carried Wyhan's list down the road",
                 "Gathered willowbark, pine resin and graveyard moss",
                 "Dug bones from a fresh grave and raised a skeleton on the hill",
                 "Struck the monument first, with lightning",
                 "Fell to the moons' light, and as he fell saw a lattice of spellwork over the village with three knots in it",
                 "Dimmed the black ring and turned a blow away from Aratos",
                 "Read the rings as receivers and found the cavern with three recesses",
                 "Was sure the three missing things are something other than the monument's rings"],
        },
    ),
    dict(
        slug='jasper', name='Jasper Quickwit', short='Jasper',
        race='Human', klass='Rogue', portrait=IMG + '1zX6MfbMgXijkdr9IOJLbGnWdMS3wtoR1',
        sub="Rogue bound to the Dragon's Eye thieves' guild",
        affiliation="Dragon's Eye; the Embers", first=1, last=11, status='Active',
        overview=[
            "Jasper is a rogue who passed a mage trial behind an apprentice's mask. The Dragon's Eye, a thieves' guild, bound him with a deadly coin and set him a task: find the moving Tower of Wayreth and steal the Orb of Dragonkind.",
            "He scouts ahead alone and shoots from cover. He scouted the Red Army camp outside Vogler, saw that the dragon was a machine, and noticed Corvin watching Ked. When Old Man Jenkins packed to flee Vogler, Jasper stayed, saying the town was good and its people needed help.",
        ],
        pursuit="Carrying out the task the Dragon's Eye set him: stealing the Orb of Dragonkind from the moving Tower of Wayreth.",
        state="In Bracken Hollow with the rest. Lucky's warning from the river still stands: time is running out on the Orb.",
        line="Read Corvin in Boyd's shelter, and went down into the cavern beneath the hill with Kakashi.",
        links=['item:winged-boots', 'item:leeching-arrows', 'item:boots-of-false-tracks', 'item:dragon-vessel',
               'item:dragons-eye-coin',
               'quest:the-orb-of-dragonkind', 'quest:the-white-robes', 'quest:finbar',
               'npc:lucky', 'npc:seredyn', 'npc:finbar', 'fac:the-dragons-eye'],
        records={
            1: ["Felt his way through the invisible maze of the mage trial and recognized the spell of opening carved in the runes",
                "Struck from hiding in the ambush on the road"],
            2: ["Dreamed of the guildmaster he once conned, the coin and the mark, and of the task: join the mages and reach the moving Tower of Wayreth, which holds the Orb of Dragonkind",
                "Sank to his ankles in the living sand, then cut an opening that showed the old man trapped inside",
                "Alone in Vogler's market square, saw a small figure inside the shape of a hunched old man"],
            3: ["Saw an older figure wrapped in a strange shimmer on the way to Thornwall Keep, walked on and told no one",
                "Met Becklin at Thornwall Keep and heard from the fishers of an odd sound in the water at night",
                "Spotted the island from the docks and found a journal page in its shack",
                "Vanished into the shadows of the cavern; his arrows found the killing angles on the beast"],
            4: ["Slipped away to General Goods, where Old Man Jenkins put a blade to his throat and then taught him the guild's phrase",
                "Bought winged boots with the party's shared gold and called it a slick deal",
                "Told Aratos the meeting had gone well and nothing of the guild",
                "Killed a traitor before he could cut Darrett down",
                "Shot the half-ogre through the head"],
            5: ["Crept alone to the edge of the camp in the woods and estimated one to two hundred soldiers",
                "Threw a rock to draw a patrol off his companions, then used the Dragon's Eye coin to pass as a soldier",
                "Reported the camp to Mayor Raven and Becklin",
                "Told Jenkins the town was good and its people needed help, and was given healing potions, leeching arrows and the name Finbar"],
            6: ["Flew to the cliff on the winged boots and hid",
                "Shot one watcher through the skull",
                "Loosed one of the leeching arrows from the cliff"],
            7: ["Helped Than clear draconians from Thornwall Keep during the evacuation",
                "Rose over the docks on the winged boots and saw that the dragon was a machine with a crew inside",
                "Told the others what he had seen",
                "Saw Jeyev carrying Darrett through the smoke, and was the only one to see Finbar",
                "Killed the lightning-throwing creature, which burst apart as it fell",
                "Heard from Jeyev that Becklin and Cudgel had ordered him to take Darrett and run",
                "Took a last look from the air and told the others only that it looked bad"],
            8: ["Saw Lucky in the river, warning that time was running out",
                "Overheard the council's private deliberation",
                "Caught a shimmer of illusion on one figure leaving the council chamber and knew the Dragon's Eye had reached Kalaman",
                "Presented his High Sorcery scroll to Wyhan; he will test for the White Robes"],
            9: ["Was the only one to notice Aeimos shadowing the party",
                "Slipped out of the necromancer's darkness and broke his concentration with a shot",
                "Was drained by the wraith's touch and drank a healing potion",
                "Found a note in Thieves' Cant marked with the Dragon's Eye: We need to talk"],
            10: ["Left the fire in sight of the others and followed Finbar, who wore a human face that was not Jenkins's, into Kalaman by night",
                 "Met Seredyn, head of the Kalaman branch, at Finn's Bar, and was caught in a thin lie",
                 "Was told that Lucky rarely recruits so freely, and that he answers to Seredyn while in Kalaman",
                 "Was told Wyhan is his best lead to the tower, and to plan his way out before he goes in",
                 "Told Roshi only that he had visited an old friend"],
            11: ["Spotted Bracken Hollow through the trees",
                 "Dropped the first wolf and the last",
                 "Saw Corvin watching Ked and judged he was working toward something",
                 "Called out that ordinary weapons were doing half their work",
                 "Threw his spear at the monument and missed; it stayed on the hillside",
                 "Put a leeching arrow into the monument",
                 "Went down into the cavern beneath the hill with Kakashi"],
        },
    ),
    dict(
        slug='roshi', name='Roshi', short='Roshi',
        race="Elf", klass='Paladin of Kiri-Jolith', portrait=IMG + '1aY9zew4XAuhOWbXfOB2Vfm7FKDzfZonc',
        sub="Devoted protector carrying Ispin's legacy",
        affiliation='The Embers', first=1, last=11, status='Active',
        overview=[
            "Roshi took the road to Vogler for the funeral of Ispin Greenshield. On the way, near the remnants of an old holy place, she felt a sacred calling settle on her.",
            "She puts herself between danger and other people, as she did against the half-ogre at High Hill and the messenger at Vogler's gate. Her hands heal, which no one in living memory had seen. She carries Ispin's green shield and a moon-touched sword.",
        ],
        pursuit="Living up to Ispin's example as a shield for others, and growing into her sacred calling.",
        state="Hurt but standing after the hill at Bracken Hollow. Wears the periapt that kept her alive.",
        line="Brought the fallen back on the hill at Bracken Hollow, then dropped Aratos before his fury could turn on his friends.",
        links=['item:ispins-green-shield', 'item:moon-touched-sword', 'npc:ispin-greenshield',
               'npc:becklin-uth-viharin', 'quest:the-emberwakes-curse'],
        records={
            1: ["Was told by a great bison statue at an old holy place to take up arms and gather a party",
                "Grappled one of the ambushers and demanded to know who sent it",
                "Tackled the last ambusher as it fled"],
            2: ["Dug graves for the dead knights and gave them solemn care",
                "Thought of Ispin on her watch",
                "Was struck down by the sand creature and nearly killed",
                "Sensed a faint golden aura around Fizban"],
            3: ["Ate crab ramen at the Brass Crab despite the danger to her health",
                "Was swallowed by the beast beneath Crustdurn Isle"],
            4: ["Told the story of Ispin and the bear den",
                "Asked for Ispin's shield when Fizban declined it",
                "Received Ispin's Green Shield at Thornwall Keep, with the request that she fight in the mock battle",
                "Found the shield could wrap her in the illusion of a boulder or a tree",
                "Was first to see the riders and the half-ogre coming",
                "Held against the half-ogre until her blade lit with divine fire"],
            5: ["Stayed to guard Vogler and rest",
                "Healed a fisherman by laying on hands, and was asked whether the gods had touched her",
                "Was told nothing like it had been seen in centuries"],
            6: ["Found Than at Thornwall Keep and asked for help delaying a massacre",
                "Spotted the messenger's watchers from the keep and brought word back",
                "Hid Kakashi's casting and ran toward the false scream",
                "Was burned by lightning thrown from the cliff",
                "Challenged the mounted messenger and drew his attention onto herself"],
            7: ["Brought Becklin's chest down from Thornwall Keep with Aratos during the evacuation",
                "Put arrows into the dragon machine from the docks",
                "Went down when the machine crashed and was kept from death by the periapt she wore",
                "Woke to a potion from Than"],
            8: ["Saw Ispin in the river asking whether she had protected the villagers, and answered that she had done what she could",
                "Offered Becklin's armor to Darrett"],
            9: ["Thought of her oath at the door, to leave the world better than she found it, and felt the spoke of protection answer",
                "Charged the necromancer with her greatsword; radiant rose-thorns burst from the blade",
                "Held the wraith close with a champion's challenge"],
            10: ["Picked up the parchment Fizban dropped and read the spell's name in its reminder",
                 "Sensed on watch that Jasper was not telling her everything",
                 "Worked the incantation out of the recipe and spoke it, teaching all five the Green Flame Blade",
                 "Offered to hold the Emberwake; Aratos could not hand it over"],
            11: ["Hid inside an illusory griffon and let a wolf run onto her sword",
                 "Struck the monument with her moon-touched sword as it hummed in the light of Solinari, the white moon",
                 "Fell to the moons' light and was held from death by the periapt",
                 "Laid hands on Kakashi, then cried out and healed them all",
                 "Dropped Aratos with one blow when the fury would not leave him"],
        },
    ),
    dict(
        slug='mayriel', name='Mayriel', short='Mayriel',
        race='Elf', klass='Cleric of Paladine', portrait=IMG + '1VKa7NEkNHE6cGsNfNBckPyjOvvKLPrkM',
        sub='Cleric of Paladine; divine magic returned',
        affiliation='Faithful of Paladine; the Embers', first=1, last=11, status='Active',
        overview=[
            "Mayriel traveled with Roshi to Ispin's funeral. On the road she saw a vision of divine fire. In Vogler she saw another: a horned woman who became a five-headed dragon, and the platinum fire that shielded her from it.",
            "She heals and fights in the same breath. On the burning docks of Vogler she pledged Paladine her family signet ring, and her obedience when the god asks for it. The Dragon Queen has told her that her sword will find her.",
        ],
        pursuit="Walking her divine calling, and waiting for the sword the Dragon Queen has promised will find her.",
        state="On the hill at Bracken Hollow, under an eclipse she has seen before. She has had no new vision since the river.",
        line="Knew the eclipse over Bracken Hollow for the one she saw a month ago, though it should come once a year.",
        links=['item:mayriels-signet-ring', 'item:divine-pendant', 'npc:sunscale',
               'quest:the-sword-of-the-dragon-queen', 'quest:the-emberwakes-curse', 'npc:fizban'],
        records={
            1: ["Watched a silver dragon statue rebuild itself at an old holy place; a voice promised her power against a coming evil, and platinum flames rose around her",
                "Alone understood the ambushers' Draconic: the Shadow Queen sent us",
                "Translated the prisoner's answers for the others"],
            2: ["A golden canary landed on her shoulder during the night watch, then flew away",
                "Kept Roshi alive after the sand creature struck",
                "Drew Fizban's interest: clerics had not been seen for some three hundred years"],
            3: ["Saw a horned woman in dark regalia unfold into a five-headed dragon, and platinum fire rise to shield her"],
            4: ["Spoke for Ispin at the Brass Crab, though she had only known of him, and silenced the room",
                "Agreed to travel on with the others for a while",
                "Had her vision told to Becklin alongside Aratos's",
                "Woke to a golden canary and a pendant; a voice spoke through the bird to her alone"],
            5: ["Followed a canary to a woman hiding a fatal wound and healed her; the woman had seen no bird",
                "Was asked whether the gods had touched her, and answered yes",
                "Urged Mayor Raven to fortify the town"],
            6: ["Put one watcher to sleep",
                "Called down moonlit radiance on the cliff and burned a watcher to ash",
                "Was struck down by red lightning, and was brought back by Aratos with a healing potion"],
            7: ["Helped Than clear draconians from Thornwall Keep during the evacuation",
                "Raised a twilight glow over her companions at the docks",
                "Blessed her companions; small golden dragons appeared around them",
                "Was knocked flat by Theros and kept hold of her mace when he tried to strike it from her hand",
                "Killed Theros Flametongue: drove him to one knee, then put her spiritual sword through his throat",
                "Healed Aratos and Kakashi after the machine fell, and spotted the last living operator in the wreck",
                "Offered Paladine her family signet ring and swore to do what he asks when the time comes"],
            8: ["Saw the Dragon Queen in the river, who promised her sword would find her",
                "Kept Sunscale, who chose her over Fizban"],
            9: ["Saw purplish-black soot on the cave floor and remembered the river",
                "Burned the wraith with sacred flame",
                "Was drained by the wraith's touch",
                "Turned the dead knights with her divine power",
                "Ended the wraith with a spiritual weapon shaped like a rose"],
            10: ["Pointed the others to the reminder at the bottom of Fizban's recipe",
                 "Told Aratos she has had no new vision since the river, and that the silence feels suspicious",
                 "Heard Aratos wonder whether the promised sword might be a person, even the party itself",
                 "Bought two healer's kits from Wyhan"],
            11: ["Sharpened Kakashi's eyes on the road and spotted the village with Jasper",
                 "Knew the three-moon eclipse from a month before, though it should come once a year",
                 "Heard her longbow hum its warning before the wolves howled",
                 "Blessed and strengthened her companions through both fights",
                 "Left the monument glowing with a guiding bolt and struck at its rings"],
        },
    ),
    dict(
        slug='aeimos', name='Aeimos Stormblessed', short='Aeimos',
        race='Human', klass='Monk', portrait=IMG + '1Fv4WEzpgAcrSBF7rxjmVI8sc1bLz8DqV',
        sub='Stormblessed kin to Aratos; a recurring guest',
        affiliation='Knights Radiant; Stormblessed kin', first=3, last=9, status='Companion',
        overview=[
            "Aeimos is Aratos's cousin and carries Stormblessed markings in blue where Aratos's are red. He announced himself in Vogler by stealing Aratos's ring. He fights with storm-charged gauntlets.",
            "He comes and goes on his own road. He left Vogler with Fizban, returned outside Kalaman for the reliquary of Sir Cthondor, and left again to seek out the other tombs Lord Soth means to corrupt.",
        ],
        pursuit="Seeking out the knights' tombs that Lord Soth means to corrupt, on a road apart from the party's.",
        state="Off on his own road against Soth's corruption. Appears and vanishes.",
        line="Left the horn with Aratos and went where the pale woman pointed.",
        links=['item:storm-charged-gauntlets', 'item:horn-of-sir-cthondor', 'pc:aratos',
               'npc:the-pale-woman', 'npc:lord-soth', 'quest:lord-soths-corruption',
               'fac:the-knights-radiant'],
        records={
            3: ["Stole Aratos's ring as a greeting",
                "Was asked to join the journey to the Knights of Solamnia and gave no firm answer",
                "Paid a fisherman in fresh-caught fish to row the party to Crustdurn Isle",
                "Broke the beast's jaw, killed it with a lightning-charged blow and cut out its tongue"],
            4: ["Left Vogler with Fizban before the others woke"],
            8: ["Named by Marshal Vendri as aiding other villages alongside Fizban"],
            9: ["Returned from the road with Fizban and shadowed the party, noticed only by Jasper",
                "Saw a pale woman behind Mayriel who pointed him toward the others, and told the party only that something was wrong",
                "Spoke his oath under his breath at the door and lit the word Resolve",
                "Pressed his head to the door, said this too shall pass, and lit a third spoke",
                "Beat the necromancer down and saw that the ritual had been cut short",
                "Was named a child of Cathan",
                "Blew the horn of Sir Cthondor and saw two spectral knights answer",
                "Heard a whisper outside the tomb: there are more, and he wishes to take them",
                "Left the horn with Aratos and slipped away",
                "Was told by the pale woman that Lord Soth wishes to corrupt all knights until his curse is lifted, and told no one"],
        },
    ),
]

# ---------------------------------------------------------------------------
# DOSSIERS
# ---------------------------------------------------------------------------
# met:      vogler | kalaman | the-road | visions      (first facet: where met)
# aff:      slug used by the second facet, with AFF_LABELS below
# standing: Ally | Neutral | Adversary | Unknown       (never a spoiler)

AFF_LABELS = {
    'kalaman': 'Kalaman',
    'vogler': 'Vogler',
    'dragons-eye': "Dragon's Eye",
    'red-dragon-army': 'Red Dragon Army',
    'knights': 'Knightly Orders',
    'high-sorcery': 'High Sorcery',
    'bracken-hollow': 'Bracken Hollow',
    'unaffiliated': 'Unaffiliated',
}
MET_LABELS = {
    'vogler': 'Vogler',
    'kalaman': 'Kalaman',
    'the-road': 'The Road',
    'bracken-hollow': 'Bracken Hollow',
    'visions': 'Dreams and Visions',
}

NPCS = [
    dict(
        slug='becklin-uth-viharin', name='Becklin Uth Viharin', role='Retired Knight of Solamnia',
        relation='Fallen mentor', affiliation='Knights of Solamnia (retired)',
        met='vogler', aff='knights', standing='Ally', last=7, status='Fallen',
        portrait=IMG + '1SsOS6K-8vuYw1Sqk4V15MIk98GEnMgu8',
        overview="Becklin Uth Viharin was a retired Knight of Solamnia living in Vogler and an old friend of Ispin Greenshield. She believed the party's warnings, gave Roshi Ispin's shield, and held the docks so the boats could leave. She took two slashes across her back and fell into the Vingaard.",
        links=['npc:darrett-highwater', 'npc:ispin-greenshield', 'npc:cudgel-ironsmile',
               'npc:the-charred-swordswoman', 'item:ispins-green-shield', 'item:becklins-armor',
               'fac:the-knights-of-solamnia', 'place:vogler', 'quest:the-evacuation-of-vogler'],
        records={
            1: ["Wrote to Roshi and Mayriel, whom she had never met, inviting them to Ispin's memorial in Vogler on the eve of the Kingfisher Festival"],
            3: ["Met Aratos at Gertrude's smithy and agreed to hear his warning later at the Brass Crab",
                "Stopped Jasper at Thornwall Keep and told him Ispin's celebration was that evening",
                "Met the party's return from Crustdurn Isle with gratitude and surprise",
                "Said she was the only knight in Vogler, and invited the party to Ispin's celebration"],
            4: ["Spoke at Ispin's river funeral in her Solamnic armor",
                "Sent Bakaris the Younger out of the Brass Crab",
                "Said Ispin had wanted his shield to go to Fizban",
                "Promised a letter to help the party gain an audience in Kalaman",
                "Gave Roshi Ispin's Green Shield at Thornwall Keep and asked that she fight in the mock battle",
                "Cut through the traitors at High Hill beside Cudgel"],
            5: ["Kept her composure after High Hill when Cudgel could not",
                "Reported that assassins had also gone after the town's leaders",
                "Asked the party to stay and help defend Vogler"],
            6: ["Agreed that escape had to be prepared, and judged an attack likely",
                "Asked the rider how long Vogler had",
                "Took the front line with Cudgel and put the party in charge of the evacuation",
                "Asked Aratos to bring a chest from Thornwall Keep to Darrett once things settled"],
            7: ["Ordered Jeyev, with Cudgel, to take Darrett and run",
                "Struggled with Cudgel to hold back a charred woman in blackened armor on the waterfront",
                "Reached the edge of the dock and looked out at the party's boat, resigned and grateful",
                "Raised her hands as if to say it was all right",
                "Took two slashes across her back and fell into the dark water"],
            8: ["Appeared to Darrett in the river among the Ashen Vigils",
                "Her armor passed to Darrett"],
        },
    ),
    dict(
        slug='fizban', name='Fizban', role='Green-robed wizard, old friend of Ispin',
        relation='Eccentric ally and guide', affiliation='Unknown; wandering',
        met='the-road', aff='unaffiliated', standing='Ally', last=10, status='Active',
        portrait=IMG + '1jIx_p6EnUosUiQHOc2K-kjU8E0u62t4W',
        overview="Fizban is a peculiar old wizard in green robes, found trapped inside a living sand creature on the road to Vogler. He comes and goes on his own business, takes a keen interest in Mayriel's divine magic, and can be unsettlingly insightful.",
        links=['npc:ispin-greenshield', 'npc:sunscale', 'pc:mayriel', 'pc:aeimos',
               'item:fizbans-stew-recipe', 'quest:fizbans-recipe', 'quest:meat-for-ispins-stew'],
        records={
            2: ["Was pulled from inside a creature of living sand, then froze it solid and shattered it",
                "Introduced himself as an old friend of Ispin, on his way to Vogler to say his goodbyes",
                "Told Mayriel that clerics had not been seen for some three hundred years",
                "Called the Test of High Sorcery terrifying and cutthroat, and named Wyhan in Kalaman as the one to see"],
            3: ["Found Mayriel shaken after her vision at the docks and told her to listen",
                "Sent the others down to her from the Brass Crab, and stayed behind when they rowed out"],
            4: ["Told the tale of a stolen pie and an offended prince",
                "Declined Ispin's shield, saying it needed someone who would stand on the front line",
                "Said Mayriel's vision worried him and that he would try to arrange an audience in Kalaman",
                "Was gone for Kalaman by morning with Aeimos, leaving Kakashi a note and the spell Shield"],
            8: ["Named by Marshal Vendri as aiding other villages",
                "Greeted the party in Kalaman with sadness for Vogler",
                "Let Sunscale stay with Mayriel"],
            9: ["Proposed Ispin's stew as a remedy for despair and sent the party to hunt",
                "Agreed to talk with Kakashi after dinner and said he would be in Kalaman only another day or so"],
            10: ["Dozed by the fire with his pipe",
                 "Judged the stew a success and said he might be in Kalaman another day or so, learning what is going on outside the city",
                 "Dropped a recipe for Ispin's stew that turned out to hide the spell Green Flame Blade"],
        },
    ),
    dict(
        slug='darrett-highwater', name='Darrett Highwater', role="Becklin's former squire",
        relation="The Embers' proxy with Kalaman", affiliation='Vogler; Kalaman service',
        met='vogler', aff='kalaman', standing='Ally', last=10, status='Active',
        overview="Darrett Highwater was Becklin's young squire in Vogler. He survived the town's fall, accepted her armor as a promise to grow into it, and now stands as the Embers' proxy with Kalaman so they are not formally conscripted. He trains at the castle grounds and sleeps among the Voglerans.",
        links=['npc:becklin-uth-viharin', 'npc:marshal-vendri', 'item:becklins-armor',
               'quest:service-to-kalaman', 'place:the-refugee-camp'],
        records={
            4: ["Brought the party to Thornwall Keep and guided them through the festival",
                "Sparred with Roshi so she could try Ispin's shield",
                "Called the charge at High Hill and found his courage when it turned real",
                "Was set by Becklin to getting the wounded off the field"],
            5: ["Led the scouts into the woods, with more confidence than sense of direction"],
            6: ["Studied the town map with Becklin for places to reinforce"],
            7: ["Was carried from the front line on Jeyev's back, on Becklin's and Cudgel's orders"],
            8: ["Refused Becklin's armor on the river",
                "Saw Becklin in the water and was dragged under",
                "Accepted the armor and put it on at Kalaman's gates",
                "Told the council that Vogler sought refuge, not war",
                "Stepped forward as intermediary between the party and Kalaman"],
            9: ["Joined the stew feast late, covered in sweat and dirt from training"],
            10: ["Took his rest among the Voglerans rather than behind the walls",
                 "Left before dawn in Becklin's armor to train under Marshal Vendri",
                 "Caught Aratos's axe arm in the training yard and held on when the rage turned toward him",
                 "Tried to carry the Emberwake at Aratos's request; Aratos took it back",
                 "Told Vendri the dragon at Vogler was a machine",
                 "Offered to stand as the party's proxy and bear any obligation; Vendri accepted"],
        },
    ),
    dict(
        slug='marshal-vendri', name='Marshal Vendri', role='Marshal of Kalaman',
        relation='Commanding authority', affiliation='Kalaman military',
        met='kalaman', aff='kalaman', standing='Ally', last=10, status='Active',
        overview="Marshal Vendri commands Kalaman's military. He acknowledged Aratos as a Knight Radiant, takes the Embers' service through Darrett, and hands out their missions.",
        links=['npc:governor-miat', 'npc:darrett-highwater', 'npc:roberto', 'quest:the-first-mission',
               'quest:service-to-kalaman', 'place:kalaman'],
        records={
            8: ["Sat on the council and confirmed the whole region is under pressure",
                "Spoke of Fizban and Aeimos aiding other villages",
                "Acknowledged Aratos's title of Knight Radiant",
                "Asked for a name to record the party under"],
            10: ["Tried to seize Aratos in the training yard and was thrown off",
                 "Heard him out with a hand on his blade and overlooked it for the moment",
                 "Sent the Embers to track down the tinkerer Tatina Rookledust",
                 "Accepted Darrett as proxy, put the party on a stipend, and wrote its name in the record",
                 "Promised to see what Kalaman has for a cursed weapon",
                 "Sent them off with two healing potions and a map"],
        },
    ),
    dict(
        slug='governor-miat', name='Governor Miat', role='Governor of Kalaman',
        relation='Granting authority', affiliation='Kalaman government',
        met='kalaman', aff='kalaman', standing='Neutral', last=8, status='Active',
        overview="Governor Miat rules Kalaman and holds firm control of its council. The council granted the people of Vogler refuge on the condition that the party aid the city's military efforts.",
        links=['npc:marshal-vendri', 'npc:bakaris-the-elder', 'quest:refuge-for-vogler',
               'quest:service-to-kalaman', 'place:kalaman'],
        records={
            8: ["Asked whether the people of Vogler intended retaliation",
                "Warned that other villages had come under attack as well",
                "Granted refuge in exchange for the party's service",
                "Was overheard holding firm against Lord Bakaris's interruptions"],
        },
    ),
    dict(
        slug='mayor-raven', name='Mayor Raven Uth Vogler', role='Mayor of fallen Vogler',
        relation='Grateful leader of the refugees', affiliation='Vogler refugees',
        met='vogler', aff='vogler', standing='Ally', last=10, status='Active',
        overview="Raven Uth Vogler is the mayor of Vogler. She resisted abandoning the town, then told its people the truth about the Red Dragon Army's demand. She now leads the displaced Voglerans camped outside Kalaman, and has named the party honorary Voglerans.",
        links=['place:vogler', 'place:the-refugee-camp', 'quest:refuge-for-vogler',
               'quest:the-evacuation-of-vogler', 'npc:bakaris-the-elder'],
        records={
            4: ["Housed the party for the night at Becklin's request",
                "Led the festival parade to High Hill",
                "Came away from the battle shaken and set on seeing it answered"],
            5: ["Stepped in before Cudgel's interrogation became nothing but vengeance",
                "Judged that the gold pointed to a second camp and wanted the woods scouted",
                "Agreed with Mayriel to shore up the town",
                "Heard the scouts' report of the soldiers in the woods"],
            6: ["Resisted the thought of abandoning Vogler",
                "Received the Red Army's scroll at the gate and read it aloud",
                "Told the town the truth; Kakashi calmed the panic and set people to packing",
                "Sent townsfolk to help Than with his explosives"],
            8: ["Saw to the refugees at Kalaman and asked the party to speak for Vogler before the council"],
            9: ["Named the party honorary Voglerans",
                "Rolled her eyes at word of Lord Bakaris and said she would try to deal with it"],
            10: ["Said her goodnights, then kept an eye on the camp until the party took the watch",
                 "Told Aratos the camp has no scouts, since most of Vogler's able bodies were lost"],
        },
    ),
    dict(
        slug='cudgel-ironsmile', name='Cudgel Ironsmile', role='Mercenary captain',
        relation='Ally at Vogler', affiliation='Her own mercenary company',
        met='vogler', aff='vogler', standing='Ally', last=7, status='Unknown',
        overview="Cudgel Ironsmile is a mercenary captain whose company played the old foe in Vogler's festival battle. Part of that company sold her out to the Red Army. She fought for the town to the end and was last seen kicked through a building on the burning waterfront.",
        links=['npc:gragonis', 'npc:becklin-uth-viharin', 'npc:the-charred-swordswoman',
               'quest:the-betrayal-at-high-hill', 'quest:the-evacuation-of-vogler', 'place:vogler'],
        records={
            4: ["Lowered Ispin's boat into the river with Becklin",
                "Cut through her own traitors at High Hill, horrified",
                "Swore to get to the bottom of the betrayal"],
            5: ["Nearly lost herself to rage questioning the captured mercenary",
                "Learned that her lieutenant Gragonis took gold and turned part of her company",
                "Went back to her camp alone to see who remained loyal",
                "Had not returned by night's end"],
            6: ["Returned with her lieutenant Jeyev",
                "Laid out the choice: stay and fight, or evacuate",
                "Offered to send one of her men to Kalaman",
                "Climbed into the cliffside fight, was struck by lightning, and crushed one of the watchers",
                "Posted her mercenaries north of town to slow the Red Army"],
            7: ["Ordered Jeyev, with Becklin, to take Darrett and run",
                "Fought beside Becklin on the waterfront",
                "Was kicked aside and went through a building"],
        },
    ),
    dict(
        slug='than', name="Than Rookledust", role='Gnome tinkerer of Thornwall Keep',
        relation='Helpful eccentric', affiliation='Thornwall Keep, Vogler',
        met='vogler', aff='vogler', standing='Ally', last=7, status='Left Vogler by boat with the party',
        aliases=['Than'],
        overview="Than is a frantic gnome tinkerer who kept a workshop at Thornwall Keep. He is scattered and hard to keep on one subject, and useful anyway. He readied the party's boat as Vogler burned and left aboard it with them. Nothing has been said of him since.",
        links=['place:thornwall-keep', 'quest:the-evacuation-of-vogler', 'pc:roshi'],
        records={
            4: ["Named by Becklin as her lodger at Thornwall Keep, more a tinkerer than a spellcaster"],
            6: ["Was found by Roshi at Thornwall Keep and welcomed her as a friend of Becklin",
                "Admitted to unstable explosives that could be set as traps",
                "Offered to help repair boats and rig a signal",
                "Warned Roshi to leave the gnome-flinger on the roof alone"],
            7: ["Was helped by four of the party to clear draconians from Thornwall Keep, and stayed behind to gather two more things",
                "Launched himself from the keep's roof with the gnome-flinger and landed on his feet at the docks",
                "From the air saw smaller winged shapes in the smoke and a rider on the dragon's back",
                "Shot a red draconian, which exploded as it died",
                "Revived Kakashi and Roshi with potions",
                "Readied the boat and left Vogler aboard it with the party"],
        },
    ),
    dict(
        slug='gragonis', name='Gragonis', role="Cudgel's lieutenant; half-ogre",
        relation='Traitor; killed by the party at High Hill', affiliation="Cudgel's company",
        met='vogler', aff='red-dragon-army', standing='Adversary', last=5, status='Dead',
        named_only=False,
        overview="Gragonis was Cudgel Ironsmile's lieutenant. A captured mercenary said he went out to the woods a few days before the festival battle and came back with gold, and that some of her company had been paid to turn on Vogler. He was the huge half-ogre the party killed on High Hill. They learned his name afterward, from the prisoner.",
        links=['npc:cudgel-ironsmile', 'quest:the-betrayal-at-high-hill', 'fac:the-red-dragon-army'],
        records={
            5: ["Named by the captured mercenary as the one who went to the woods and came back with gold",
                "Revealed as the half-ogre the party had killed on High Hill",
                "Had recruited mercenaries to betray Cudgel, kill the militia and take Vogler"],
        },
    ),
    dict(
        slug='bakaris-the-elder', name='Bakaris the Elder', role='Lord; nobleman',
        relation='Distrusted noble', affiliation='Nobility',
        met='vogler', aff='unaffiliated', standing='Neutral', last=8, status='Active',
        overview="Lord Bakaris is a nobleman who dresses in red and gold and takes offense when plans are made without him. He prefers a sealed letter to a ride into danger. He reached Kalaman's council ahead of the refugees.",
        links=['npc:bakaris-the-younger', 'quest:the-bakarises', 'npc:governor-miat', 'place:kalaman'],
        records={
            4: ["Named by Becklin as the last arrival from Kalaman, with his son",
                "Stood among the spectators at High Hill, where his son said he would judge the mock battle"],
            6: ["Forced his way into the planning, offended that anyone had made plans without him",
                "Preferred sending a letter under his seal to riding for help",
                "Went to ready his own things",
                "Pressed Mayor Raven at her ear to make a decision while the crowd panicked"],
            8: ["Suggested on the river that more might have been done to save the village",
                "Entered Kalaman ahead of the refugees and brought the council the news first",
                "Tried to twist the hearing until Aratos silenced him"],
        },
    ),
    dict(
        slug='bakaris-the-younger', name='Bakaris the Younger', role='Young nobleman',
        relation='Disliked noble', affiliation='Nobility',
        met='vogler', aff='unaffiliated', standing='Neutral', last=8, status='Active',
        overview="Bakaris the Younger is a blond young nobleman, son of Lord Bakaris, with more arrogance than grace and very little real authority.",
        links=['npc:bakaris-the-elder', 'quest:the-bakarises'],
        records={
            4: ["Heckled the stories of Ispin at the Brass Crab until Becklin sent him off",
                "Told Aratos and Kakashi that his family came from Kalaman and that his father would judge the mock battle"],
            8: ["Echoed his father on the river: more might have been done",
                "Stood in the party's way outside the council and called the refugees fishfolk"],
        },
    ),
    dict(
        slug='wyhan', name='Wyhan', role="Apothecary; examiner for High Sorcery",
        relation='Sharp, transactional contact', affiliation="Kalaman apothecary; High Sorcery",
        met='kalaman', aff='high-sorcery', standing='Neutral', last=11, status='Active',
        overview="Wyhan keeps an apothecary in Kalaman. She read the High Sorcery scrolls Kakashi and Jasper carried and set both to test for the White Robes. Seredyn names her as the best lead to the Tower of Wayreth. She has sent Kakashi a list of things to gather, frostlace above all.",
        links=['quest:the-white-robes', 'quest:the-orb-of-dragonkind', 'quest:fizbans-recipe',
               'fac:the-mages-of-high-sorcery', 'place:kalaman', 'place:tower-of-wayreth', 'quest:wyhans-list'],
        records={
            2: ["Named by Fizban on the road as the one to see in Kalaman: rough around the edges, very powerful, best met with courtesy"],
            8: ["Examined the High Sorcery scrolls Kakashi and Jasper carried",
                "Determined both would test for the White Robes, with a practical exam weeks out",
                "Dismissed them with little ceremony"],
            10: ["Turned Kakashi away at night and told him to come back in the morning with gold",
                 "Sold Kakashi components to restore his familiar",
                 "Named a price for spell scrolls well beyond what he carried, and told him to find a job",
                 "Hearing only the numbers from Fizban's recipe, judged that they decipher part of it into an incantation",
                 "Sold Mayriel two healer's kits",
                 "Allowed that she could use a hand or two around the shop",
                 "Was named by Seredyn as Jasper's best lead to the tower"],
            11: ["Sent a list after Kakashi on the road: willowbark, pine resin, graveyard moss, and frostlace"],
        },
    ),
    dict(
        slug='sergeant-boyd', name='Sergeant Boyd', role='Retired soldier holding Bracken Hollow together',
        relation='Rescuer and host', affiliation='Bracken Hollow',
        met='bracken-hollow', aff='bracken-hollow', standing='Ally', last=11, status='Active',
        aliases=['Boyd'],
        overview="Sergeant Boyd is retired from the army and has made Bracken Hollow his home. Since the village closed he has kept its people fed and indoors at the right hours. He pulled Kakashi off a fresh grave, sheltered the party from the wolves, and told them how the moons turn. He says no one should have to choose who is sent up the hill.",
        links=['place:bracken-hollow', 'quest:the-spell-over-bracken-hollow', 'quest:the-ones-sent-up-the-hill',
               'npc:corvin', 'npc:ked', 'pc:kakashi', 'quest:wyhans-list'],
        records={
            11: ["Hauled Kakashi off a fresh grave: you need to go. Quickly",
                 "Loosed two arrows at the wolves in the dark and missed with both",
                 "Brought the party indoors and explained the white, red and black moons and the eclipse",
                 "Said a few travelers were shut in along with the villagers",
                 "Said the monument stays on its hill and does not come into the village",
                 "Said no one had been sent up the hill, until Corvin called that less than the full truth",
                 "Told the party he would not ask them to fight the town's battles, and would not stop them",
                 "Left to carry food to the other houses and was not there when the party took Ked up the hill"],
        },
    ),
    dict(
        slug='corvin', name='Corvin', role='Villager of Bracken Hollow',
        relation='Went up the hill with the party', affiliation='Bracken Hollow',
        met='bracken-hollow', aff='bracken-hollow', standing='Unknown', last=11, status='Fled the hill',
        overview="Corvin is a broad-shouldered man in his forties with a rough beard, one of those who go out under the black moon for food. He told the party what Boyd would not: that another of the black-touched can be sent up the hill in place of the one the eclipse chooses. He believes the village must make the best of that. On the hill he kept Ked from leaving at the point of a dagger.",
        links=['place:bracken-hollow', 'npc:sergeant-boyd', 'npc:ked', 'quest:the-ones-sent-up-the-hill',
               'quest:the-spell-over-bracken-hollow', 'pc:jasper'],
        records={
            11: ["Interrupted Boyd: that's not the full truth, now is it",
                 "Said that some skills are still needed to keep the town together",
                 "Kept watching Ked, and tensed when Jasper asked him about it",
                 "Said people needed to eat, and Boyd left with food for the other houses",
                 "Talked Ked into going up the hill",
                 "Stood at Ked's back with a dagger when he tried to leave: you stay. You see this through",
                 "Knocked Ked senseless, and ran when the monument fought harder than he had ever seen it fight"],
        },
    ),
    dict(
        slug='ked', name='Ked', role='Villager of Bracken Hollow, black-touched',
        relation="Under the party's protection", affiliation='Bracken Hollow',
        met='bracken-hollow', aff='bracken-hollow', standing='Neutral', last=11, status='Unconscious on the hill',
        overview="Ked is a villager of Bracken Hollow, a human in his twenties or thirties. He was the one person in Boyd's shelter whose glow carried the black as well as the white and red, which makes him one of the handful the eclipse chooses from. Aratos gave him his word that the Embers would protect him.",
        links=['place:bracken-hollow', 'npc:corvin', 'npc:sergeant-boyd', 'pc:aratos',
               'quest:the-ones-sent-up-the-hill', 'quest:the-spell-over-bracken-hollow'],
        records={
            11: ["Curled up when Aratos pointed an axe at him: I don't want any trouble",
                 "Stood and came along after Aratos promised to protect him with their lives",
                 "Glowed brighter as the party climbed the hill and the eclipse began",
                 "Tried to leave, struck Corvin, and was knocked senseless",
                 "Still lying on the hill, with the eclipse not yet over"],
        },
    ),
    dict(
        slug='roberto', name='Roberto', role='Squire at Kalaman',
        relation='Sparring partner, injured', affiliation='Kalaman garrison',
        met='kalaman', aff='kalaman', standing='Neutral', last=10, status='Recovering',
        overview="Roberto is a squire in Kalaman's garrison. He walked the courtyard statues with Aratos, and was later cut down by the Emberwake in a sparring match.",
        links=['pc:aratos', 'item:the-emberwake-greataxe', 'quest:the-emberwakes-curse', 'npc:marshal-vendri'],
        records={
            8: ["Walked the courtyard statues with Aratos, Lord Soth's among them",
                "Pointed him to Marshal Vendri for questions about such things"],
            10: ["Agreed to a bout of three hits with Aratos; took two, then landed one",
                 "Was cut down by the Emberwake and left unconscious",
                 "Reported by Vendri later that morning as stabilized and a little shaken"],
        },
    ),
    dict(
        slug='seredyn', name='Seredyn', role="Head of the Dragon's Eye in Kalaman",
        relation="Local guild head, wary", affiliation="Dragon's Eye, Kalaman branch",
        met='kalaman', aff='dragons-eye', standing='Neutral', last=10, status='Active',
        overview="Seredyn heads the Dragon's Eye branch in Kalaman from a table at the back of Finn's Bar. He dresses richly, wears gold earrings, and walks the city behind a faint illusion. Lucky had not told him Jasper was coming.",
        links=['npc:lucky', 'npc:finbar', 'pc:jasper', 'quest:the-orb-of-dragonkind',
               'fac:the-dragons-eye', 'place:kalaman'],
        records={
            8: ["Left the council chamber shimmering faintly with illusion; he and Jasper acknowledged each other without a word"],
            10: ["Saw through Jasper's attempt at misdirection",
                 "Heard the truth of the Orb task and judged that Lucky must be furious with Jasper to set it",
                 "Twitched at one eye when Lucky was named",
                 "Said he answers only to Lucky, and that Jasper answers to him while in Kalaman",
                 "Does not know where the tower is; named Wyhan as the best lead to it",
                 "Warned that getting into the tower might prove easier than getting out",
                 "Told Jasper to keep his visit short, cause no trouble, and let nothing come back to him"],
        },
    ),
    dict(
        slug='finbar', name='Finbar', role="Dragon's Eye contact",
        relation='Guild contact, once "Old Man Jenkins"', affiliation="Dragon's Eye",
        met='vogler', aff='dragons-eye', standing='Neutral', last=10, status='Active',
        aliases=['Old Man Jenkins', 'Jenkins'],
        overview="Finbar is a kender of the Dragon's Eye who can pass unseen. In Vogler he wore the face of Old Man Jenkins and kept General Goods. Jasper's coin showed him the figure inside the disguise, and before Vogler fell he had the name as well. The rest of the party still knows him only as Jenkins. In Kalaman he walked Jasper to the guild behind a different human face, and showed his own only inside its door.",
        links=['npc:seredyn', 'npc:lucky', 'pc:jasper', 'item:winged-boots', 'item:leeching-arrows',
               'quest:finbar', 'quest:the-orb-of-dragonkind', 'fac:the-dragons-eye'],
        records={
            2: ["A hunched old man with a shimmer about him gave Jasper a knowing look in Vogler's market square"],
            3: ["An older figure with a shimmer passed Jasper on the way to Thornwall Keep; Jasper walked on and told no one"],
            4: ["A note in Thieves' Cant brought Jasper to General Goods alone",
                "As Old Man Jenkins, put a blade to Jasper's throat and gave half a passphrase; he had feared Lucky sent Jasper to kill him",
                "Taught Jasper the phrase and warned him about Lucky and the coin",
                "Called the tower job a death sentence, and said there were others like them in Kalaman",
                "Sold Jasper a pair of winged boots"],
            5: ["Was found packing to flee Vogler, and called Jasper a fool for staying",
                "Called Jasper a fellow Dragon's Eye and asked him to tell no one",
                "Gave Jasper two healing potions and leeching arrows",
                "Told him to remember that old Finbar always takes care of him"],
            6: ["As Old Man Jenkins, left his shop locked and unanswered on the morning of the ultimatum"],
            7: ["Seen only by Jasper, looked at him, looked at the boat and made for it",
                "The whole party heard a voice from nowhere: glad to see you're not dead yet",
                "Came aboard the party's boat unseen by the others"],
            10: ["Stood unseen outside the camp until Jasper spotted him",
                 "Dropped his invisibility and wore a human face that was not Jenkins's",
                 "Led Jasper into Peller's Provisions, knocked three times at the back door, and gave the passphrase",
                 "Showed his kender face inside the guild's door",
                 "Was told to see Jasper out, and stood him a drink"],
        },
    ),
    dict(
        slug='lucky', name='Lucky Leppomanto', role="Guild master of the Dragon's Eye",
        relation="Set Jasper his task", affiliation="Dragon's Eye",
        met='visions', aff='dragons-eye', standing='Unknown', last=8, status='Active',
        aliases=['Lucky'],
        overview="Lucky Leppomanto is the guild master of the Dragon's Eye. Lucky set Jasper his task: steal the Orb of Dragonkind from the Tower of Wayreth. Jasper has seen Lucky only in a dream and in the river's apparitions.",
        links=['pc:jasper', 'npc:seredyn', 'npc:finbar', 'item:dragons-eye-coin',
               'quest:the-orb-of-dragonkind', 'fac:the-dragons-eye'],
        records={
            2: ["Appeared in Jasper's dream of the guild, the coin and the task"],
            8: ["Appeared to Jasper in the river and warned that time was running out"],
            10: ["Had told Seredyn nothing of Jasper's presence or task in Kalaman",
                 "Said by Seredyn to recruit rarely, and never so freely as he recruited Jasper"],
        },
    ),
    dict(
        slug='theros-flametongue', name='Theros Flametongue', role='Orcish warrior with a flaming axe',
        relation='Defeated adversary, returned', affiliation='Red Dragon Army',
        met='vogler', aff='red-dragon-army', standing='Adversary', last=7, status='Slain, then risen',
        portrait=IMG + '11vuG_FppfLpj1OMBTRuGTnc5hTGlMpqS',
        overview="Theros Flametongue is a green-skinned orcish warrior who rode into Vogler on the dragon machine carrying a flaming axe. Mayriel killed him on the docks. As the boats pulled away, a figure stood over his body, flame passed across him, and he rose.",
        links=['item:the-emberwake-greataxe', 'pc:aratos', 'pc:mayriel', 'quest:theros-flametongue',
               'fac:the-red-dragon-army', 'place:vogler'],
        records={
            7: ["Jumped down from the dragon machine and mocked the heroes he had heard of on the front lines",
                "Took Aratos's first blow, then gave his name as a courtesy to the one he meant to kill",
                "Tore the axe from Aratos's hands and knocked Mayriel flat",
                "Was caught in the machine's fire and buckled for a moment",
                "Was driven to one knee by Mayriel, said he would not die to nothings, and was killed by her spiritual sword",
                "Lost his axe to Aratos",
                "A figure stood over his body; flame passed across him and he rose"],
        },
    ),
    dict(
        slug='the-charred-swordswoman', name='The Charred Swordswoman', role='Unidentified warrior',
        relation='Unidentified adversary', affiliation='Red Dragon Army',
        met='vogler', aff='red-dragon-army', standing='Adversary', last=7, status='Unknown',
        overview="A tall woman with charred skin, blackened armor and a massive sword, seen through the smoke at Vogler's waterfront. She called after the party's boat that they would not escape the flames of the Dragon Queen. The party does not know her name.",
        links=['npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'fac:the-red-dragon-army', 'place:vogler'],
        records={
            7: ["Fought Becklin and Cudgel on the waterfront as the party's boat left",
                "Kicked Cudgel Ironsmile aside through a building",
                "Stood at the edge of the dock after Becklin fell, joined by two more figures",
                "Called after the boat: run as far as you can, you will not escape the flames of the Dragon Queen"],
        },
    ),
    dict(
        slug='lord-soth', name='Lord Soth', role='Fallen Knight of Solamnia',
        relation='Looming antagonist', affiliation='Knights of Solamnia (fallen)',
        met='visions', aff='knights', standing='Adversary', last=9, status='At large',
        overview="Lord Soth was once a celebrated Knight of Solamnia. He fell through selfishness and personal failure and lives in disgrace under a curse. Aratos has seen him in the river's apparitions, and the party has fought one of his servants, a necromancer corrupting a tomb of knights. The pale woman told Aeimos alone that Soth wishes to corrupt all knights and their legacies, in vengeance for how they portrayed him, until his curse is lifted.",
        links=['quest:lord-soths-corruption', 'quest:the-leviathan-axe', 'pc:aratos', 'pc:aeimos',
               'npc:sir-cthondor', 'npc:the-pale-woman', 'fac:the-knights-of-solamnia',
               'place:the-reliquary-of-sir-cthondor'],
        records={
            8: ["Appeared to Aratos in the river opposite Cathan Twice-Born; the two told him he would have to choose soon",
                "His statue stands in Kalaman's courtyard among knights once honored"],
            9: ["A necromancer died in his service while corrupting the tomb of Sir Cthondor: his will is done, Lord Soth",
                "Said by the pale woman, to Aeimos alone, to wish the corruption of all knights, their image and their legacies, in vengeance for how they portrayed him"],
        },
    ),
    dict(
        slug='sir-cthondor', name='Sir Cthondor', role="Knight of the hidden reliquary, at rest",
        relation='Freed spirit', affiliation="The reliquary of the Knights Radiant",
        met='kalaman', aff='knights', standing='Ally', last=10, status='At rest',
        overview="Sir Cthondor was a knight whose tomb lies in a hidden reliquary of the Knights Radiant outside Kalaman. A necromancer serving Lord Soth raised his spirit as a wraith. Freed, he named Aratos and Aeimos children of Cathan and sounded his horn to send the risen dead back to rest.",
        links=['place:the-reliquary-of-sir-cthondor', 'item:horn-of-sir-cthondor', 'npc:lord-soth',
               'pc:aratos', 'pc:aeimos', 'fac:the-knights-radiant', 'quest:meat-for-ispins-stew'],
        records={
            9: ["Stood at the center of the tomb, horn in the crook of his arm",
                "Rose as a wraith in violet shadow when the necromancer's ritual went far enough",
                "Was freed by Mayriel's spiritual weapon",
                "Named Aratos and Aeimos children of Cathan and told them they had proven themselves",
                "Blew his horn and returned the three risen knights to rest"],
            10: ["Aratos stood before his statue and asked for help overcoming the axe's curse"],
        },
    ),
    dict(
        slug='the-pale-woman', name='The Pale Woman', role='Unidentified figure',
        relation='Mysterious guide to Aeimos', affiliation='Unknown',
        met='kalaman', aff='unaffiliated', standing='Unknown', last=9, status='Active',
        overview="A pale, beautiful woman with pointed ears and long flowing hair who appears to Aeimos, points, and vanishes. He could not tell what she was. She has whispered to him twice and spoken to him once. No one else has seen or heard her, and Aeimos has told no one.",
        links=['pc:aeimos', 'npc:lord-soth', 'quest:lord-soths-corruption'],
        records={
            9: ["Appeared behind Mayriel during the hunt, seen only by Aeimos, and pointed toward the others",
                "Whispered to Aeimos in the reliquary to go forward, and outside it that there are more and he wishes to take them",
                "Told Aeimos, alone beyond the camp, that Lord Soth wishes to corrupt all knights in vengeance for how they portrayed him, until his curse is lifted",
                "Pointed into the distance when he asked where to go"],
        },
    ),
    dict(
        slug='sunscale', name='Sunscale', role='Golden canary',
        relation="Mayriel's companion", affiliation='Unknown',
        met='the-road', aff='unaffiliated', standing='Ally', last=8, status='Active',
        overview="Sunscale is a golden canary that first landed on Mayriel's shoulder on the road to Vogler. It had kept company with Fizban; given the choice in Kalaman, it stayed with her.",
        links=['pc:mayriel', 'npc:fizban', 'item:divine-pendant'],
        records={
            2: ["A golden canary landed on Mayriel's shoulder during a night watch on the road, then flew away"],
            4: ["Mayriel woke to a golden canary and a pendant",
                "A voice spoke through the bird to Mayriel alone"],
            7: ["The golden canary flew into view as Mayriel pledged her ring; it grew larger as its light spread and healed the party"],
            8: ["Returned to Fizban, then made its choice and stayed with Mayriel"],
        },
    ),
    dict(
        slug='ispin-greenshield', name='Ispin Greenshield', role='Late adventurer, friend to many',
        relation='Honored dead', affiliation='None',
        met='vogler', aff='unaffiliated', standing='Ally', last=8, status='Dead',
        overview="Ispin Greenshield was an old human adventurer, remembered fondly by elves and townsfolk alike. His funeral in Vogler drew Roshi and Mayriel onto the road. He asked that it be an evening of stories.",
        links=['item:ispins-green-shield', 'pc:roshi', 'npc:becklin-uth-viharin', 'npc:fizban',
               'place:vogler', 'item:fizbans-stew-recipe'],
        records={
            1: ["Letters of his death drew Roshi and Mayriel toward Vogler"],
            2: ["Roshi thought of him on her watch: an adventurer she had traveled with and visited in Vogler every few years",
                "Fizban named him an old friend"],
            3: ["Remembered across Vogler in tales of goblins, an owlbear, a leap from the tallest mountain and a jump into a volcano"],
            4: ["Was sent down the Vingaard in a shrouded boat at sunset",
                "Was remembered at the Brass Crab: the volcano ridden on a shield, the bear den and the honey, the wyrmling",
                "Had left his green shield to Fizban, who declined it; it passed to Roshi"],
            8: ["Appeared to Roshi in the river, asking whether she had truly protected the villagers"],
            9: ["Fizban cooked what he said was Ispin's stew recipe, and it fed the refugee camp for a night"],
        },
    ),
    dict(
        slug='jeyev', name='Jeyev', role="Cudgel's lieutenant",
        relation='Ally at Vogler', affiliation="Cudgel's company",
        met='vogler', aff='vogler', standing='Ally', last=7, status='Unknown',
        overview="Jeyev is Cudgel Ironsmile's loyal lieutenant, a shaved-headed man in plate armor and blue-gray robes. He rode out past the Red Army's messenger to gather her loyal mercenaries. On the night Vogler burned he carried Darrett out of the smoke, on Becklin's and Cudgel's orders.",
        links=['npc:cudgel-ironsmile', 'npc:darrett-highwater', 'npc:becklin-uth-viharin', 'place:vogler'],
        records={
            6: ["Arrived with Cudgel and was introduced as her lieutenant",
                "Turned the messenger's sword aside when the rider cut him off, and traded blows with him",
                "Rode out to warn and gather Cudgel's loyal mercenaries"],
            7: ["Carried Darrett out of the smoke to the docks",
                "Told Jasper that Becklin and Cudgel were still fighting and had ordered him to take Darrett and run"],
        },
    ),
    dict(
        slug='cathan-twice-born', name='Cathan Twice-Born', role='Ancestor of Aratos and Aeimos',
        relation="Aratos's ancestor", affiliation='The line of Aratos and Aeimos',
        met='visions', aff='knights', standing='Unknown', last=10, status='Long dead',
        aliases=['Cathan'],
        overview="Cathan Twice-Born is an ancestor of Aratos and Aeimos. His failure, long ago, brought about ruin, and Aratos knows it as the history of his family. Aratos saw him in the Vingaard, standing opposite Lord Soth, and was told he would have to choose soon. The spirit of Sir Cthondor named the cousins children of Cathan.",
        links=['pc:aratos', 'pc:aeimos', 'npc:lord-soth', 'npc:sir-cthondor', 'quest:the-leviathan-axe',
               'fac:the-knights-radiant'],
        records={
            8: ["Stood in the river opposite Lord Soth; the two told Aratos he would have to choose soon"],
            9: ["Named by Sir Cthondor's spirit as the forebear of Aratos and Aeimos"],
            10: ["Came to Aratos's mind at the campfire after the King's warning, as the ancestor whose failure brought ruin"],
        },
    ),
]

# Named, but with nothing behind the name worth a page. One line each.
UNFILED = [
    ('Tatina Rookledust', "A tinkerer several days' travel from Kalaman. Marshal Vendri believes she can explain the mechanical dragon. Not yet met."),
    ('The Elder Warrior', "A stern, ancient figure at the foot of the tree of fire and frost in Journey 005, who told Aratos to choose. Aratos has heard his rough old voice since, on the cliff in Journey 006 and at the docks in 007: prove, good, are you worthy?"),
    ('The King', "A hooded, kingly figure among the ancestral spirits who appear when Aratos rages. Came to him three times in Journey 010 with warnings: the same blood flows through my veins. The same weakness."),
    ('Gribb Brack', "A farmer in Bracken Hollow, a few houses down from Boyd's shelter. Boyd says he would know about frostlace. Not yet met."),
    ('Marigold', "A healer and something of a mystic. Her cottage stands just outside Bracken Hollow, and she travels between villages tending the sick. She was away on the night the village closed."),
    ('Nora', "A villager of Bracken Hollow who is unwell. Corvin named her in Journey 011, when he said people needed to eat."),
    ('Gertrude', "Smith in Vogler. Aratos met Becklin at her smithy in Journey 003."),
]
