"""
campaign_people.py - the Embers and everyone they have met.

Player-known framing only. Sources: the Unexpected Journey accounts 001-010
and the campaign tracker (Player Characters, NPCs). Nothing here should say
more than a player at the table could.

References to other records use "kind:slug":
    pc:   the-embers/      npc:  dossiers/      item:  armory/
    place: atlas/          fac:  war-intel/     quest: quests/

`records` maps a journey number to what that journey added. The highest
number shows open on the page; the rest fold under "Previous Journeys".
"""

IMG = 'https://lh3.googleusercontent.com/d/'

# ---------------------------------------------------------------------------
# THE EMBERS
# ---------------------------------------------------------------------------

PCS = [
    dict(
        slug='aratos', name='Aratos Stormblessed', short='Aratos',
        race='Human', klass='Barbarian', portrait=IMG + '1FocmkAQsG7XDRJPrGZMtQerhkHxSvYNV',
        sub="Barbarian of the Ancestral Guardians; a Knight Radiant of Cathan's line",
        affiliation='Knights Radiant; the Embers', first=1, last=10, status='Active',
        overview=[
            "Aratos carries the mark of something larger than himself: a vision that came to him like a summons, showing him a world conquered by dragons and their armies. He woke from that dream with thunder in his veins and a purpose carved into his bones: to reach Kalaman, to find the Knights of Solamnia, and to fight.",
            "He is driven by that vision, and by a bond of blood with Aeimos, his cousin. Aratos leads not always by choice, but by the weight of what he carries. He has faced the fears of a fallen town, carried refugees to safety, and stood against the Shadow Queen's servants. The storm in him grows stronger with each battle.",
        ],
        pursuit="Mastering the cursed trophy axe, and choosing between his ancestors' two legacies: fire and fury, or ice and restraint.",
        state="Briefly mastered the axe at the reliquary through restraint and glimpsed its true form. Still cannot give the axe away.",
        line="Chose the cold side of the tree at the reliquary and held the Emberwake, for a moment, on his own terms.",
        links=['item:the-emberwake-greataxe', 'item:horn-of-sir-cthondor', 'quest:the-emberwakes-curse',
               'quest:fire-and-frost', 'quest:the-first-mission', 'pc:aeimos', 'npc:theros-flametongue',
               'fac:the-knights-radiant'],
        records={
            1: ["Woke from a dream of scaled warriors marching in ranks, with one command in it: fight",
                "Recognized the ambushers on the road from that dream and charged"],
            2: ["Brought lightning against the creature of living sand"],
            3: ["Told Becklin of his vision at Gertrude's smithy and asked her help warning the knights",
                "Reunited with his cousin Aeimos, who stole his ring before saying hello",
                "Drove lightning through the beast beneath Crustdurn Isle"],
            4: ["Shared his vision with Becklin, who promised a letter for Kalaman",
                "Stayed at Darrett's side when the mock battle at High Hill turned real"],
            5: ["Saw a colossal tree split between flame and frost, and a stern figure who told him to choose: blades of fury, or an axe of cold restraint",
                "Scouted the woods and saw the shape of the Red Army camp"],
            6: ["Tried to bluff a cliffside watcher and ended up with a blade at his throat",
                "Felt his axe run cold while a voice demanded he prove himself",
                "Killed the Red Army's messenger with a javelin through the heart",
                "Was asked by Becklin to bring a chest from Thornwall Keep to Darrett if she did not return"],
            7: ["Dueled Theros Flametongue on the burning docks with his ancestors gathered around him",
                "Brought down the dragon machine with a javelin and a bolt of lightning",
                "Took Theros's still-warm axe as a trophy"],
            8: ["Took up the Emberwake Greataxe on the river",
                "Saw Cathan Twice-Born and Lord Soth in the water, and was told he would have to choose soon",
                "Silenced Lord Bakaris in the council chamber",
                "Named himself a Knight Radiant; Marshal Vendri acknowledged the title"],
            9: ["Spoke his oath at the reliquary door and lit the word Valor",
                "Was named a child of Cathan by the spirit of Sir Cthondor",
                "Was left the horn by Aeimos"],
            10: ["Saw the tree of fire and frost in the campfire, and the King, who warned that the same weakness runs in his blood",
                 "Lost himself to the axe in a sparring match and cut down the squire Roberto, who survived",
                 "Found he cannot hand the axe away or set it down",
                 "Knelt at the reliquary and chose the cold side of the tree; the flames died and the axe briefly took another shape"],
        },
    ),
    dict(
        slug='kakashi', name='Kakashi', short='Kakashi',
        race='Human', klass='Wizard', portrait=IMG + '1USG7Cr8dArWVq8HCEe99o3IQMOBCD26K',
        sub='Wizard in training, testing for the White Robes of High Sorcery',
        affiliation='High Sorcery (White Robes candidate); the Embers', first=1, last=10, status='Active',
        overview=[
            "A scholar and student of magic, Kakashi is driven by curiosity and a need to understand the world around him, especially the nature of magic itself. He carries a familiar, a clever raven, and questions that most mages dare not ask.",
            "He joined The Embers not seeking adventure, but because the road they walked demanded his skills. He has studied ancient magic, faced the impossible, and proven that wit and knowledge are weapons as sharp as any blade. Kakashi sees the world through the lens of understanding, and he is determined to survive long enough to learn its deepest secrets.",
        ],
        pursuit="Growing his power and earning his White Robes, while puzzling over a vision of a tower.",
        state="Awaiting a practical White Robes exam set by Wyhan. Carrying a strange vision.",
        line="Read Fizban's recipe as a cipher, and saw an elven woman in a pail of water who told him to keep them safe.",
        links=['item:boilerdrake-heart', 'item:moon-marked-spellbook', 'quest:the-white-robes',
               'quest:kakashis-tower-vision', 'quest:kakashis-buried-past', 'npc:wyhan',
               'fac:the-mages-of-high-sorcery'],
        records={
            1: ["Saw through the false key in the mage trial and passed alongside Jasper",
                "Earned a moon-marked spellbook"],
            2: ["Saw the moons align on his watch and heard voices say he was not strong enough, not yet"],
            3: ["Sent his raven to scout the shack on Crustdurn Isle",
                "Opened the fight below with a burst of ice"],
            4: ["Spoke for Ispin at the Brass Crab and quieted the room",
                "Was left a spell by Fizban as a parting gift"],
            5: ["Sent his raven to follow Cudgel at a distance"],
            6: ["Stilled a panicking crowd with a flash of power, then with gentleness",
                "Loosed a lightning strike that sounded like a thousand birds"],
            7: ["Finished the last operator inside the wreck and was dropped by the blast",
                "Remembered a village burning, and a past he had tried to bury",
                "Pulled the Boilerdrake Heart from the wreckage"],
            8: ["Attuned to the Boilerdrake Heart",
                "Presented his High Sorcery scroll to Wyhan; he will test for the White Robes"],
            9: ["Understood that the reliquary door was testing the virtues of knighthood",
                "Pushed the Boilerdrake Heart past its limits against the wraith"],
            10: ["Recognized Fizban's recipe as a cipher",
                 "Saw an elven woman in a pail of water, warding a round room of relics, who told him: you have to fight, keep them safe",
                 "Had Wyhan confirm the cipher and name the spell",
                 "Judged that breaking the hold of Aratos's axe would take divine magic"],
        },
    ),
    dict(
        slug='jasper', name='Jasper Quickwit', short='Jasper',
        race='Halfling', klass='Rogue', portrait=IMG + '1zX6MfbMgXijkdr9IOJLbGnWdMS3wtoR1',
        sub="Rogue bound to the Dragon's Eye thieves' guild",
        affiliation="Dragon's Eye; the Embers", first=1, last=10, status='Active',
        overview=[
            "Jasper hides sharp steel beneath quick wit and a mask of easy charm. A thief by trade, a trickster by nature, he joined The Embers for reasons he has never fully explained. What is clear is that he will not abandon them now, not when the world itself is at stake.",
            "His fingers move faster than most can see. His mind works in angles and distances others miss. He has saved his companions with cunning, carried them through impossible places, and proven that sometimes the smallest person in the room is the most dangerous. Jasper is a shadow that chooses to stand in the light.",
        ],
        pursuit="Repaying his debt to the guild by stealing the Orb of Dragonkind from the moving Tower of Wayreth.",
        state="Active and under pressure. The guild keeps reminding him that time is running short.",
        line="Met Seredyn at Finn's Bar and learned the tower is easier to enter than to leave.",
        links=['item:winged-boots', 'item:leeching-bolts', 'item:dragons-eye-coin',
               'quest:the-orb-of-dragonkind', 'quest:the-white-robes', 'quest:finbar',
               'npc:lucky', 'npc:seredyn', 'npc:finbar', 'fac:the-dragons-eye'],
        records={
            1: ["Passed the mage trial beside Kakashi by reading the runes for the word that opened the door",
                "Struck from hiding in the ambush on the road"],
            2: ["Dreamed of Lucky and the coin, and of the task: find the moving Tower of Wayreth and steal the Orb of Dragonkind",
                "Was caught and nearly swallowed by the living sand"],
            3: ["Vanished into the shadows of the cavern; his arrows found the killing angles on the beast"],
            4: ["Slipped out to General Goods to meet Old Man Jenkins, who knew the guild's phrase",
                "Bought winged boots with the party's shared gold and called it a slick deal",
                "Killed a traitor before he could cut Darrett down",
                "Shot the half-ogre through the head"],
            5: ["Crept alone to the edge of the Red Army camp and counted one to two hundred soldiers",
                "Used the Dragon's Eye coin to pass as a guard when a patrol came too close",
                "Told Jenkins the town was good and its people needed help, and was given healing potions and leeching bolts"],
            6: ["Used one of the leeching bolts on the cliffside"],
            7: ["Rose over the docks on the winged boots and saw that the dragon was a machine with a crew inside"],
            8: ["Saw Lucky in the river, warning that time was running out",
                "Overheard the council's private deliberation",
                "Caught a shimmer of illusion on one figure leaving the council chamber and knew the Dragon's Eye had reached Kalaman",
                "Presented his High Sorcery scroll to Wyhan; he will test for the White Robes"],
            9: ["Broke the necromancer's concentration with a shot from the shadows",
                "Found a note in Thieves' Cant marked with the Dragon's Eye: We need to talk"],
            10: ["Followed Finbar, no longer wearing Old Man Jenkins's face, into Kalaman by night",
                 "Met Seredyn, head of the Kalaman branch, at Finn's Bar",
                 "Was told Wyhan is his best lead to the tower, and that leaving it will be harder than entering",
                 "Told Roshi only that he had visited an old friend"],
        },
    ),
    dict(
        slug='roshi', name='Roshi', short='Roshi',
        race='Human', klass='Paladin of Kiri-Jolith', portrait=IMG + '1aY9zew4XAuhOWbXfOB2Vfm7FKDzfZonc',
        sub="Devoted protector carrying Ispin's legacy",
        affiliation='The Embers', first=1, last=10, status='Active',
        overview=[
            "Roshi walked the roads toward Vogler to attend a funeral and say goodbye to an old name: the name of an impossible hero. Instead, she found something larger: a calling, a purpose, and companions who would come to matter more than anything.",
            "She is a warrior devoted to the protection of those who cannot protect themselves. Humble in speech but fierce in action, Roshi has learned that honor is not a thing spoken of. It is something lived, moment by moment, choice by choice. She carries a shield that once belonged to a legend, and she has earned the right to bear it.",
        ],
        pursuit="Living up to Ispin's example as a shield for others, and growing into her sacred calling.",
        state="Steady. Her healing has been publicly recognized as divine.",
        line="Spoke the words hidden in Fizban's recipe and lit green flame in all five of them.",
        links=['item:ispins-green-shield', 'item:moon-touched-sword', 'npc:ispin-greenshield',
               'npc:becklin-uth-viharin', 'quest:the-emberwakes-curse'],
        records={
            1: ["Felt a sacred calling settle on her at an old holy place on the road",
                "Grappled one of the ambushers and demanded answers"],
            2: ["Gave the dead knights solemn care",
                "Was struck hard by the sand creature and nearly killed"],
            3: ["Ate crab ramen at the Brass Crab against all advice",
                "Was swallowed by the beast beneath Crustdurn Isle"],
            4: ["Told the story of Ispin and the bear den",
                "Received Ispin's Green Shield at Thornwall Keep",
                "Held against the half-ogre until her blade lit with divine fire"],
            5: ["Healed a fisherman by laying on hands, and was asked whether the gods had touched her"],
            6: ["Found Than at Thornwall Keep and asked for help delaying a massacre",
                "Drew the mounted messenger onto herself so Jeyev could ride"],
            7: ["Went down in the blast and was kept from death by the magic she carried",
                "Loosed a last arrow toward Becklin's attackers; it went wide"],
            8: ["Saw Ispin in the river asking whether she had protected the villagers, and answered that she had done what she could",
                "Offered Becklin's armor to Darrett"],
            9: ["Offered the door her truth and lit the word Foresight",
                "Turned the risen knights",
                "Ended the wraith with a spiritual weapon shaped like a rose"],
            10: ["Picked up the parchment Fizban dropped",
                 "Spoke the incantation that taught all five the Green Flame Blade",
                 "Sensed that Jasper was holding something back",
                 "Bought a healer's kit"],
        },
    ),
    dict(
        slug='mayriel', name='Mayriel', short='Mayriel',
        race='Elf', klass='Cleric of Paladine', portrait=IMG + '1VKa7NEkNHE6cGsNfNBckPyjOvvKLPrkM',
        sub='Cleric of Paladine; divine magic returned',
        affiliation='Faithful of Paladine; the Embers', first=1, last=10, status='Active',
        overview=[
            "Mayriel is a healer and warrior who hears the voice of Paladine in moments of darkness and divine clarity. She came to the roads seeking to understand what the gods were saying, and she found her answer in fire and purpose.",
            "She has stood between her companions and death. She has called down divine wrath upon those who would harm the innocent. And she has carried the weight of being the light in a world growing darker. Mayriel's faith is not blind. It is sharp, tested, and earned through sacrifice.",
        ],
        pursuit="Walking her divine calling, and waiting for the sword the Dragon Queen has promised will find her.",
        state="Has not had a vision in some time, which she finds suspicious.",
        line="Told Aratos the silence of her visions feels wrong, and that she does not know whether the promised sword is a blade or its bearer.",
        links=['item:mayriels-signet-ring', 'item:divine-pendant', 'npc:sunscale',
               'quest:the-sword-of-the-dragon-queen', 'quest:the-emberwakes-curse', 'npc:fizban'],
        records={
            1: ["Saw divine fire and draconic terror at an old holy place on the road",
                "Understood the ambushers when they named the Shadow Queen"],
            2: ["Kept Roshi alive after the sand creature struck",
                "Drew Fizban's interest: clerics had not walked openly in centuries"],
            3: ["Saw a horned woman in dark regalia unfold into a five-headed dragon, and platinum fire rise to shield her"],
            4: ["Shared her vision with Becklin",
                "Woke to a golden finch and a pendant"],
            5: ["Healed a woman hiding a fatal wound, and was asked whether the gods had touched her"],
            6: ["Called down moonlit radiance on the cliff",
                "Fell, and was brought back with a healing potion"],
            7: ["Raised a twilight glow over her companions at the docks",
                "Killed Theros Flametongue",
                "Offered Paladine her family signet ring and her obedience when he asks"],
            8: ["Saw the Dragon Queen in the river, who promised her sword would find her",
                "Kept Sunscale, who chose her over Fizban"],
            9: ["Saw purplish-black soot at the cave mouth and remembered the river",
                "Struck the necromancer with radiant rose-thorns"],
            10: ["Told Aratos she has had no vision in some time, and that the silence feels suspicious",
                 "Does not know whether the promised sword is a blade or the one who carries it",
                 "Bought a healer's kit"],
        },
    ),
    dict(
        slug='aeimos', name='Aeimos Stormblessed', short='Aeimos',
        race='Human', klass='Monk', portrait=IMG + '1Fv4WEzpgAcrSBF7rxjmVI8sc1bLz8DqV',
        sub='Stormblessed kin to Aratos; a recurring guest',
        affiliation='Knights Radiant; Stormblessed kin', first=3, last=9, status='Companion',
        overview=[
            "Aeimos is Aratos's cousin, carrying the same storm-marked blood and the same capacity for dangerous power. Where Aratos burns with vision and fury, Aeimos moves with discipline and precision. A martial artist trained in the way of the monks, he joined The Embers not out of summons, but out of kinship.",
            "He is quiet by nature, but his silence is the quiet of a storm gathering its strength. Aeimos has fought alongside his cousin, faced the same shadows, and proven that sometimes the greatest power comes not from anger, but from mastery over oneself.",
        ],
        pursuit="Hunting down and freeing the legacies of knights that Lord Soth is corrupting, on a road parallel to the party's.",
        state="Off on his own road against Soth's corruption. Appears and vanishes.",
        line="Left the horn with Aratos and went where the pale woman pointed.",
        links=['item:storm-charged-gauntlets', 'item:horn-of-sir-cthondor', 'pc:aratos',
               'npc:the-pale-elven-woman', 'npc:lord-soth', 'quest:lord-soths-corruption',
               'quest:fire-and-frost', 'fac:the-knights-radiant'],
        records={
            3: ["Stole Aratos's ring as a greeting",
                "Agreed to come toward Kalaman and the knights",
                "Leapt into the beast with storm-charged fists and cut out its tongue as a trophy"],
            4: ["Left Vogler at dawn with Fizban"],
            8: ["Named by Marshal Vendri as aiding other villages alongside Fizban"],
            9: ["Shadowed the hunt unseen until a pale elven woman pointed him toward the others",
                "Spoke his oath at the door and lit the word Resolve: hopelessness is not my privilege",
                "Was named a child of Cathan",
                "Blew the horn of Sir Cthondor and saw two spectral knights answer",
                "Left the horn with Aratos and slipped away",
                "Was told by the pale woman that Lord Soth seeks to corrupt all knights until his curse is lifted"],
        },
    ),
]

# ---------------------------------------------------------------------------
# DOSSIERS
# ---------------------------------------------------------------------------
# met:      vogler | kalaman | the-road | visions      (first facet: where met)
# aff:      slug used by the second facet, with AFF_LABELS below
# standing: Ally | Neutral | Adversary | Unknown       (never a spoiler)

AFF_LABELS = {
    'kalaman': 'Kalaman',
    'vogler': 'Vogler',
    'dragons-eye': "Dragon's Eye",
    'red-dragon-army': 'Red Dragon Army',
    'knights': 'Knightly Orders',
    'high-sorcery': 'High Sorcery',
    'unaffiliated': 'Unaffiliated',
}
MET_LABELS = {
    'vogler': 'Vogler',
    'kalaman': 'Kalaman',
    'the-road': 'The Road',
    'visions': 'Dreams and Visions',
}

NPCS = [
    dict(
        slug='becklin-uth-viharin', name='Becklin Uth Viharin', role='Retired Knight of Solamnia',
        relation='Fallen mentor', affiliation='Knights of Solamnia (retired)',
        met='vogler', aff='knights', standing='Ally', last=7, status='Fallen',
        portrait=IMG + '1SsOS6K-8vuYw1Sqk4V15MIk98GEnMgu8',
        overview="Becklin Uth Viharin was a retired Knight of Solamnia living in Vogler, an old friend of Ispin Greenshield and the town's steadiest hand. She believed the party's warnings, gave Roshi Ispin's shield, and held the docks so the boats could leave. She fell into the Vingaard with blades in her back.",
        links=['npc:darrett-highwater', 'npc:ispin-greenshield', 'npc:cudgel-ironsmile',
               'npc:the-charred-swordswoman', 'item:ispins-green-shield', 'item:becklins-armor',
               'fac:the-knights-of-solamnia', 'place:vogler', 'quest:the-evacuation-of-vogler'],
        records={
            3: ["Heard Aratos's vision at Gertrude's smithy and did not dismiss it",
                "Met the party's return from Crustdurn Isle with gratitude and surprise"],
            4: ["Spoke at Ispin's river funeral in her Solamnic armor",
                "Sent Bakaris the Younger out of the Brass Crab",
                "Promised a letter to help the party gain an audience in Kalaman",
                "Gave Roshi Ispin's Green Shield at Thornwall Keep",
                "Cut through the traitors at High Hill beside Cudgel"],
            5: ["Kept her composure after High Hill when Cudgel could not"],
            6: ["Agreed that escape had to be prepared",
                "Took the front line with Cudgel and gave the party the evacuation",
                "Asked Aratos to bring a chest from Thornwall Keep to Darrett if she did not return"],
            7: ["Held the waterfront against a charred woman in blackened armor",
                "Raised her hands toward the departing boat as if to say it was all right",
                "Was struck from behind and fell into the river"],
            8: ["Appeared to Darrett in the river among the Ashen Vigils",
                "Her armor passed to Darrett"],
        },
    ),
    dict(
        slug='fizban', name='Fizban', role='Green-robed wizard, old friend of Ispin',
        relation='Eccentric ally and guide', affiliation='Unknown; wandering',
        met='the-road', aff='unaffiliated', standing='Ally', last=10, status='Active',
        portrait=IMG + '1jIx_p6EnUosUiQHOc2K-kjU8E0u62t4W',
        overview="Fizban is a peculiar old wizard in green robes, found half-swallowed by a living sand creature on the road to Vogler. He comes and goes on his own business, takes a keen interest in Mayriel's divine magic, and is more insightful than he lets on.",
        links=['npc:ispin-greenshield', 'npc:sunscale', 'pc:mayriel', 'pc:aeimos',
               'item:fizbans-stew-recipe', 'quest:fizbans-recipe', 'quest:meat-for-ispins-stew'],
        records={
            2: ["Was found inside a creature of living sand, which he froze solid from within",
                "Introduced himself as an old friend of Ispin",
                "Told Mayriel that clerics had not walked openly in centuries"],
            3: ["Found Mayriel shaken after her vision at the docks and told her to listen"],
            4: ["Told the tale of a stolen pie and an offended prince",
                "Insisted Ispin's shield belonged with someone still willing to stand in front of danger",
                "Left for Kalaman at dawn with Aeimos, leaving Kakashi a spell"],
            8: ["Named by Marshal Vendri as aiding other villages",
                "Greeted the party in Kalaman with sadness for Vogler",
                "Let Sunscale stay with Mayriel"],
            9: ["Proposed Ispin's stew as a remedy for despair and sent the party to hunt"],
            10: ["Dozed by the fire with his pipe",
                 "Dropped a recipe for Ispin's stew that turned out to hide the Green Flame Blade",
                 "Said he would stay in the city a little longer before moving on"],
        },
    ),
    dict(
        slug='darrett-highwater', name='Darrett Highwater', role="Becklin's former squire",
        relation='Ward and proxy commander', affiliation='Vogler; Kalaman service',
        met='vogler', aff='kalaman', standing='Ally', last=10, status='Active',
        overview="Darrett Highwater was Becklin's young squire in Vogler. He survived the town's fall, accepted her armor as a promise to grow into it, and now stands as the Embers' proxy with Kalaman so they are not formally conscripted. He trains under Marshal Vendri and sleeps among the Voglerans.",
        links=['npc:becklin-uth-viharin', 'npc:marshal-vendri', 'item:becklins-armor',
               'quest:service-to-kalaman', 'place:the-refugee-camp'],
        records={
            4: ["Brought the party to Thornwall Keep",
                "Called the charge at High Hill and found his courage when it turned real"],
            5: ["Led the scouts into the woods, confidence sometimes ahead of direction"],
            6: ["Studied the town map with Becklin for places to reinforce"],
            7: ["Was carried from the front line on Jeyev's back"],
            8: ["Saw Becklin in the river and was dragged under",
                "Refused her armor, then accepted it at Kalaman's gates",
                "Told the council that Vogler sought refuge, not war",
                "Stepped forward as intermediary between the party and Kalaman"],
            9: ["Joined the stew feast late, covered in sweat and dirt from training"],
            10: ["Took his rest among the Voglerans rather than behind the walls",
                 "Helped hold Aratos back in the training yard",
                 "Offered again to stand as the party's proxy; Vendri accepted",
                 "Stays behind to look after the camp"],
        },
    ),
    dict(
        slug='marshal-vendri', name='Marshal Vendri', role='Marshal of Kalaman',
        relation='Commanding authority', affiliation='Kalaman military',
        met='kalaman', aff='kalaman', standing='Ally', last=10, status='Active',
        overview="Marshal Vendri commands Kalaman's military. He acknowledged Aratos as a Knight Radiant, takes the Embers' service through Darrett, and hands out their missions.",
        links=['npc:governor-miat', 'npc:darrett-highwater', 'npc:roberto', 'quest:the-first-mission',
               'quest:service-to-kalaman', 'place:kalaman'],
        records={
            8: ["Sat on the council and confirmed the whole region is under pressure",
                "Spoke of Fizban and Aeimos aiding other villages",
                "Acknowledged Aratos's title of Knight Radiant",
                "Asked for a name to record the party under"],
            10: ["Ran to stop Aratos in the training yard",
                 "Heard him out, and kept his eyes on the axe",
                 "Sent the Embers to find the tinkerer Tatina Rookledust",
                 "Accepted Darrett as proxy and wrote the party's name in the record",
                 "Promised to look into remedies for a cursed weapon",
                 "Sent them off with two healing potions"],
        },
    ),
    dict(
        slug='governor-miat', name='Governor Miat', role='Governor of Kalaman',
        relation='Granting authority', affiliation='Kalaman government',
        met='kalaman', aff='kalaman', standing='Neutral', last=8, status='Active',
        overview="Governor Miat rules Kalaman and holds firm control of its council. He granted the people of Vogler refuge on the condition that the party aid the city's military efforts.",
        links=['npc:marshal-vendri', 'npc:bakaris-the-elder', 'quest:refuge-for-vogler',
               'quest:service-to-kalaman', 'place:kalaman'],
        records={
            8: ["Asked whether the people of Vogler intended retaliation",
                "Warned that other villages had come under attack as well",
                "Granted refuge in exchange for the party's service",
                "Was overheard holding firm against Lord Bakaris's interruptions"],
        },
    ),
    dict(
        slug='mayor-raven', name='Mayor Raven Uth Vogler', role='Mayor of fallen Vogler',
        relation='Grateful leader of the refugees', affiliation='Vogler refugees',
        met='vogler', aff='vogler', standing='Ally', last=10, status='Active',
        overview="Raven Uth Vogler is the mayor of Vogler. She resisted abandoning the town, then told its people the truth and led them onto the boats. She now leads the displaced Voglerans camped outside Kalaman, and has named the party honorary Voglerans.",
        links=['place:vogler', 'place:the-refugee-camp', 'quest:refuge-for-vogler',
               'quest:the-evacuation-of-vogler', 'npc:bakaris-the-elder'],
        records={
            4: ["Offered the party lodging in her home",
                "Led the festival parade to High Hill"],
            5: ["Stepped in before Cudgel's interrogation became nothing but vengeance",
                "Heard the scouts' report of the army beyond the woods"],
            6: ["Resisted the thought of abandoning Vogler",
                "Received the Red Army's scroll at the gate",
                "Told the town the truth and set it to packing"],
            8: ["Saw to the refugees at Kalaman and asked the party to speak for Vogler before the council"],
            9: ["Named the party honorary Voglerans",
                "Expected nothing better of Lord Bakaris"],
            10: ["Made her rounds of the camp and offered her goodnights"],
        },
    ),
    dict(
        slug='cudgel-ironsmile', name='Cudgel Ironsmile', role='Mercenary captain',
        relation='Ally at Vogler', affiliation='Her own mercenary company',
        met='vogler', aff='vogler', standing='Ally', last=7, status='Unknown',
        overview="Cudgel Ironsmile is a mercenary captain whose company played the old foe in Vogler's festival battle. Part of that company sold her out to the Red Army. She fought for the town to the end and was last seen kicked through a building on the burning waterfront.",
        links=['npc:gragonis', 'npc:becklin-uth-viharin', 'npc:the-charred-swordswoman',
               'quest:the-betrayal-at-high-hill', 'quest:the-evacuation-of-vogler', 'place:vogler'],
        records={
            4: ["Lowered Ispin's boat into the river with Becklin",
                "Cut through her own traitors at High Hill, horrified"],
            5: ["Nearly lost herself to rage questioning the captured mercenary",
                "Learned that her lieutenant Gragonis took the gold",
                "Went back to her camp alone to see who remained loyal"],
            6: ["Returned with her loyal lieutenant Jeyev",
                "Laid out the choice: stay and fight, or evacuate",
                "Climbed into the cliffside fight",
                "Posted her mercenaries north of town to slow the Red Army"],
            7: ["Fought beside Becklin on the waterfront",
                "Was kicked aside through a building"],
        },
    ),
    dict(
        slug='than', name='Than', role='Gnome tinkerer of Thornwall Keep',
        relation='Helpful eccentric', affiliation='Thornwall Keep, Vogler',
        met='vogler', aff='vogler', standing='Ally', last=7, status='Unknown',
        overview="Than is a frantic gnome tinkerer who kept a workshop at Thornwall Keep. He is scattered and hard to keep on one subject, and useful anyway. What became of him after Vogler fell is not known.",
        links=['place:thornwall-keep', 'quest:the-evacuation-of-vogler', 'pc:roshi'],
        records={
            6: ["Was found by Roshi at Thornwall Keep",
                "Admitted to unstable explosives that could be set as traps",
                "Offered to help repair boats and rig a signal"],
            7: ["Launched himself from the keep's roof with the gnome-flinger and landed on his feet at the docks",
                "Shot a red draconian, which exploded as it died",
                "Ran between the fallen with potions"],
        },
    ),
    dict(
        slug='gragonis', name='Gragonis', role="Cudgel's lieutenant",
        relation='Named as the traitor', affiliation="Cudgel's company; Red Army gold",
        met='vogler', aff='red-dragon-army', standing='Adversary', last=5, status='Unknown',
        named_only=True,
        overview="Gragonis was Cudgel Ironsmile's lieutenant. He went into the woods, came back with Red Army gold, and paid part of her company to turn on Vogler. The party has heard his name and has not met him.",
        links=['npc:cudgel-ironsmile', 'quest:the-betrayal-at-high-hill', 'fac:the-red-dragon-army'],
        records={
            5: ["Named by the captured mercenary as the one who brought the gold",
                "Said to have paid men to betray Cudgel, slaughter the militia, and leave Vogler open"],
        },
    ),
    dict(
        slug='bakaris-the-elder', name='Bakaris the Elder', role='Lord; nobleman',
        relation='Distrusted noble', affiliation='Nobility',
        met='vogler', aff='vogler', standing='Neutral', last=8, status='Active',
        overview="Lord Bakaris is a nobleman who dresses in red and gold and takes offense when plans are made without him. He prefers a sealed letter to a ride into danger. He reached Kalaman's council ahead of the refugees.",
        links=['npc:bakaris-the-younger', 'quest:the-bakarises', 'npc:governor-miat', 'place:kalaman'],
        records={
            6: ["Forced his way into the planning, offended that anyone had made plans without him",
                "Preferred sending a letter under his seal to riding for help",
                "Stirred fear from the edge of the crowd"],
            8: ["Suggested on the river that more might have been done to save the village",
                "Entered Kalaman ahead of the refugees and brought the council the news first",
                "Tried to twist the hearing until Aratos silenced him"],
        },
    ),
    dict(
        slug='bakaris-the-younger', name='Bakaris the Younger', role='Young nobleman',
        relation='Disliked noble', affiliation='Nobility',
        met='vogler', aff='vogler', standing='Neutral', last=8, status='Active',
        overview="Bakaris the Younger is a blond young nobleman, son of Lord Bakaris, with more arrogance than grace and very little real authority.",
        links=['npc:bakaris-the-elder', 'quest:the-bakarises'],
        records={
            4: ["Mocked the mourners' affection for Ispin at the Brass Crab until Becklin sent him off",
                "Gave away nothing useful about Kalaman or his father before the mock battle"],
            8: ["Echoed his father on the river: more might have been done",
                "Stood in the party's way outside the council and called the refugees fishfolk"],
        },
    ),
    dict(
        slug='wyhan', name='Wyhan', role='Apothecary and mage of High Sorcery',
        relation='Sharp, transactional contact', affiliation='High Sorcery; Kalaman apothecary',
        met='kalaman', aff='high-sorcery', standing='Neutral', last=10, status='Active',
        overview="Wyhan keeps an apothecary in Kalaman and is a mage of High Sorcery. She set Kakashi and Jasper to test for the White Robes, and Seredyn names her as the best lead to the Tower of Wayreth.",
        links=['quest:the-white-robes', 'quest:the-orb-of-dragonkind', 'quest:fizbans-recipe',
               'fac:the-mages-of-high-sorcery', 'place:kalaman', 'place:tower-of-wayreth'],
        records={
            8: ["Examined the High Sorcery scrolls Kakashi and Jasper carried",
                "Determined both would test for the White Robes, with a practical exam weeks out",
                "Dismissed them with little ceremony"],
            10: ["Sold Kakashi components to restore his familiar",
                 "Named a price for spell scrolls well beyond what he carried",
                 "Confirmed that the numbers in Fizban's recipe were a cipher, and that the spell was Green Flame Blade",
                 "Was named by Seredyn as Jasper's best lead to the tower"],
        },
    ),
    dict(
        slug='roberto', name='Roberto', role='Squire at Kalaman',
        relation='Sparring partner, injured', affiliation='Kalaman garrison',
        met='kalaman', aff='kalaman', standing='Neutral', last=10, status='Injured',
        overview="Roberto is a squire in Kalaman's garrison. He walked the courtyard statues with Aratos, and later took the Emberwake's blade in a sparring match.",
        links=['pc:aratos', 'item:the-emberwake-greataxe', 'quest:the-emberwakes-curse', 'npc:marshal-vendri'],
        records={
            8: ["Walked the courtyard statues with Aratos, Lord Soth's among them",
                "Pointed him to Marshal Vendri for questions about such things"],
            10: ["Sparred with Aratos and landed one clean hit",
                 "Was cut down by the Emberwake",
                 "Alive, unconscious and badly hurt; expected to recover"],
        },
    ),
    dict(
        slug='seredyn', name='Seredyn', role="Head of the Dragon's Eye in Kalaman",
        relation='Guild handler, wary', affiliation="Dragon's Eye, Kalaman branch",
        met='kalaman', aff='dragons-eye', standing='Neutral', last=10, status='Active',
        overview="Seredyn heads the Dragon's Eye branch in Kalaman from a table at the back of Finn's Bar. He dresses richly, wears gold earrings, and walks the city behind a faint illusion. Lucky had not told him Jasper was coming.",
        links=['npc:lucky', 'npc:finbar', 'pc:jasper', 'quest:the-orb-of-dragonkind',
               'fac:the-dragons-eye', 'place:kalaman'],
        records={
            8: ["Left the council chamber shimmering faintly with illusion; he and Jasper acknowledged each other without a word"],
            10: ["Saw through Jasper's attempt at misdirection",
                 "Received the truth of the Orb task with something between surprise and resignation",
                 "Named Wyhan as the lead to the Tower of Wayreth",
                 "Warned that getting into the tower might prove easier than getting out",
                 "Twitched at the corner of one eye when Lucky was named",
                 "Told Jasper to keep his visit short, cause no trouble, and let nothing come back to him"],
        },
    ),
    dict(
        slug='finbar', name='Finbar', role="Dragon's Eye contact",
        relation='Guild contact, once "Old Man Jenkins"', affiliation="Dragon's Eye",
        met='vogler', aff='dragons-eye', standing='Neutral', last=10, status='Active',
        aliases=['Old Man Jenkins', 'Jenkins'],
        overview="Finbar is a member of the Dragon's Eye who can pass unseen. In Vogler he wore the face of Old Man Jenkins at General Goods. In Kalaman he dropped the disguise and walked Jasper to the guild.",
        links=['npc:seredyn', 'npc:lucky', 'pc:jasper', 'item:winged-boots', 'item:leeching-bolts',
               'quest:finbar', 'quest:the-orb-of-dragonkind', 'fac:the-dragons-eye'],
        records={
            4: ["As Old Man Jenkins, summoned Jasper by a note left in his pocket",
                "Explained the guild, Lucky, the coin and the task",
                "Sold Jasper a pair of winged boots"],
            5: ["Was found packing to flee Vogler",
                "Gave Jasper two healing potions and leeching bolts when Jasper chose to stay"],
            7: ["Slipped onto the boat unseen by most"],
            10: ["Watched the camp from just outside the firelight",
                 "Dropped his invisibility and the old man's face",
                 "Led Jasper to Peller's Provisions, knocked three times, and gave the passphrase",
                 "Walked him out again"],
        },
    ),
    dict(
        slug='lucky', name='Lucky Leppomanto', role="Guild master of the Dragon's Eye",
        relation="Jasper's creditor", affiliation="Dragon's Eye",
        met='visions', aff='dragons-eye', standing='Unknown', last=8, status='Active',
        aliases=['Lucky'],
        overview="Lucky Leppomanto is the guild master of the Dragon's Eye. He bound Jasper to the guild with a coin and set him a task: steal the Orb of Dragonkind from the Tower of Wayreth. The party has seen him only in dream and apparition.",
        links=['pc:jasper', 'npc:seredyn', 'npc:finbar', 'item:dragons-eye-coin',
               'quest:the-orb-of-dragonkind', 'fac:the-dragons-eye'],
        records={
            2: ["Appeared in Jasper's dream of the guild, the coin and the debt"],
            8: ["Appeared to Jasper in the river and warned that time was running out"],
            10: ["Had told Seredyn nothing of Jasper's presence or task in Kalaman"],
        },
    ),
    dict(
        slug='theros-flametongue', name='Theros Flametongue', role='Orcish warrior with a flaming axe',
        relation='Defeated adversary, returned', affiliation='Red Dragon Army',
        met='vogler', aff='red-dragon-army', standing='Adversary', last=7, status='Slain, then risen',
        portrait=IMG + '11vuG_FppfLpj1OMBTRuGTnc5hTGlMpqS',
        overview="Theros Flametongue is a green-skinned orcish warrior who rode into Vogler on the dragon machine carrying a flaming axe. Mayriel killed him on the docks. As the boats pulled away, flame passed over his body and he stood up again.",
        links=['item:the-emberwake-greataxe', 'pc:aratos', 'pc:mayriel', 'quest:theros-flametongue',
               'fac:the-red-dragon-army', 'place:vogler'],
        records={
            7: ["Leapt from the dragon machine and mocked what he had heard of Vogler's heroes",
                "Dueled Aratos at the heart of the burning dock",
                "Was killed by Mayriel's spiritual sword",
                "Lost his axe to Aratos",
                "Rose again as flame passed across his body"],
        },
    ),
    dict(
        slug='the-charred-swordswoman', name='The Charred Swordswoman', role='Unidentified warrior',
        relation='Unidentified adversary', affiliation='Red Dragon Army',
        met='vogler', aff='red-dragon-army', standing='Adversary', last=7, status='Unknown',
        overview="A tall woman with charred skin, blackened armor and a massive sword, seen through the smoke at Vogler's waterfront. The party does not know her name.",
        links=['npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'fac:the-red-dragon-army', 'place:vogler'],
        records={
            7: ["Held back on the waterfront by Becklin and Cudgel as the last boat left",
                "Kicked Cudgel Ironsmile aside through a building"],
        },
    ),
    dict(
        slug='lord-soth', name='Lord Soth', role='Fallen Knight of Solamnia',
        relation='Looming antagonist', affiliation='Knights of Solamnia (fallen)',
        met='visions', aff='knights', standing='Adversary', last=9, status='At large',
        overview="Lord Soth was once a celebrated Knight of Solamnia. He fell through selfishness and personal failure and lives in disgrace under a curse. He works through servants to corrupt knights and their legacies, and means to continue until the curse is lifted. He has brushed the party's path and has not moved against them.",
        links=['quest:lord-soths-corruption', 'quest:fire-and-frost', 'pc:aratos', 'pc:aeimos',
               'npc:sir-cthondor', 'npc:the-pale-elven-woman', 'fac:the-knights-of-solamnia',
               'place:the-reliquary-of-sir-cthondor'],
        records={
            8: ["Appeared to Aratos in the river beside Cathan Twice-Born; the two told him he would have to choose soon",
                "His statue stands in Kalaman's courtyard among knights once honored"],
            9: ["A necromancer died in his service while corrupting the tomb of Sir Cthondor",
                "Said by the pale woman to seek the corruption of all knights: their image, their legacies, and the memory of what they were"],
        },
    ),
    dict(
        slug='sir-cthondor', name='Sir Cthondor', role='Knight Radiant, at rest',
        relation='Freed spirit', affiliation='Knights Radiant',
        met='kalaman', aff='knights', standing='Ally', last=10, status='At rest',
        overview="Sir Cthondor was a Knight Radiant whose tomb lies in a hidden reliquary outside Kalaman. A necromancer serving Lord Soth raised his spirit as a wraith. Freed, he named Aratos and Aeimos children of Cathan and sounded his horn to send the risen dead back to rest.",
        links=['place:the-reliquary-of-sir-cthondor', 'item:horn-of-sir-cthondor', 'npc:lord-soth',
               'pc:aratos', 'pc:aeimos', 'fac:the-knights-radiant', 'quest:meat-for-ispins-stew'],
        records={
            9: ["Stood at the centre of the tomb, horn in the crook of his arm, as he does in the murals",
                "Rose as a wraith in violet shadow when the necromancer's ritual went far enough",
                "Was freed by Roshi's spiritual weapon",
                "Named Aratos and Aeimos children of Cathan and told them they had proven themselves",
                "Blew his horn and returned the risen knights to rest"],
            10: ["Aratos knelt before his statue and asked the honored dead for help carrying the axe"],
        },
    ),
    dict(
        slug='the-pale-elven-woman', name='The Pale Elven Woman', role='Unidentified elven figure',
        relation='Mysterious guide to Aeimos', affiliation='Unknown',
        met='kalaman', aff='unaffiliated', standing='Unknown', last=9, status='Active',
        overview="A pale, beautiful elven woman with long flowing hair who appears to Aeimos, points, and vanishes. She has spoken once.",
        links=['pc:aeimos', 'npc:lord-soth', 'quest:lord-soths-corruption'],
        records={
            9: ["Appeared behind Mayriel during the hunt and pointed toward the others",
                "Told Aeimos that Lord Soth seeks to corrupt all knights until his curse is lifted",
                "Pointed into the distance when he asked where to go"],
        },
    ),
    dict(
        slug='sunscale', name='Sunscale', role='Golden finch',
        relation="Mayriel's companion", affiliation='Unknown',
        met='vogler', aff='unaffiliated', standing='Ally', last=8, status='Active',
        overview="Sunscale is a golden finch that appeared to Mayriel in Vogler. It had kept company with Fizban; given the choice in Kalaman, it stayed with her.",
        links=['pc:mayriel', 'npc:fizban', 'item:divine-pendant'],
        records={
            4: ["Mayriel woke to a golden finch and a pendant"],
            7: ["The golden bird swept into view as Mayriel pledged her ring; its radiance restored the party enough to move"],
            8: ["Returned to Fizban, then made its choice and stayed with Mayriel"],
        },
    ),
    dict(
        slug='ispin-greenshield', name='Ispin Greenshield', role='Late adventurer, friend to many',
        relation='Honored dead', affiliation='None',
        met='vogler', aff='unaffiliated', standing='Ally', last=8, status='Dead',
        overview="Ispin Greenshield was an old adventurer whose brief human life left lasting marks on elven memory. His funeral in Vogler drew Roshi and Mayriel onto the road. He asked for tales, not tears.",
        links=['item:ispins-green-shield', 'pc:roshi', 'npc:becklin-uth-viharin', 'npc:fizban',
               'place:vogler', 'item:fizbans-stew-recipe'],
        records={
            1: ["Letters of his death drew Roshi and Mayriel toward Vogler"],
            4: ["Was sent down the Vingaard in a shrouded boat at sunset",
                "Was remembered at the Brass Crab: the volcano ridden on a shield, the bear den and the honey, the wyrmling",
                "His green shield passed to Roshi"],
            8: ["Appeared to Roshi in the river, asking whether she had truly protected the villagers"],
            9: ["His stew, by Fizban's account of the recipe, fed the refugee camp for a night"],
        },
    ),
]

# Named, but with nothing behind the name worth a page. One line each.
UNFILED = [
    ('Jeyev', "Cudgel's loyal lieutenant, shaved-headed. Rode out for help in Journey 006 and carried Darrett off the front line in 007."),
    ('Tatina Rookledust', "A tinkerer several days' travel from Kalaman. Marshal Vendri believes she can explain the mechanical dragon. Not yet met."),
    ('Cathan Twice-Born', "Ancestor of Aratos and Aeimos. Appeared to Aratos in the river in Journey 008, opposite Lord Soth."),
    ('The King', "An ancestral spirit in a dark green hood who appears to Aratos. The same blood flows through my veins. The same weakness."),
    ('Gertrude', "Smith in Vogler. Aratos met Becklin at her smithy in Journey 003."),
]
