"""
campaign_world.py - journeys, places, items, factions, quests, and where the
party stands. Same rules as campaign_people.py: player-known framing only.
"""

IMG = 'https://lh3.googleusercontent.com/d/'

CAMPAIGN = dict(
    title='Shadow of the Dragon Queen',
    tagline='Takhisis stirs. Her armies march on Ansalon.',
    kicker='A Dragonlance Campaign',
    party='The Embers',
    scheduler='https://rallly.co/invite/D8kMYvewkWxI',
    playlist='https://www.youtube.com/playlist?list=PLN57h0dwcT5t6izo-CKegvP96QNZyXIDn',
    gate_art=IMG + '1HxtWOhCcRJALSWUbbrUCKNGmLYB8fIPG',
)

FIVE = ['aratos', 'kakashi', 'jasper', 'roshi', 'mayriel']
SIX = FIVE + ['aeimos']

# ---------------------------------------------------------------------------
# JOURNEYS
# ---------------------------------------------------------------------------
# npcs / places / items are (label, ref-or-None). A ref links the chip; None
# leaves it as plain text. The accounts themselves live in _build/journeys/.
# video: a YouTube ID, None if not linked yet, False if the session was not recorded.

JOURNEYS = [
    dict(num=1, title='The Night of the Eye', level=1, where='Road to Vogler', video='lUOB97A9Bl0',
         subtitle='Five strangers meet in an ambush on the road to Vogler.',
         synopsis='Aratos dreams of draconic warriors and sets out for Kalaman. Kakashi and Jasper pass a mage trial. Roshi and Mayriel travel to a funeral. All five meet when a caravan is ambushed by scaled, Draconic-speaking soldiers. The one they capture speaks of a Shadow Queen, says the east has fallen, and kills itself.',
         pcs=FIVE,
         npcs=[('Fallen Solamnic knights', None), ('Draconian ambushers', 'fac:draconians')],
         places=[('The Road to Vogler', None), ('An old holy place', None)],
         items=[('Moon-Marked Spellbook', 'item:moon-marked-spellbook')]),
    dict(num=2, title='The Road After Bloodshed', level=1, where='Road to Vogler', video='XiRpDQrTqls',
         subtitle='Bad dreams in the night, and a creature of living sand on the road.',
         synopsis='The party burns the scaled dead and takes what clues the fallen knights carried. On the road they find an old man half-swallowed by a creature of living sand and break it. He is Fizban, a green-robed wizard and friend of Ispin, and he walks with them to Vogler, where the fish are vanishing.',
         pcs=FIVE,
         npcs=[('Fizban', 'npc:fizban'), ('Lucky', 'npc:lucky')],
         places=[('The Road to Vogler', None), ('Vogler', 'place:vogler'), ('The Vingaard River', 'place:the-vingaard-river')],
         items=[("Dragon's Eye Coin", 'item:dragons-eye-coin')]),
    dict(num=3, title='The Beast Beneath Crustdurn Isle', level=2, where='Vogler', video='p_iMbkL0n8w',
         subtitle='Vogler fed them well. Something in the river was taking the fish.',
         synopsis='The party explores Vogler, hears tales of Ispin, and Aratos is reunited with his cousin Aeimos. The trouble in the river leads to Crustdurn Isle, where a tentacled frog-beast beneath an abandoned shack swallows Roshi before it is killed. They come back with treasure and proof.',
         pcs=SIX,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Fizban', 'npc:fizban')],
         places=[('Vogler', 'place:vogler'), ('Crustdurn Isle', 'place:crustdurn-isle'), ('The Brass Crab', 'place:vogler')],
         items=[('Moon-Touched Sword', 'item:moon-touched-sword')]),
    dict(num=4, title='Tales, Tears, and Treachery', level=2, where='Vogler', video='5BhFMMHMYpI',
         subtitle="Ispin's memory became a shield, and Vogler became a battlefield.",
         synopsis="Ispin Greenshield's funeral becomes a celebration of an impossible life. The Kingfisher Festival mock battle turns into a massacre when some of Cudgel's mercenaries turn on Vogler.",
         pcs=SIX,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Mayor Raven', 'npc:mayor-raven'), ('Darrett Highwater', 'npc:darrett-highwater'),
               ('Bakaris the Younger', 'npc:bakaris-the-younger'), ('Fizban', 'npc:fizban'),
               ('Old Man Jenkins', 'npc:finbar'), ('Ispin Greenshield', 'npc:ispin-greenshield'),
               ('Sunscale', 'npc:sunscale')],
         places=[('Vogler', 'place:vogler'), ('The Brass Crab', 'place:vogler'), ('High Hill', 'place:vogler'),
                 ('Thornwall Keep', 'place:thornwall-keep')],
         items=[("Ispin's Green Shield", 'item:ispins-green-shield'), ('Winged Boots', 'item:winged-boots'),
                ('Divine Pendant', 'item:divine-pendant')]),
    dict(num=5, title='Shadows in the Woods', level=3, where='Vogler Surrounds', video='mbw91Av_Obc',
         subtitle='An army waits beyond the woods, and Vogler has little time.',
         synopsis="A captured mercenary names Cudgel's lieutenant Gragonis as the one who took Red Army gold. Scouts find a real army of one to two hundred in the woods. Roshi and Mayriel's healing draws awe from the wounded. The party chooses to stay.",
         pcs=FIVE,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Mayor Raven', 'npc:mayor-raven'), ('Darrett Highwater', 'npc:darrett-highwater'),
               ('Gragonis', 'npc:gragonis'), ('Old Man Jenkins', 'npc:finbar')],
         places=[('Vogler', 'place:vogler'), ('High Hill', 'place:vogler'), ('The Brass Crab', 'place:vogler'),
                 ('The woods beyond Vogler', None)],
         items=[('Leeching Arrows', 'item:leeching-arrows'), ("Dragon's Eye Coin", 'item:dragons-eye-coin')]),
    dict(num=6, title="The Dragon Queen's Demand", level=3, where='Vogler', video='EDvLu6R2ufQ',
         subtitle='An ultimatum in black and red. Surrender by sunset, or burn.',
         synopsis="A rider in black and red delivers the Red Dragon Army's terms: open Vogler's doors by sunset or face slaughter. The party stages a distraction to get Cudgel's lieutenant Jeyev out for help, and kills the messenger and his watchers. The evacuation begins.",
         pcs=FIVE,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Mayor Raven', 'npc:mayor-raven'), ('Bakaris the Elder', 'npc:bakaris-the-elder'),
               ('Than', 'npc:than'), ('Darrett Highwater', 'npc:darrett-highwater'), ('Jeyev', None)],
         places=[('Vogler', 'place:vogler'), ('Thornwall Keep', 'place:thornwall-keep'), ('The north approach', None)],
         items=[('Periapt from the Cliffside', 'item:periapt-from-the-cliffside'),
                ('Blue-Gemmed Ring', 'item:blue-gemmed-ring'), ('Leeching Arrows', 'item:leeching-arrows')]),
    dict(num=7, title='Flames Over Vogler', level=3, where='Vogler Docks', video='3yBIUfOKBFI',
         subtitle='The sky darkens with wings. A dragon comes to Krynn.',
         synopsis="The Red Army attacks during the evacuation and a dragon burns the docks. Theros Flametongue duels Aratos. The dragon proves to be a crewed machine. Mayriel kills Theros, and Aratos brings the machine down. From the last boat the party watches Becklin fall.",
         pcs=FIVE,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Than', 'npc:than'), ('Theros Flametongue', 'npc:theros-flametongue'),
               ('The Charred Swordswoman', 'npc:the-charred-swordswoman'),
               ('Darrett Highwater', 'npc:darrett-highwater'), ('Finbar', 'npc:finbar'),
               ('Sunscale', 'npc:sunscale'), ('Jeyev', None)],
         places=[('Vogler docks', 'place:vogler'), ('Thornwall Keep', 'place:thornwall-keep'),
                 ('The Vingaard River', 'place:the-vingaard-river')],
         items=[('The Emberwake Greataxe', 'item:the-emberwake-greataxe'), ('Boilerdrake Heart', 'item:boilerdrake-heart'),
                ("Mayriel's Signet Ring", 'item:mayriels-signet-ring'), ('Winged Boots', 'item:winged-boots')]),
    dict(num=8, title='Ashes on the River', level=4, where='Vingaard River to Kalaman', video=False,
         subtitle='The dead rise from the river on the way to Kalaman.',
         synopsis='On the river the dead rise as Ashen Vigils, each showing a survivor someone different. The party breaks them, reaches Kalaman, and argues its way before the council. Vogler is given refuge in exchange for military service, with Darrett as the go-between.',
         pcs=FIVE,
         npcs=[('Darrett Highwater', 'npc:darrett-highwater'), ('Mayor Raven', 'npc:mayor-raven'),
               ('Governor Miat', 'npc:governor-miat'), ('Marshal Vendri', 'npc:marshal-vendri'),
               ('Bakaris the Elder', 'npc:bakaris-the-elder'), ('Bakaris the Younger', 'npc:bakaris-the-younger'),
               ('Wyhan', 'npc:wyhan'), ('Roberto', 'npc:roberto'), ('Fizban', 'npc:fizban'),
               ('Sunscale', 'npc:sunscale'), ('Lord Soth', 'npc:lord-soth'), ('Lucky', 'npc:lucky'),
               ('Cathan Twice-Born', None)],
         places=[('The Vingaard River', 'place:the-vingaard-river'), ('Kalaman', 'place:kalaman')],
         items=[("Becklin's Armor", 'item:becklins-armor'), ('Boilerdrake Heart', 'item:boilerdrake-heart'),
                ('The Emberwake Greataxe', 'item:the-emberwake-greataxe')]),
    dict(num=9, title='The Reliquary of Lost Oaths', level=4, where='Outside Kalaman', video='5olPIXViJD4',
         subtitle='Behind an oath-tested door, a necromancer is raising the knights buried there.',
         synopsis="Sent to hunt meat for Ispin's stew, the party finds a hidden Knights Radiant reliquary behind an oath-tested door. A necromancer serving Lord Soth is corrupting the tomb of Sir Cthondor. They defeat him and the wraith he raises, and the freed spirit names Aratos and Aeimos children of Cathan.",
         pcs=SIX,
         npcs=[('Sir Cthondor', 'npc:sir-cthondor'), ('The Pale Woman', 'npc:the-pale-woman'),
               ('Fizban', 'npc:fizban'), ('Mayor Raven', 'npc:mayor-raven'),
               ('Darrett Highwater', 'npc:darrett-highwater'), ("Lord Soth's necromancer", 'npc:lord-soth')],
         places=[('The refugee camp', 'place:the-refugee-camp'),
                 ('The reliquary', 'place:the-reliquary-of-sir-cthondor')],
         items=[('Horn of Sir Cthondor', 'item:horn-of-sir-cthondor'), ('Armor of Bone', 'item:armor-of-bone')]),
    dict(num=10, title='The Weight of the Axe', level=4, where='Kalaman', video='G0hiBL1WDE0',
         subtitle='A recipe hides a spell. A trophy hides a curse.',
         synopsis="Fizban's stew recipe turns out to be a cipher for a spell. Finbar takes Jasper to meet the head of the Dragon's Eye in Kalaman. In a sparring match the trophy axe's rage overtakes Aratos and he nearly kills a squire; at the reliquary he masters it once through restraint. Marshal Vendri sends the party, now named the Embers, to find the tinkerer Tatina Rookledust.",
         pcs=FIVE,
         npcs=[('Fizban', 'npc:fizban'), ('Finbar', 'npc:finbar'), ('Seredyn', 'npc:seredyn'),
               ('Wyhan', 'npc:wyhan'), ('Roberto', 'npc:roberto'), ('Marshal Vendri', 'npc:marshal-vendri'),
               ('Darrett Highwater', 'npc:darrett-highwater'), ('Mayor Raven', 'npc:mayor-raven'),
               ('Sir Cthondor', 'npc:sir-cthondor')],
         places=[('The refugee camp', 'place:the-refugee-camp'), ('Kalaman', 'place:kalaman'),
                 ("Finn's Bar", 'place:kalaman'), ('The reliquary', 'place:the-reliquary-of-sir-cthondor')],
         items=[("Fizban's Stew Recipe", 'item:fizbans-stew-recipe'),
                ('The Emberwake Greataxe', 'item:the-emberwake-greataxe')]),
    dict(num=11, title='The Moons Over Bracken Hollow', level=4, where='Bracken Hollow', video='Zuxn5gqO9wQ',
         subtitle='A village no one can leave. An eclipse that takes one of them each time.',
         synopsis="A list from Wyhan draws the Embers to Bracken Hollow, a village under three eclipsed moons. No one has been able to leave it for a month. Sergeant Boyd explains the turn of the white, red and black moons, and the eclipse that takes one villager each time. The party climbs the hill with Corvin and Ked and brings down the stone monument by darkening the three rings on its chest, but the Emberwake's fury takes Aratos and Roshi has to drop him. Beneath the hill are three recesses, and three things to find in the village before the next eclipse.",
         pcs=FIVE,
         npcs=[('Sergeant Boyd', 'npc:sergeant-boyd'), ('Corvin', 'npc:corvin'), ('Ked', 'npc:ked'),
               ('Wyhan', 'npc:wyhan'), ('Gribb Brack', None), ('Marigold', None)],
         places=[('Bracken Hollow', 'place:bracken-hollow'), ('The graveyard', 'place:bracken-hollow'),
                 ('The hill and its monument', 'place:bracken-hollow'),
                 ('The cavern beneath the hill', 'place:bracken-hollow')],
         items=[('The Emberwake Greataxe', 'item:the-emberwake-greataxe'),
                ('The Horn of Sir Cthondor', 'item:horn-of-sir-cthondor'),
                ('Moon-Touched Sword', 'item:moon-touched-sword'),
                ('Leeching Arrows', 'item:leeching-arrows'),
                ('Periapt from the Cliffside', 'item:periapt-from-the-cliffside')]),
]

# ---------------------------------------------------------------------------
# THE ATLAS
# ---------------------------------------------------------------------------
# region: kalaman | vogler | beyond
# sites are named spots inside a place that do not need a page of their own.

REGIONS = [
    ('kalaman', 'Kalaman', 'The walled city, its camp, and the hills around it.'),
    ('vogler', 'Vogler', 'The town on the Vingaard that the party could not save.'),
    ('beyond', 'Beyond', 'The roads between, and places known only by name.'),
]

ATLAS_MAP = dict(src=IMG + '1V7_DqsoC7C3KVWuW27c-Um8YASEvQaxm', alt='Map of Ansalon',
                 caption='Ansalon')

PLACES = [
    dict(slug='kalaman', name='Kalaman', kind='Walled city', region='kalaman', where='On the Vingaard',
         last=10, status='Base of operations',
         overview="Kalaman is a walled city half a day downriver from Vogler. It took in Vogler's refugees in exchange for the party's service. It holds a High Sorcery presence, a hidden branch of the Dragon's Eye, and a courtyard of knightly statues that includes Lord Soth.",
         sites=[('The council chambers', "Where Governor Miat granted Vogler refuge."),
                ('The castle training yard', "Where the Emberwake took Aratos in a sparring match."),
                ('The knights\' courtyard', "Statues of knights once honored, Lord Soth among them."),
                ("Wyhan's Apothecary", "Components, potions at steep prices, and High Sorcery's business."),
                ("Peller's Provisions", "A general goods store. Look closely at the sign and it reads Finn's Bar. Knock three times.")],
         links=['npc:governor-miat', 'npc:marshal-vendri', 'npc:wyhan', 'npc:seredyn', 'npc:roberto',
                'npc:bakaris-the-elder', 'place:the-refugee-camp', 'place:the-reliquary-of-sir-cthondor',
                'quest:service-to-kalaman', 'fac:the-dragons-eye'],
         records={
             8: ["Rose ahead on the river, half a day from Vogler",
                 "Its council heard the party and granted the refugees shelter in exchange for military service",
                 "A Dragon's Eye agent walked out of the council chamber under an illusion"],
             9: ["Let the refugees camp outside its walls"],
             10: ["Finbar brought Jasper through the gates by night to Finn's Bar",
                  "Aratos cut down a squire in the castle training yard",
                  "Its marshal recorded the party as the Embers and sent them out on their first mission"],
         }),
    dict(slug='the-refugee-camp', name='The Refugee Camp', kind='Encampment', region='kalaman',
         where='Outside Kalaman', last=10, status='Home base',
         overview="Tents along the Vingaard River outside Kalaman's walls, where the people of Vogler have settled. Darrett sleeps here among the Voglerans, and the party kept its fire here until it left on its first mission.",
         links=['npc:mayor-raven', 'npc:darrett-highwater', 'npc:fizban', 'place:kalaman', 'place:vogler',
                'quest:refuge-for-vogler'],
         records={
             9: ["Pitched beneath the city's walls with tents and fresh water enough for the moment",
                 "Fed for a night on bear and Ispin's stew"],
             10: ["Lighter after the stew, with warm voices around the fires",
                  "Aratos saw the tree of fire and frost in its campfire",
                  "Kakashi saw three full moons and an elven woman in a pail of water near the tents"],
         }),
    dict(slug='the-reliquary-of-sir-cthondor', name='The Reliquary of Sir Cthondor', kind='Hidden tomb',
         region='kalaman', where='Hills outside Kalaman', last=10, status='Cleansed',
         overview="A cave outside Kalaman opens onto a stone door marked with the sword of the Knights Radiant, drawn with six points. The door asks for an oath. Behind it lie murals of a floating city falling, and a tomb of knights with Sir Cthondor at its center.",
         sites=[('The oath door', "Lit Valor for Aratos, Resolve for Aeimos, Foresight for Roshi."),
                ('The mural passage', "Knights of Solamnia and Knights Radiant beneath a floating city, then the city falling. Defaced with purplish-black ash."),
                ('The tomb', "Armored dead along the walls and the statue of Sir Cthondor, whose horn Aratos now carries.")],
         links=['npc:sir-cthondor', 'npc:lord-soth', 'item:horn-of-sir-cthondor', 'item:armor-of-bone',
                'fac:the-knights-radiant', 'quest:meat-for-ispins-stew', 'quest:the-emberwakes-curse',
                'quest:lord-soths-corruption'],
         records={
             9: ["Found at the end of a bear trail, a blue glow pulsing from inside",
                 "Its door opened to the party's oaths",
                 "A necromancer serving Lord Soth was raising its dead over a spectral black rose",
                 "Went quiet again when Sir Cthondor sounded his horn"],
             10: ["The door opened at the remembered sequence",
                  "Aratos knelt before the statue and held the Emberwake through restraint"],
         }),
    dict(slug='vogler', name='Vogler', kind='Riverside town', region='vogler', where='On the Vingaard',
         last=7, status='Destroyed', portrait=IMG + '1_IqP61QpZkvN-ugktyUe91hGKDyXiYG0',
         plate=dict(src=IMG + '1A-nxlQT29DGSJkhR2kh0BKrBGIJo_mGo', alt='Map of Vogler', caption='Vogler, before the fire'),
         overview="Vogler was a village on the Vingaard River that knew how to mourn and celebrate in the same breath. It honored Ispin Greenshield, held the Kingfisher Festival, and was burned by the Red Dragon Army's mechanical dragon. Its people are now refugees outside Kalaman.",
         sites=[('The Brass Crab', "Food, drink and stories. Crab ramen, at your own risk."),
                ('High Hill', "Where the festival's mock battle turned into a massacre."),
                ('The docks', "A fish statue touched for luck; later, the last stand."),
                ("Gertrude's smithy", "Where Aratos first spoke with Becklin."),
                ('General Goods', "Old Man Jenkins behind the counter.")],
         links=['npc:mayor-raven', 'npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'npc:than',
                'npc:ispin-greenshield', 'place:thornwall-keep', 'place:crustdurn-isle',
                'place:the-vingaard-river', 'place:the-refugee-camp', 'quest:the-evacuation-of-vogler',
                'quest:the-betrayal-at-high-hill', 'quest:the-vanishing-fish', 'fac:the-red-dragon-army'],
         records={
             2: ["Reached during preparations for the Kingfisher Festival and Ispin's funeral",
                 "Its fishermen spoke of vanishing fish and strange sounds from the river"],
             3: ["Kept safe another day when the beast beneath Crustdurn Isle was killed"],
             4: ["Sent Ispin down the river at sunset and told his stories at the Brass Crab",
                 "Betrayed at High Hill by mercenaries paid by the Red Army"],
             5: ["Carried its wounded home beneath festival banners",
                 "Learned an army of one to two hundred waited beyond the woods"],
             6: ["Ordered to open its doors by sunset or face slaughter",
                 "Began to pack, repair boats and set traps"],
             7: ["Burned by a dragon that turned out to be a machine",
                 "Its last boats got away; Becklin fell holding the docks"],
         }),
    dict(slug='thornwall-keep', name='Thornwall Keep', kind='Keep', region='vogler', where='Vogler',
         last=7, status='Lost with Vogler',
         overview="The keep at Vogler. Becklin gave Roshi Ispin's shield here, Than kept his workshop here, and Becklin left a chest here for Darrett. It burned with the town.",
         links=['npc:than', 'npc:becklin-uth-viharin', 'place:vogler', 'item:ispins-green-shield'],
         records={
             4: ["Becklin gave Roshi Ispin's Green Shield here"],
             6: ["Roshi found Than and his unstable explosives",
                 "From its height she spotted the messenger's watchers on the cliff",
                 "Becklin named a chest here to be brought to Darrett if she did not return"],
             7: ["Flames climbed the tower; Than left by gnome-flinger from the roof"],
         }),
    dict(slug='crustdurn-isle', name='Crustdurn Isle', kind='River island', region='vogler',
         where='Vingaard River, near Vogler', last=3, status='Cleared',
         portrait=IMG + '1vo5CCa735IpdEeKIybErdPNBYQ5R5q92',
         overview="A lonely island in the river near Vogler, rumored haunted and avoided by locals. A hatch in its abandoned shack leads down to a cavern littered with fish bones.",
         links=['place:vogler', 'quest:the-vanishing-fish', 'item:moon-touched-sword'],
         records={
             3: ["Scouted by Kakashi's raven, then reached by rented rowboat",
                 "Old writings below suggested something had once needed to be fed or appeased",
                 "The beast in the cavern swallowed Roshi and was killed",
                 "Gave up a moon-touched sword and a pair of boots marked by strange magic"],
         }),
    dict(slug='bracken-hollow', name='Bracken Hollow', kind='Forest village', region='beyond',
         where='Off the road out of Kalaman', last=11, status='Sealed',
         overview="A plain village tucked into the forest, of the same sort as Vogler, with no wall and no guard at its gate. For about a month no one has been able to leave it: a person who walks out past its edge walks back in on the far side. The three moons hang over it in eclipse and take turns. Under the white moon people feel a little sick and echoes of the villagers walk the streets. Under the red a battle is fought in the town. Under the black the wolves come, and the farms give food. Then comes the eclipse itself, when the monument on the hill wakes and one of the black-touched vanishes. About two hundred people lived here. Around forty are gone.",
         sites=[('The graveyard', "A short walk from the square. Many of its graves are fresh."),
                ("Boyd's shelter", "A dim, run-down house where Boyd keeps villagers through the dangerous hours."),
                ('The farms', "They give food only under the black moon, when the wolves are out."),
                ('The hill and its monument', "A tall block of stone that wakes and stands during the eclipse. Three rings on its chest: white, red, black."),
                ('The cavern beneath the hill', "Reached by a crevice where the monument stood. Closed, with three recesses. The spell is bound here."),
                ("Marigold's cottage", "Just outside the village. Home of the healer, who was away the night it closed.")],
         links=['npc:sergeant-boyd', 'npc:corvin', 'npc:ked', 'quest:the-spell-over-bracken-hollow',
                'quest:the-ones-sent-up-the-hill', 'quest:wyhans-list', 'pc:kakashi', 'pc:aratos'],
         records={
             11: ["Seen through the trees from a creek; a flag stirred inside its gate",
                  "Went dark as the party walked in, under three moons standing in eclipse",
                  "Four black wolves came out of the dark at the party in the road",
                  "Boyd explained the turn of the moons and what the eclipse takes",
                  "Its monument woke, fought, and lost its head on the hill",
                  "A beam of red, white and black light rose from inside the hill",
                  "Kakashi and Jasper found three recesses in a cavern beneath it"],
         }),
    dict(slug='the-vingaard-river', name='The Vingaard River', kind='River', region='beyond',
         where='Vogler to Kalaman', last=8, status='Traveled',
         overview="The river that runs past Vogler and on to Kalaman, half a day downstream. It carried Ispin's funeral boat, and later the whole town.",
         links=['place:vogler', 'place:kalaman', 'place:crustdurn-isle', 'npc:lord-soth'],
         records={
             4: ["Took Ispin Greenshield's boat at sunset"],
             7: ["Carried the last boats away from the burning docks; Becklin fell into it"],
             8: ["The dead rose from it as Ashen Vigils, each showing a survivor someone different",
                 "Those pulled under were dragged back from the brink"],
         }),
    dict(slug='tower-of-wayreth', name='The Tower of Wayreth', kind='Arcane stronghold', region='beyond',
         where='Moves', last=None, last_note='Not yet reached', status='Target',
         overview="A moving tower guarded by wizards, said to hold the Orb of Dragonkind. Jasper's task is to steal the Orb. Seredyn's counsel is that getting in may prove easier than getting out.",
         links=['quest:the-orb-of-dragonkind', 'npc:wyhan', 'npc:seredyn', 'fac:the-mages-of-high-sorcery'],
         records={
             2: ["Named in Jasper's dream as the place the Orb of Dragonkind is kept"],
             10: ["Seredyn named Wyhan as the lead to it, and warned about getting out"],
         }),
]

# Charted by name only. A row in the Atlas, no page behind it.
PLACES_UNLINKED = [
    dict(name="Tatina Rookledust's home", kind='Unknown', region='beyond', where="Several days from Kalaman",
         status='Destination',
         blurb="Where the party is headed. Marshal Vendri gave the direction; nothing else about it is known."),
    dict(name='The road to Vogler', kind='Road', region='beyond', where='Solamnia',
         status='Traveled',
         blurb="Where five strangers met in an ambush, burned the scaled dead, and later met an old wizard inside a creature of living sand."),
]

# ---------------------------------------------------------------------------
# THE ARMORY
# ---------------------------------------------------------------------------
# klass: magic-item | keepsake | document   (the tabs)
# kind:  the Type facet

ITEMS = [
    dict(slug='the-emberwake-greataxe', name='The Emberwake Greataxe', sub='Cursed trophy axe',
         klass='magic-item', kind='Weapon', holder='Aratos', holder_ref='pc:aratos',
         origin="Taken from Theros Flametongue at the Vogler docks", last=11, status='Held; cursed',
         overview="A great axe that runs warm to the touch. Aratos took it from Theros Flametongue's body as Vogler burned. It is cursed. A hit in a sparring match woke a rage in him that was not his own, and it took him again on the hill at Bracken Hollow. He cannot hand it away or set it down, and other weapons now sit wrong in his hand. It went cold once, at the reliquary, when he chose stillness.",
         links=['pc:aratos', 'npc:theros-flametongue', 'npc:roberto', 'quest:the-emberwakes-curse',
                'place:the-reliquary-of-sir-cthondor', 'place:bracken-hollow',
                'quest:the-leviathan-axe'],
         records={
             7: ["Carried into Vogler, flaming, by Theros Flametongue",
                 "Taken still warm from his body by Aratos"],
             8: ["Taken up by Aratos on the river to Kalaman"],
             9: ["Drawn in the reliquary as fire and storm rose around Aratos"],
             10: ["Warmed faintly in his hand after the King's warning",
                  "Took him in a sparring match and came down on the squire Roberto",
                  "Would not be handed to Darrett; set down, it drew him back without his deciding to",
                  "Went cold at the reliquary when Aratos chose stillness, and for a moment became another weapon entirely"],
             11: ["Opened a wolf from shoulder to flank at Bracken Hollow; green flame leapt to the next",
                  "Pulled at Aratos on the hill until every other weapon sat wrong in his hand",
                  "Took him when the monument's darkness struck him mid-rage; its embers became full flame",
                  "Went through the monument's neck, the stone running like lava"],
         }),
    dict(slug='horn-of-sir-cthondor', name='The Horn of Sir Cthondor', sub="Horn from Sir Cthondor's statue",
         klass='magic-item', kind='Wondrous Item', holder='Aratos', holder_ref='pc:aratos',
         origin="The reliquary of Sir Cthondor", last=11, status='Held',
         overview="The horn from the central statue in Sir Cthondor's tomb. Blown, it makes no sound a mortal can hear. Spectral warriors answer it: two knights in the tomb, and five on the hill at Bracken Hollow.",
         links=['pc:aratos', 'pc:aeimos', 'npc:sir-cthondor', 'place:the-reliquary-of-sir-cthondor',
                'fac:the-knights-radiant', 'place:bracken-hollow'],
         records={
             9: ["Sir Cthondor's freed spirit blew a spectral horn of his own and sent the risen knights back to rest",
                 "Blown by Aeimos; two spectral knights answered",
                 "Left with Aratos when Aeimos slipped away"],
             11: ["Blown by Aratos on the hill at Bracken Hollow; five spectral warriors answered",
                  "They dragged the fallen clear and struck the red ring dark",
                  "They closed in a ring around Aratos when he fell"],
         }),
    dict(slug='ispins-green-shield', name="Ispin's Green Shield", sub='Shield of a legend',
         klass='keepsake', kind='Shield', holder='Roshi', holder_ref='pc:roshi',
         origin="Ispin Greenshield, by way of Becklin", last=5, status='Held',
         overview="The green shield Ispin Greenshield carried through a life of impossible stories. He meant it to pass on. When Roshi took it, it felt as though the shield had come home.",
         links=['pc:roshi', 'npc:ispin-greenshield', 'npc:becklin-uth-viharin', 'place:thornwall-keep'],
         records={
             4: ["Offered to Roshi at the Brass Crab; Fizban insisted it belonged with someone still willing to stand in front of danger",
                 "Given to her by Becklin at Thornwall Keep the next morning",
                 "Roshi ducked behind it as the half-ogre fell"],
             5: ["Kept near her among the wounded; Ispin's presence felt close"],
         }),
    dict(slug='moon-touched-sword', name='Moon-Touched Sword', sub='Blade from beneath the isle',
         klass='magic-item', kind='Weapon', holder='Roshi', holder_ref='pc:roshi',
         origin="The cavern beneath Crustdurn Isle", last=11, status='Held',
         overview="A moon-touched sword found in the cavern beneath Crustdurn Isle, among what had been dragged or offered to the beast there.",
         links=['pc:roshi', 'place:crustdurn-isle', 'quest:the-vanishing-fish', 'place:bracken-hollow'],
         records={
             3: ["Recovered from the cavern beneath Crustdurn Isle"],
             4: ["Carried by Roshi at High Hill, where her blade lit with divine fire against the half-ogre"],
             11: ["Hummed in the light of the white moon and flashed with divine fire against the monument"],
         }),
    dict(slug='winged-boots', name='Winged Boots', sub='Boots that carry their wearer into the air',
         klass='magic-item', kind='Wondrous Item', holder='Jasper', holder_ref='pc:jasper',
         origin="Bought from Old Man Jenkins in Vogler", last=9, status='Held',
         overview="A pair of winged boots Jasper bought from Old Man Jenkins with the party's shared gold, and later defended as a slick deal.",
         links=['pc:jasper', 'npc:finbar'],
         records={
             4: ["Sold to Jasper at General Goods",
                 "Worn by Kakashi over the mock battle at High Hill"],
             7: ["Carried Jasper over the docks, where he saw that the dragon was a machine"],
             9: ["Let Jasper glide down into the tomb and fire from the shadows"],
         }),
    dict(slug='leeching-arrows', name='Leeching Arrows', sub='Arrows that draw life from their target',
         klass='magic-item', kind='Ammunition', holder='Jasper', holder_ref='pc:jasper',
         origin="Given by Old Man Jenkins", last=11, status='Held',
         overview="Special arrows meant to leech life from whatever they strike. Jenkins handed them over, grudgingly, when Jasper chose to stay and defend Vogler.",
         links=['pc:jasper', 'npc:finbar'],
         records={
             5: ["Given to Jasper along with two healing potions"],
             6: ["One used on a surviving foe on the cliffside"],
             11: ["One loosed at the monument; the dried leech came alive in flight and bored into the stone"],
         }),
    dict(slug='dragons-eye-coin', name="The Dragon's Eye Coin", sub="Mark of the guild",
         klass='magic-item', kind='Wondrous Item', holder='Jasper', holder_ref='pc:jasper',
         origin="The Dragon's Eye", last=5, status='Held; binding',
         overview="The coin by which the Dragon's Eye marked and bound Jasper: a deadly thing. It can also lend its bearer another face.",
         links=['pc:jasper', 'npc:lucky', 'fac:the-dragons-eye', 'quest:the-orb-of-dragonkind'],
         records={
             2: ["Remembered in Jasper's dream of the guild that marked him"],
             4: ["Explained, along with the guild and the task, by Old Man Jenkins"],
             5: ["Used to pass as a Red Army guard at the edge of the camp"],
         }),
    dict(slug='boilerdrake-heart', name='Boilerdrake Heart', sub='Fire gem from the war machine',
         klass='magic-item', kind='Gem', holder='Kakashi', holder_ref='pc:kakashi',
         origin="The wreck of the mechanical dragon", last=9, status='Held; attuned',
         overview="A hot, glowing gem pulled from the wreckage of the mechanical dragon that burned Vogler. It was the source of the machine's fire.",
         links=['pc:kakashi', 'fac:the-red-dragon-army', 'place:vogler', 'quest:the-first-mission'],
         records={
             7: ["Pulled from the dragon machine's wreck by Kakashi"],
             8: ["Attuned on the river"],
             9: ["Forced beyond its limits to add fire to his lightning against the wraith"],
         }),
    dict(slug='moon-marked-spellbook', name='Moon-Marked Spellbook', sub='Reward of the mage trial',
         klass='magic-item', kind='Wondrous Item', holder='Kakashi', holder_ref='pc:kakashi',
         origin="The mage trial", last=1, status='Held',
         overview="A spellbook marked with the moons, given to Kakashi and Jasper for passing the trial together.",
         links=['pc:kakashi', 'pc:jasper', 'fac:the-mages-of-high-sorcery'],
         records={
             1: ["Awarded when Kakashi and Jasper passed the trial through caution and cleverness"],
         }),
    dict(slug='periapt-from-the-cliffside', name='Periapt from the Cliffside', sub='Amulet that holds off death',
         klass='magic-item', kind='Wondrous Item', holder='Roshi', holder_ref='pc:roshi',
         origin="Taken from the Red Army's fallen at Vogler", last=11, status='Worn',
         overview="A magical amulet found on the dead messenger and his cliffside watchers. Identified as a periapt that can preserve its wearer from death when they fall.",
         links=['place:vogler', 'pc:roshi', 'place:bracken-hollow'],
         records={
             6: ["Found among the fallen with a ring, two healing potions and gold"],
             11: ["Worn by Roshi; held her from death when the moons' light struck her down"],
         }),
    dict(slug='blue-gemmed-ring', name='Blue-Gemmed Ring', sub='Ring of protective magic',
         klass='magic-item', kind='Ring', holder='The Embers', holder_ref=None,
         origin="Taken from the Red Army's fallen at Vogler", last=6, status='Held',
         overview="A ring set with a blue gem, found on the dead messenger and his cliffside watchers. It offers protective magic to whoever wears it.",
         links=['place:vogler'],
         records={
             6: ["Found among the fallen alongside the periapt"],
         }),
    dict(slug='armor-of-bone', name='Armor of Bone', sub="The necromancer's armor",
         klass='magic-item', kind='Armor', holder='The Embers', holder_ref=None,
         origin="The necromancer in the reliquary", last=9, status='Held',
         overview="An intricate armor of bone, heavy with necrotic energy, taken from the body of the necromancer who served Lord Soth.",
         links=['place:the-reliquary-of-sir-cthondor', 'npc:lord-soth'],
         records={
             9: ["Taken from the necromancer's body with a handful of gold"],
         }),
    dict(slug='storm-charged-gauntlets', name='Storm-Charged Gauntlets', sub="Aeimos's gauntlets",
         klass='magic-item', kind='Weapon', holder='Aeimos', holder_ref='pc:aeimos',
         origin="Unknown", last=9, status='Held',
         overview="The gauntlets Aeimos fights with. Activated, they strike with lightning, even from a distance.",
         links=['pc:aeimos'],
         records={
             9: ["Battered a risen knight with lightning from across the tomb"],
         }),
    dict(slug='divine-pendant', name='Divine Pendant', sub='A gift that came with the finch',
         klass='keepsake', kind='Wondrous Item', holder='Mayriel', holder_ref='pc:mayriel',
         origin="Appeared in Vogler with the golden finch", last=4, status='Held',
         overview="A pendant Mayriel woke to in Vogler alongside a golden finch, meant to aid her divine path.",
         links=['pc:mayriel', 'npc:sunscale'],
         records={
             4: ["Found on waking in Mayor Raven's home, with the finch"],
         }),
    dict(slug='mayriels-signet-ring', name="Mayriel's Signet Ring", sub='Family signet, pledged to Paladine',
         klass='keepsake', kind='Ring', holder='Mayriel', holder_ref='pc:mayriel',
         origin="Her family", last=7, status='Pledged',
         overview="Mayriel's family signet ring. On the burning docks of Vogler she offered it to Paladine, with a promise of obedience when the god one day asks something of her. It glowed with holy light.",
         links=['pc:mayriel', 'npc:sunscale'],
         records={
             7: ["Offered to Paladine; it glowed, and the golden finch's radiance restored the party"],
         }),
    dict(slug='becklins-armor', name="Becklin's Armor", sub='Solamnic armor',
         klass='keepsake', kind='Armor', holder='Darrett Highwater', holder_ref='npc:darrett-highwater',
         origin="Becklin Uth Viharin", last=10, status='Worn by Darrett',
         overview="The Solamnic armor of Becklin Uth Viharin. Darrett would not take it at first. He wears it now as a promise to grow into the burden.",
         links=['npc:becklin-uth-viharin', 'npc:darrett-highwater'],
         records={
             8: ["Offered to Darrett on the river by Roshi and refused",
                 "Accepted and put on at the gates of Kalaman"],
             10: ["Polished and unscathed on Darrett as he headed to training before dawn"],
         }),
    dict(slug='fizbans-stew-recipe', name="Fizban's Stew Recipe", sub="Ispin's campfire stew, in Fizban's hand",
         klass='document', kind='Document', holder='Burned away', holder_ref=None,
         origin="Dropped by Fizban at the refugee camp", last=10, status='Spent',
         overview="A scrap of parchment recording Ispin Greenshield's campfire stew, each ingredient in an absurd quantity. The numbers were a cipher pointing to words in the recipe itself, and the words were an incantation. Spoken aloud, it taught all five of the party the Green Flame Blade and burned to nothing.",
         links=['npc:fizban', 'npc:wyhan', 'npc:ispin-greenshield', 'quest:fizbans-recipe', 'pc:roshi', 'pc:kakashi'],
         records={
             10: ["Fell from where Fizban had been sitting; Roshi picked it up",
                  "Kakashi suspected the quantities were not measurements",
                  "Wyhan confirmed the cipher and named the spell",
                  "Roshi spoke it: blade made bright, let emerald fire arise, strike one foe, then leap before their eyes",
                  "Green flame touched each of the five and the parchment burned away"],
         }),
]

ITEM_TABS = [
    ('all', 'All Items'),
    ('magic-item', 'Magic Items'),
    ('keepsake', 'Keepsakes'),
    ('document', 'Documents'),
]

# ---------------------------------------------------------------------------
# WAR INTEL
# ---------------------------------------------------------------------------
# band: threat | order | guild   (grouping on the index)

FACTIONS = [
    dict(slug='takhisis-the-shadow-queen', name='Takhisis, the Dragon Queen', band='threat',
         kind='The power behind the invasion', relation='Overarching enemy', last=8, status='Active',
         aliases=['Shadow Queen', 'Dragon Queen'],
         overview="Takhisis is the queen the enemy serves. Her soldiers call her the Shadow Queen and the Dragon Queen and say they are reclaiming the realm for her. Mayriel has seen her in vision as a horned woman in dark regalia who unfolds into a five-headed dragon.",
         links=['fac:the-red-dragon-army', 'fac:draconians', 'pc:mayriel', 'quest:the-sword-of-the-dragon-queen'],
         records={
             1: ["Named by a captured draconian: the realm reclaimed for its queen, the east already fallen, the shadow coming fast"],
             3: ["Seen by Mayriel commanding slaughter beneath the moons, then as a five-headed dragon; platinum fire rose to shield her"],
             6: ["Vogler's surrender was demanded in her name"],
             7: ["A voice called after the boats: you will not escape the flames of the Dragon Queen"],
             8: ["Appeared to Mayriel in the river and promised that her sword would find her"],
         }),
    dict(slug='the-red-dragon-army', name='The Red Dragon Army', band='threat',
         kind='Enemy army', relation='Primary enemy force', last=8, status='Active',
         aliases=['Red Army'],
         overview="An invading army serving the Dragon Queen, organized and well supplied. It fields armored soldiers, draconians and a war machine built like a dragon, and it paid mercenaries to turn on Vogler. It burned Vogler and is pressing other villages too.",
         links=['fac:takhisis-the-shadow-queen', 'fac:draconians', 'npc:theros-flametongue',
                'npc:the-charred-swordswoman', 'npc:gragonis', 'place:vogler', 'item:boilerdrake-heart',
                'quest:the-first-mission', 'quest:the-betrayal-at-high-hill'],
         records={
             1: ["Scaled soldiers ambushed a caravan on the road to Vogler, in the name of a queen"],
             4: ["A note on the dead half-ogre read: For your services from the Red Army"],
             5: ["One to two hundred soldiers found camped beyond the woods, with larger, bestial figures on patrol"],
             6: ["A rider in black and red delivered its terms: open the doors by sunset or face slaughter"],
             7: ["Burned Vogler with a mechanical dragon crewed from within and powered by a glowing gem",
                 "Raised Theros Flametongue again by fire"],
             8: ["Governor Miat confirmed other villages have come under attack"],
         }),
    dict(slug='draconians', name='Draconians', band='threat',
         kind='Creature', relation="Soldiers of the Dragon Queen", last=7, status='Active',
         overview="Reptilian humanoids with scaled hides, sharp claws and brutal weapons. They speak Draconic and fight in coordination. A captured one killed itself sooner than talk. Their bodies decay with unnatural speed, and a red one exploded when it was killed.",
         links=['fac:the-red-dragon-army', 'fac:takhisis-the-shadow-queen'],
         records={
             1: ["Ambushed a caravan on the road; one knight fell with an arrow in his throat",
                 "A captive spoke of its queen, then choked itself to death rather than say more",
                 "The party burned the bodies before the decay could spread"],
             5: ["Larger, bestial figures like them seen on patrol at the Red Army camp"],
             7: ["Fought on the Vogler waterfront",
                 "A red one, shot by Than, convulsed and exploded as it died"],
         }),
    dict(slug='the-knights-of-solamnia', name='The Knights of Solamnia', band='order',
         kind='Knightly order', relation='Sought as allies', last=9, status='Active',
         overview="The knighthood Aratos set out to reach and warn of what his vision showed. Becklin Uth Viharin was a retired knight of the order. Lord Soth was once one of its most celebrated knights and fell into disgrace. His statue still stands in Kalaman's courtyard.",
         links=['npc:becklin-uth-viharin', 'npc:lord-soth', 'npc:darrett-highwater', 'pc:aratos',
                'fac:the-knights-radiant', 'place:kalaman'],
         records={
             1: ["Knights died in the ambush on the road to Vogler"],
             2: ["The dead knights carried signs that they had been investigating attacks in the region"],
             3: ["Becklin, a retired knight, heard Aratos's warning in Vogler"],
             7: ["Becklin Uth Viharin fell holding the docks"],
             8: ["Statues of knights once honored stand in Kalaman's courtyard, Lord Soth among them"],
             9: ["Shown in the reliquary murals standing with the Knights Radiant beneath a floating city"],
         }),
    dict(slug='the-knights-radiant', name='The Knights Radiant', band='order',
         kind='Ancient knightly order', relation="Aratos's and Aeimos's heritage", last=10, status='Active',
         overview="An order tied to hidden reliquaries. Its symbol is a sword. The door of its reliquary outside Kalaman asked for oaths and answered with the virtues of knighthood: Valor, Resolve, Foresight. Aratos and Aeimos have been named children of Cathan by one of its dead. Its tombs and legacies are being targeted by Lord Soth.",
         links=['pc:aratos', 'pc:aeimos', 'npc:sir-cthondor', 'npc:lord-soth',
                'place:the-reliquary-of-sir-cthondor', 'item:horn-of-sir-cthondor',
                'quest:lord-soths-corruption', 'quest:the-leviathan-axe', 'fac:the-knights-of-solamnia'],
         records={
             8: ["Aratos identified himself as a Knight Radiant before Kalaman's council; Marshal Vendri acknowledged the title"],
             9: ["A reliquary of the order was found outside Kalaman behind an oath-tested door",
                 "Its murals show the order beside the Knights of Solamnia, then a floating city falling",
                 "Sir Cthondor named Aratos and Aeimos children of Cathan"],
             10: ["Aratos returned to the reliquary to ask its dead for help"],
         }),
    dict(slug='the-mages-of-high-sorcery', name='The Mages of High Sorcery', band='order',
         kind='Order of wizards', relation='Neutral; Kakashi and Jasper are candidates', last=10, status='Active',
         aliases=['High Sorcery', 'White Robes'],
         overview="An order of wizards. Kakashi and Jasper carry its scrolls and are to test for its White Robes. Its towers are built to keep powerful magical things safe from those who would misuse them. In Kalaman its business runs through Wyhan, an apothecary.",
         links=['npc:wyhan', 'pc:kakashi', 'pc:jasper', 'place:tower-of-wayreth', 'quest:the-white-robes',
                'quest:kakashis-tower-vision', 'item:moon-marked-spellbook'],
         records={
             1: ["Kakashi and Jasper passed a trial of invisible passages, hidden writing and a too-inviting key"],
             8: ["Wyhan read their scrolls and set both to test for the White Robes"],
             10: ["Kakashi saw an elven woman warding a round room of relics, the kind of room its towers are built for",
                  "Seredyn warned that the wizards guarding Wayreth are more secretive than the guild itself"],
         }),
    dict(slug='the-dragons-eye', name="The Dragon's Eye", band='guild',
         kind="Thieves' guild", relation="Jasper's entanglement", last=10, status='Active',
         overview="A secretive thieves' guild that marks and binds its members with a coin. Its phrase is: none shall hide from the Dragon's Eye. Its guild master is Lucky Leppomanto. It keeps a hidden branch in Kalaman behind the sign of Peller's Provisions.",
         links=['pc:jasper', 'npc:lucky', 'npc:seredyn', 'npc:finbar', 'item:dragons-eye-coin',
                'quest:the-orb-of-dragonkind', 'place:kalaman'],
         records={
             2: ["Jasper dreamed of the guild that marked him and the task it set"],
             4: ["Old Man Jenkins made contact in Vogler and gave the phrase"],
             8: ["One of its agents left Kalaman's council chamber under an illusion"],
             9: ["A note in Thieves' Cant reached Jasper at the camp: We need to talk"],
             10: ["Its Kalaman branch received Jasper at Finn's Bar",
                  "Seredyn made clear that Lucky had told him nothing"],
         }),
]

FACTION_BANDS = [
    ('threat', 'The Enemy', 'Who is marching, and in whose name.'),
    ('order', 'Orders', 'Knights and wizards, living and lost.'),
    ('guild', 'Guilds', 'Those who work out of sight.'),
]

# ---------------------------------------------------------------------------
# THE QUEST BOARD
# ---------------------------------------------------------------------------
# kind:   quest | thread
# status: open | closed
# parent: slug of the quest this hangs under (shown indented on the board)
# objectives: (text, done)

QUESTS = [
    dict(slug='the-spell-over-bracken-hollow', name='The Spell Over Bracken Hollow', kind='quest', status='open', last=11,
         overview=[
             "Bracken Hollow has been shut for about a month. Nobody can walk out of it, the three moons hang over it in eclipse, and each eclipse takes one of its people. The Embers walked in and are shut in with them.",
             "As he fell on the hill, Kakashi saw a lattice of spellwork laid over the whole village, the true sun beyond it, and three knots in the weave. The monument's three rings were receivers for that working. With all three darkened it could be killed, but what is bound this way can come back unless the binding itself is undone.",
             "Beneath the hill is a closed cavern with three recesses. That is where the spell is bound. Three rings, three recesses, three phases: three things are needed there to break it, and they are somewhere in the village.",
         ],
         objectives=[("Bring down the monument on the hill", True),
                     ("Find where the spell is bound", True),
                     ("Find the three things the spell needs, somewhere in the village", False),
                     ("Break the spell before the next eclipse", False)],
         links=['place:bracken-hollow', 'npc:sergeant-boyd', 'npc:corvin', 'npc:ked', 'pc:kakashi',
                'quest:the-ones-sent-up-the-hill', 'quest:the-first-mission'],
         records={
             11: ["The party walked in under an eclipse of the three moons. The last was a month ago, and it should come once a year",
                  "Boyd explained the white, red and black moons and the hour of the eclipse",
                  "Kakashi saw the lattice over the village and its three knots",
                  "The black, white and red rings were struck dark, and Aratos took the monument's head",
                  "Light rose from inside the hill; a crevice led down to a cavern with three recesses",
                  "A little less than a day remains until the next eclipse"],
         }),
    dict(slug='the-first-mission', name='The First Mission', kind='quest', status='open',
         giver='npc:marshal-vendri', last=11,
         overview="Marshal Vendri has sent the Embers to find a tinkerer named Tatina Rookledust, several days' travel from Kalaman. The mechanical dragon that burned Vogler was a remarkable and dangerous piece of engineering, and he believes she can shed light on how it was built and who is behind it.",
         objectives=[("Accept the mission from Marshal Vendri", True),
                     ("Reach Tatina Rookledust, several days from Kalaman", False),
                     ("Learn what she knows about the mechanical dragon", False)],
         rewards=["Two healing potions, given at the outset"],
         links=['npc:marshal-vendri', 'npc:darrett-highwater', 'item:boilerdrake-heart',
                'fac:the-red-dragon-army', 'place:kalaman', 'quest:service-to-kalaman',
                'quest:the-spell-over-bracken-hollow'],
         records={
             7: ["The dragon over Vogler proved to be a machine, crewed from within"],
             10: ["Vendri named the tinkerer and gave the direction",
                  "Most of his soldiers are committed elsewhere; the Embers were the right people for it",
                  "The party left Kalaman as morning stretched toward midday"],
             11: ["Turned aside from the road at Bracken Hollow, where Boyd says no one can leave"],
         }),
    dict(slug='service-to-kalaman', name='Service to Kalaman', kind='quest', status='open',
         giver='npc:governor-miat', last=10,
         overview="Kalaman sheltered the people of Vogler in exchange for the party's aid in its military efforts. Darrett Highwater stands as their proxy, so the Embers serve without being formally conscripted. Missions come from Marshal Vendri.",
         objectives=[("Win refuge for the people of Vogler", True),
                     ("Give Kalaman a name to record the party under", True),
                     ("Carry out the missions Marshal Vendri assigns", False)],
         links=['npc:governor-miat', 'npc:marshal-vendri', 'npc:darrett-highwater', 'place:kalaman',
                'place:the-refugee-camp', 'quest:the-first-mission', 'quest:refuge-for-vogler'],
         records={
             8: ["Governor Miat granted refuge on the condition of service",
                 "Darrett stepped forward as intermediary",
                 "Vendri asked for a name for the record"],
             10: ["Darrett offered again to carry the formal obligation; Vendri accepted",
                  "The party gave its name: the Embers"],
         }),
    dict(slug='the-orb-of-dragonkind', name='The Orb of Dragonkind', kind='quest', status='open',
         giver='npc:lucky', last=10,
         overview="The Dragon's Eye bound Jasper with a deadly coin. Its guild master, Lucky, set the task: find the moving Tower of Wayreth and steal the Orb of Dragonkind. In the river's apparitions, Lucky warned that time is running out.",
         objectives=[("Make contact with the guild in Kalaman", True),
                     ("Approach Wyhan about reaching the Tower of Wayreth", False),
                     ("Find a way out of the tower as well as a way in", False),
                     ("Steal the Orb of Dragonkind", False)],
         links=['pc:jasper', 'npc:lucky', 'npc:seredyn', 'npc:finbar', 'npc:wyhan', 'item:dragons-eye-coin',
                'place:tower-of-wayreth', 'fac:the-dragons-eye'],
         records={
             2: ["Jasper dreamed of Lucky, the coin and the task"],
             4: ["Old Man Jenkins explained more of the guild and the tower"],
             8: ["Lucky appeared in the river: time is running out"],
             9: ["A note in Thieves' Cant: We need to talk"],
             10: ["Seredyn named Wyhan as the best lead to the tower",
                  "He warned that getting in might prove easier than getting out"],
         }),
    dict(slug='finbar', name='Finbar', kind='thread', status='open', parent='the-orb-of-dragonkind', last=10,
         overview="Old Man Jenkins of Vogler was a disguise. His name is Finbar, he can turn invisible, and he belongs to the Dragon's Eye. Jasper saw through the disguise in Vogler and was given the name. The rest of the party still does not know. He gave Jasper potions and leeching arrows in Vogler, and took him to Seredyn in Kalaman.",
         links=['npc:finbar', 'pc:jasper', 'npc:seredyn'],
         records={
             5: ["Gave Jasper potions and leeching arrows as he packed to leave Vogler"],
             7: ["Boarded the boat unseen"],
             10: ["Showed his own face and brought Jasper to Finn's Bar"],
         }),
    dict(slug='the-white-robes', name='The Test for the White Robes', kind='quest', status='open',
         giver='npc:wyhan', last=10,
         overview="Wyhan read the High Sorcery scrolls Kakashi and Jasper carried and determined that both would test for the White Robes. The practical exam was set several weeks out.",
         objectives=[("Present the scrolls to Wyhan", True),
                     ("Sit the practical exam", False)],
         links=['pc:kakashi', 'pc:jasper', 'npc:wyhan', 'fac:the-mages-of-high-sorcery'],
         records={
             1: ["Kakashi and Jasper passed the first trial and were pointed onward"],
             8: ["Wyhan set both on the path of the White Robes"],
             10: ["Wyhan received Kakashi with dry tolerance and sold him components"],
         }),
    dict(slug='wyhans-list', name="Wyhan's List", kind='quest', status='open', giver='npc:wyhan', last=11,
         overview="A note from Wyhan reached Kakashi on the road with a list of things to gather. Three were easy to come by. The fourth, frostlace, is the one she wants: a small pale flower that comes into bloom with the cold. In Bracken Hollow, Boyd says the farmer Gribb Brack would be the one to ask.",
         objectives=[("Willowbark, from any stream", True),
                     ("Pine resin", True),
                     ("Graveyard moss", True),
                     ("Frostlace", False),
                     ("Bring it all back to Wyhan in Kalaman", False)],
         links=['npc:wyhan', 'pc:kakashi', 'place:bracken-hollow', 'place:kalaman', 'npc:sergeant-boyd'],
         records={
             11: ["Willowbark cut from the roots at a creek outside Bracken Hollow",
                  "Resin tapped from a stand of pines on the way in",
                  "Moss taken from the headstones in the graveyard",
                  "Roshi knew frostlace as a pale flower that blooms with the cold",
                  "Boyd pointed to Gribb Brack, and offered to take the party there under the white moon"],
         }),
    dict(slug='the-leviathan-axe', name='The Leviathan Axe', kind='quest', status='open', last=11,
         overview=[
             "Aratos has made his choice. Shown a tree that burns on one side and is glazed with frost on the other, and offered blades bound in fury or an axe marked by cold restraint, he reached for the cold.",
             "At the reliquary the Emberwake took the shape of the axe from his vision, the Leviathan Axe, for a moment. Then it turned back.",
             "The King, one of the ancestral spirits who appear when he rages, has come to him twice. The first time was a warning: the same blood, the same weakness. The second time he told Aratos to test his resolve, and the axe's fire rose at once. Aratos held.",
             "At Bracken Hollow he did not hold. The fury took him in the middle of a fight, and Roshi had to bring him down.",
         ],
         objectives=[("Choose between fury and restraint", True),
                     ("Hold to that choice when the axe's fire rises", False)],
         links=['pc:aratos', 'item:the-emberwake-greataxe', 'npc:lord-soth', 'npc:theros-flametongue',
                'place:the-reliquary-of-sir-cthondor', 'fac:the-knights-radiant',
                'quest:the-emberwakes-curse', 'place:bracken-hollow'],
         records={
             5: ["A stern, ancient figure at the foot of a tree split between flame and frost offered blades bound in fury, or an axe marked by cold restraint: choose, boy. The gods are watching"],
             6: ["On the cliff above Vogler his axe ran cold, and a voice demanded he prove himself"],
             7: ["The same cold voice came as he threw the javelin that brought down the dragon machine",
                 "He took Theros Flametongue's still-warm axe as a trophy"],
             8: ["Cathan Twice-Born and Lord Soth stood in the river as opposing shadows of legacy and choice: he would have to choose soon"],
             9: ["Spectral figures stood with him in the reliquary: a towering bald warrior, a kingly hooded figure, and a slim blue-hued guardian with a spear"],
             10: ["The tree appeared in the campfire, a black rose at its base; the King warned him: the same blood, the same weakness. Don't let it take you",
                  "At the reliquary the King laid a hand on his shoulder: you must test your resolve",
                  "He reached for the cold side of the tree. The flames died, and for a moment the Emberwake was the weapon from his vision",
                  "He thinks he can do it. He will need his companions when he cannot"],
             11: ["On the hill at Bracken Hollow the Emberwake pulled at him, and every other weapon sat wrong in his hand",
                  "Struck by the monument's darkness while raging, he lost himself to a fury that was not his own",
                  "Roshi had to drop him before he turned on his friends"],
         }),

    # -- threads --
    dict(slug='the-ones-sent-up-the-hill', name='The Ones Sent Up the Hill', kind='thread', status='open',
         parent='the-spell-over-bracken-hollow', last=11,
         overview="Each eclipse takes one of the black-touched. Corvin says the village has a choice in it: another of the black-touched can be sent up the hill in the chosen one's place, and that one is taken. He holds that some people's skills are still needed. Boyd says no one should have to make that choice for another. On the hill Corvin kept Ked from leaving at dagger-point, knocked him senseless, and ran. Ked and Aratos had both been marked with the black, and the eclipse was not yet over.",
         links=['npc:corvin', 'npc:ked', 'npc:sergeant-boyd', 'pc:aratos', 'place:bracken-hollow'],
         records={
             11: ["Corvin told the party what Boyd had left out",
                  "Jasper judged that Corvin wanted Boyd out of the house and was working toward something",
                  "The monument marked Aratos black when he challenged it",
                  "Corvin held Ked on the hill with a dagger, then struck him down and fled",
                  "Whether the eclipse took anyone this time is not yet known"],
         }),
    dict(slug='the-emberwakes-curse', name="The Emberwake's Curse", kind='thread', status='open',
         parent='the-leviathan-axe', last=11,
         overview="The axe Aratos took from Theros Flametongue is cursed. A real blow can wake a rage in him that feels like his own but comes from outside, and he can neither give the weapon away nor leave it behind. Other weapons sit wrong in his hand. Cold stillness quiets it. Kakashi judges that breaking the hold would take divine magic, the kind Roshi and Mayriel carry.",
         links=['pc:aratos', 'item:the-emberwake-greataxe', 'npc:roberto', 'pc:roshi', 'pc:mayriel',
                'place:the-reliquary-of-sir-cthondor', 'npc:marshal-vendri'],
         records={
             10: ["The axe took him in the training yard and nearly killed Roberto",
                  "He could not hand it to Darrett or set it down",
                  "At the reliquary he reached for the cold side of the tree and the flames died",
                  "Marshal Vendri promised to look into what remedies Kalaman has"],
             11: ["Any weapon but the Emberwake now sits wrong in his hand",
                  "Harm taken while raging woke the fury: he took the monument's head and stayed lost to it",
                  "Roshi struck him senseless before he could turn on the party"],
         }),
    dict(slug='the-sword-of-the-dragon-queen', name='The Sword of the Dragon Queen', kind='thread', status='open', last=10,
         overview="The Dragon Queen has told Mayriel that her sword will find her. Mayriel does not know whether that means a blade or the one who carries it. She has had no vision in some time, and the silence makes her suspicious.",
         links=['pc:mayriel', 'fac:takhisis-the-shadow-queen', 'item:mayriels-signet-ring'],
         records={
             3: ["A horned woman in dark regalia spoke against the followers of Paladine"],
             7: ["Mayriel pledged Paladine her signet and her obedience"],
             8: ["The Dragon Queen in the river: her sword will find her"],
             10: ["No vision in some time; the silence feels suspicious"],
         }),
    dict(slug='kakashis-tower-vision', name="Kakashi's Tower Vision", kind='thread', status='open', last=10,
         overview="On watch, Kakashi saw three full moons in a pail of water when none were in the sky, and in place of his reflection a frightened elven woman. She went down a circular stair to a room of altars, each holding something that pulsed with magic, and began to ward them. Then she looked at him and said: you have to fight. Keep them safe.",
         links=['pc:kakashi', 'fac:the-mages-of-high-sorcery'],
         records={
             2: ["The moons aligned on his watch; voices said he was not strong enough, not yet"],
             10: ["Fire erupted, and the vision ended",
                  "He knows High Sorcery builds its towers to guard such things"],
         }),
    dict(slug='kakashis-buried-past', name="Kakashi's Buried Past", kind='thread', status='open', last=7,
         overview="When the dragon machine's last explosion dropped him, Kakashi remembered a village burning and people crying. It is a past he had tried to bury.",
         links=['pc:kakashi'],
         records={
             7: ["The memory surfaced in the wreck at Vogler's docks"],
         }),
    dict(slug='lord-soths-corruption', name="Lord Soth's Corruption of Knights", kind='thread', status='open', last=9,
         overview="Lord Soth seeks to corrupt all knights: their image, their legacies, and the memory of what they were. He means to continue until his curse is lifted. A necromancer in his service was found at work in the reliquary of Sir Cthondor. Aeimos has left to find the other tombs Soth may reach for.",
         links=['npc:lord-soth', 'pc:aeimos', 'pc:aratos', 'npc:the-pale-woman', 'npc:sir-cthondor',
                'place:the-reliquary-of-sir-cthondor', 'fac:the-knights-radiant'],
         records={
             8: ["Aratos saw Lord Soth in the river, standing opposite Cathan Twice-Born"],
             9: ["His necromancer raised Sir Cthondor as a wraith over a black rose",
                 "The pale woman told Aeimos what Soth wants and pointed him onward"],
         }),
    dict(slug='theros-flametongue', name='Theros Flametongue', kind='thread', status='open', last=7,
         overview="Mayriel killed Theros Flametongue on the docks of Vogler. As the boats pulled away, a figure stood over his body, flame passed across him, and he rose. Aratos is carrying his axe.",
         links=['npc:theros-flametongue', 'pc:aratos', 'item:the-emberwake-greataxe', 'fac:the-red-dragon-army'],
         records={
             7: ["Killed, then raised by fire as Vogler burned"],
         }),
    dict(slug='the-bakarises', name='The Bakarises', kind='thread', status='open', last=8,
         overview="Lord Bakaris forced his way into Vogler's planning and then reached Kalaman's council ahead of the refugees. His son mocked Ispin's funeral and dismissed the refugees as fishfolk. The party does not trust either of them. Governor Miat does not seem moved by them.",
         links=['npc:bakaris-the-elder', 'npc:bakaris-the-younger', 'npc:governor-miat', 'place:kalaman'],
         records={
             6: ["The Elder preferred a sealed letter to a ride for help"],
             8: ["Both suggested more might have been done for Vogler",
                 "The Younger blocked the council door; the Elder tried to twist the hearing"],
         }),

    # -- closed --
    dict(slug='the-vanishing-fish', name='The Vanishing Fish of Vogler', kind='quest', status='closed', last=3,
         outcome="The beast beneath Crustdurn Isle was killed.",
         overview="Vogler's fishermen reported poor catches and strange sounds from the river. The trail led to an island the locals avoided.",
         objectives=[("Find what is taking the fish", True), ("Deal with it", True)],
         links=['place:crustdurn-isle', 'place:vogler', 'npc:becklin-uth-viharin', 'item:moon-touched-sword'],
         records={
             2: ["The same rumor from different mouths: the fish were vanishing"],
             3: ["A tentacled frog-beast in the cavern beneath Crustdurn Isle swallowed Roshi and was brought down",
                 "Aeimos cut out its tongue for proof"],
         }),
    dict(slug='the-betrayal-at-high-hill', name='The Betrayal at High Hill', kind='quest', status='closed', last=5,
         outcome="Gragonis took Red Army gold. The army behind him was found.",
         overview="The Kingfisher Festival's mock battle became a massacre when part of Cudgel's company struck with real steel. Someone paid them.",
         objectives=[("Survive the ambush", True), ("Learn who paid the mercenaries", True),
                     ("Find out what waits beyond the woods", True)],
         links=['npc:cudgel-ironsmile', 'npc:gragonis', 'fac:the-red-dragon-army', 'place:vogler'],
         records={
             4: ["A note on the half-ogre: For your services from the Red Army"],
             5: ["The captive named Cudgel's lieutenant, Gragonis",
                 "Jasper counted one to two hundred soldiers in the woods"],
         }),
    dict(slug='the-evacuation-of-vogler', name='The Evacuation of Vogler', kind='quest', status='closed', last=7,
         giver='npc:becklin-uth-viharin',
         outcome="The people got out. The town, Becklin and Cudgel did not.",
         overview="The Red Dragon Army gave Vogler until sunset. Becklin and Cudgel took the front line and gave the party the villagers.",
         objectives=[("Buy time: get Jeyev out past the messenger", True),
                     ("Get the boats repaired and loaded", True),
                     ("See the people of Vogler onto the river", True)],
         links=['npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'npc:mayor-raven', 'npc:than',
                'place:vogler', 'place:the-vingaard-river', 'fac:the-red-dragon-army'],
         records={
             6: ["The messenger and his watchers were killed and Jeyev rode",
                 "Becklin gave the party their charge"],
             7: ["The last boats left as the dragon machine burned the docks",
                 "Becklin fell; Cudgel was thrown through a building"],
         }),
    dict(slug='refuge-for-vogler', name='Refuge for Vogler', kind='quest', status='closed', last=9,
         giver='npc:mayor-raven',
         outcome="Refuge granted, in exchange for the party's service.",
         overview="Mayor Raven asked the party to speak before Kalaman's council on behalf of her people.",
         objectives=[("Bring the refugees down the river alive", True),
                     ("Get a hearing before the council", True),
                     ("Win shelter for the people of Vogler", True)],
         links=['npc:mayor-raven', 'npc:governor-miat', 'npc:darrett-highwater', 'place:kalaman',
                'place:the-refugee-camp', 'quest:service-to-kalaman'],
         records={
             8: ["The Ashen Vigils were broken on the river",
                 "Governor Miat granted refuge; Darrett stood as intermediary"],
             9: ["Raven named the party honorary Voglerans"],
         }),
    dict(slug='meat-for-ispins-stew', name="Meat for Ispin's Stew", kind='quest', status='closed', last=9,
         giver='npc:fizban',
         outcome="A bear, eventually. Also a reliquary, a wraith and a horn.",
         overview="Fizban claimed to know one of Ispin's old recipes and needed meat. Bear, deer, hare, anything the wilds might offer.",
         objectives=[("Hunt something for the pot", True)],
         links=['npc:fizban', 'npc:sir-cthondor', 'place:the-reliquary-of-sir-cthondor',
                'place:the-refugee-camp', 'item:horn-of-sir-cthondor'],
         records={
             9: ["The bear trail led to a cave with a blue glow",
                 "The party found a bear after all and brought it back to camp"],
         }),
    dict(slug='fizbans-recipe', name="Fizban's Recipe", kind='quest', status='closed', last=10,
         outcome="All five learned the Green Flame Blade.",
         overview="A recipe for stew with quantities too absurd to be quantities.",
         objectives=[("Work out what the numbers mean", True), ("Speak the incantation", True)],
         links=['npc:fizban', 'npc:wyhan', 'item:fizbans-stew-recipe', 'pc:kakashi', 'pc:roshi'],
         records={
             10: ["Kakashi suspected a cipher; Wyhan confirmed it",
                  "Roshi spoke the words and the parchment burned away"],
         }),
]

# ---------------------------------------------------------------------------
# WHERE THE PARTY STANDS  (the command bar and The Road So Far)
# ---------------------------------------------------------------------------

STANDING = dict(
    journey=11,
    position='Bracken Hollow',
    pos_note="shut in, with less than a day until the next eclipse",
    pos_ref='place:bracken-hollow',
    pos_blurb="The Embers are inside a village no one can walk out of. The monument on the hill is down and headless, and a beam of red, white and black light is rising from inside the hill. The eclipse that woke it has not yet ended.",
    outstanding='Find the three things that break the spell',
    consequence="The Emberwake's fury took Aratos in the middle of the fight, and Roshi had to strike him senseless. The monument marked him black before it fell. He lies on the hill, ringed by the horn's spectral warriors. Ked lies senseless nearby. Corvin has run.",
    last_text="A list from Wyhan led the party into Bracken Hollow, shut for a month under three eclipsed moons. Boyd explained the turn of the moons and Corvin the part Boyd left out. On the hill the monument fell once its three rings were darkened. Beneath it is a cavern with three recesses.",
    quests=['the-spell-over-bracken-hollow', 'the-leviathan-axe', 'the-first-mission', 'wyhans-list',
            'the-orb-of-dragonkind', 'the-white-robes', 'service-to-kalaman'],
    met=['npc:sergeant-boyd', 'npc:corvin', 'npc:ked'],   # who mattered in the latest journey
    unanswered=['the-ones-sent-up-the-hill', 'the-emberwakes-curse', 'the-sword-of-the-dragon-queen',
                'kakashis-tower-vision', 'lord-soths-corruption', 'theros-flametongue'],
)

# Names a player might only have heard spoken. Added to the vocabulary the
# search uses to repair a misspelled query. Titles and names from the records
# above are harvested automatically; this list is for everything else.
EXTRA_VOCAB = [
    'Ansalon', 'Krynn', 'Solamnia', 'Solamnic', 'Vingaard', 'Kingfisher', 'Istarian', 'Paladine',
    'Kiri-Jolith', 'Draconic', 'Draconian', 'Leppomanto',
    'Voglerans', 'Jenkins', 'Jeyev', 'Tatina', 'Rookledust', 'Cathan', 'Gertrude', 'Wraith',
    'Necromancer', 'Reliquary', 'Ashen', 'Vigils', 'Orb', 'Dragonkind',
    'Emberwake', 'Boilerdrake', 'Periapt', 'Finn', 'Peller', 'Apothecary',
    'Takhisis', 'Bracken', 'Hollow', 'Frostlace', 'Willowbark', 'Gribb', 'Brack', 'Marigold', 'Boyd', 'Corvin', 'Ked',
    'Eclipse', 'Monument', 'Leviathan',
]
