"""
campaign_world.py - journeys, places, items, factions, quests, and where the
party stands. Same rules as campaign_people.py: player-known framing only.
"""

IMG = 'https://lh3.googleusercontent.com/d/'

CAMPAIGN = dict(
    title='Shadow of the Dragon Queen',
    tagline='Takhisis stirs. Her armies march on Ansalon.',
    kicker='A Dragonlance Campaign',
    party='The Embers',
    scheduler='https://rallly.co/invite/D8kMYvewkWxI',
    playlist='https://www.youtube.com/playlist?list=PLN57h0dwcT5t6izo-CKegvP96QNZyXIDn',
    gate_art=IMG + '1HxtWOhCcRJALSWUbbrUCKNGmLYB8fIPG',
)

FIVE = ['aratos', 'kakashi', 'jasper', 'roshi', 'mayariel']
SIX = FIVE + ['aeimos']

# ---------------------------------------------------------------------------
# JOURNEYS
# ---------------------------------------------------------------------------
# npcs / places / items are (label, ref-or-None). A ref links the chip; None
# leaves it as plain text. The accounts themselves live in _build/journeys/.
# video: a YouTube ID, None if not linked yet, False if the session was not recorded.

JOURNEYS = [
    dict(num=1, title='The Night of the Eye', level=1, where='Road to Vogler', video='lUOB97A9Bl0',
         subtitle="Five strangers meet in an ambush on the road to Vogler.",
         synopsis="Aratos dreams of a scaled army and sets out to warn the knights in Kalaman. Kakashi and Jasper pass the entry exam of the Mages of High Sorcery. Roshi and Mayariel travel to a funeral and are called by old gods at a ruined holy place. All five meet when a caravan is ambushed by scaled, Draconic-speaking soldiers. The one they capture was sent by a Shadow Queen, says the east has fallen, and kills itself.",
         pcs=FIVE,
         npcs=[('Fallen Solamnic knights', None), ('Scaled ambushers', 'fac:draconians')],
         places=[('The Road to Vogler', None), ('The Barb', None), ('An old holy place', None)],
         items=[('Moon-Marked Spellbook', 'item:moon-marked-spellbook')]),
    dict(num=2, title='The Road After Bloodshed', level=1, where='Road to Vogler', video='XiRpDQrTqls',
         subtitle="Bad dreams in the night, and a creature of living sand on the road.",
         synopsis="The party buries the fallen knights, burns the scaled dead and takes what clues the knights carried. In the night Jasper dreams of his guild, a golden canary visits Mayariel, and Kakashi sees the moons merge. On the road they pull an old man out of a creature of living sand. He is Fizban, a green-robed wizard and friend of Ispin. He freezes and shatters the creature, then rides with them to Vogler.",
         pcs=FIVE,
         npcs=[('Fizban', 'npc:fizban'), ('The guildmaster', 'npc:lucky')],
         places=[('The Road to Vogler', None), ('Vogler', 'place:vogler'), ('The Vingaard River', 'place:the-vingaard-river')],
         items=[("Dragon's Eye Coin", 'item:dragons-eye-coin')]),
    dict(num=3, title='The Beast Beneath Crustdurn Isle', level=2, where='Vogler', video='p_iMbkL0n8w',
         subtitle='Vogler fed them well. Something in the river was taking the fish.',
         synopsis='The party explores Vogler, hears tales of Ispin, and Aratos is reunited with his cousin Aeimos. The trouble in the river leads to Crustdurn Isle, where a tentacled frog-beast beneath an abandoned shack swallows Roshi before it is killed. They come back with treasure and proof.',
         pcs=SIX,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Fizban', 'npc:fizban')],
         places=[('Vogler', 'place:vogler'), ('Crustdurn Isle', 'place:crustdurn-isle'), ('The Brass Crab', 'place:vogler')],
         items=[('Moon-Touched Sword', 'item:moon-touched-sword'),
                ('Boots of False Tracks', 'item:boots-of-false-tracks')]),
    dict(num=4, title='Tales, Tears, and Treachery', level=2, where='Vogler', video='5BhFMMHMYpI',
         subtitle="Ispin's memory became a shield, and Vogler became a battlefield.",
         synopsis="Ispin Greenshield's funeral becomes a celebration of an impossible life. The Kingfisher Festival mock battle turns into a massacre when some of Cudgel's mercenaries turn on Vogler.",
         pcs=SIX,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Mayor Raven', 'npc:mayor-raven'), ('Darrett Highwater', 'npc:darrett-highwater'),
               ('Bakaris the Younger', 'npc:bakaris-the-younger'), ('Fizban', 'npc:fizban'),
               ('Old Man Jenkins', 'npc:finbar'), ('Ispin Greenshield', 'npc:ispin-greenshield'),
               ('The golden canary', 'npc:sunscale'), ('Bakaris the Elder', 'npc:bakaris-the-elder')],
         places=[('Vogler', 'place:vogler'), ('The Brass Crab', 'place:vogler'), ('High Hill', 'place:vogler'),
                 ('Thornwall Keep', 'place:thornwall-keep')],
         items=[("Ispin's Green Shield", 'item:ispins-green-shield'), ('Winged Boots', 'item:winged-boots'),
                ('Boots of False Tracks', 'item:boots-of-false-tracks'),
                ('Amulet of Paladine', 'item:amulet-of-paladine')]),
    dict(num=5, title='Shadows in the Woods', level=3, where='Vogler Surrounds', video='mbw91Av_Obc',
         subtitle="An army waits in the woods, and Vogler has little time.",
         synopsis="A captured mercenary names Cudgel's lieutenant Gragonis, the half-ogre killed on High Hill, as the one who came back from the woods with gold. Scouts find one to two hundred soldiers camped in the woods. Roshi and Mayariel's healing draws awe from the wounded. The party stays to defend Vogler.",
         pcs=FIVE,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Mayor Raven', 'npc:mayor-raven'), ('Darrett Highwater', 'npc:darrett-highwater'),
               ('Gragonis', 'npc:gragonis'), ('Old Man Jenkins', 'npc:finbar'), ('The Elder Warrior', None)],
         places=[('Vogler', 'place:vogler'), ('High Hill', 'place:vogler'), ('The Brass Crab', 'place:vogler'),
                 ('The woods beyond Vogler', None)],
         items=[('Leeching Arrows', 'item:leeching-arrows'), ("Dragon's Eye Coin", 'item:dragons-eye-coin')]),
    dict(num=6, title="The Dragon Queen's Demand", level=3, where='Vogler', video='EDvLu6R2ufQ',
         subtitle="An ultimatum in black and red. Open the doors by sunset, or be shown no mercy.",
         synopsis="A rider in black and red delivers the Red Dragon Army's terms: open Vogler's doors by sunset or face slaughter. The party stages a distraction to get Cudgel's lieutenant Jeyev out to her mercenaries, and kills the messenger and his four watchers. The evacuation begins.",
         pcs=FIVE,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Mayor Raven', 'npc:mayor-raven'), ('Bakaris the Elder', 'npc:bakaris-the-elder'),
               ('Than', 'npc:than'), ('Darrett Highwater', 'npc:darrett-highwater'), ('Jeyev', 'npc:jeyev'),
               ('The Elder Warrior', None)],
         places=[('Vogler', 'place:vogler'), ('Thornwall Keep', 'place:thornwall-keep'), ('The camp north of town', None)],
         items=[('Periapt of Wound Closure', 'item:periapt-of-wound-closure'),
                ('Ring of Protection', 'item:ring-of-protection'), ('Leeching Arrows', 'item:leeching-arrows')]),
    dict(num=7, title='Flames Over Vogler', level=3, where='Vogler Docks', video='3yBIUfOKBFI',
         subtitle="The sky darkens with wings over the docks of Vogler.",
         synopsis="A dragon burns the docks as the last boats load. Its rider, Theros Flametongue, duels Aratos. Jasper sees that the dragon is a crewed machine. Mayariel kills Theros, and Aratos brings the machine down with his javelin of lightning. From the boat the party watches Becklin fall into the river and Theros rise again.",
         pcs=FIVE,
         npcs=[('Becklin Uth Viharin', 'npc:becklin-uth-viharin'), ('Cudgel Ironsmile', 'npc:cudgel-ironsmile'),
               ('Than', 'npc:than'), ('Theros Flametongue', 'npc:theros-flametongue'),
               ('The Charred Swordswoman', 'npc:the-charred-swordswoman'),
               ('Darrett Highwater', 'npc:darrett-highwater'), ('Finbar', 'npc:finbar'),
               ('The golden canary', 'npc:sunscale'), ('Jeyev', 'npc:jeyev'), ('The Elder Warrior', None)],
         places=[('Vogler docks', 'place:vogler'), ('Thornwall Keep', 'place:thornwall-keep'),
                 ('The Vingaard River', 'place:the-vingaard-river')],
         items=[('The Emberwake Greataxe', 'item:the-emberwake-greataxe'), ('Boilerdrake Heart', 'item:boilerdrake-heart'),
                ("Mayariel's Signet Ring", 'item:mayariels-signet-ring'), ('Winged Boots', 'item:winged-boots')]),
    dict(num=8, title='Ashes on the River', level=4, where='Vingaard River to Kalaman', video=False,
         subtitle='The dead rise from the river on the way to Kalaman.',
         synopsis='On the river the dead rise as Ashen Vigils, each showing a survivor someone different. The party breaks them, reaches Kalaman, and argues its way before the council. Vogler is given refuge in exchange for military service, with Darrett as the go-between.',
         pcs=FIVE,
         npcs=[('Darrett Highwater', 'npc:darrett-highwater'), ('Mayor Raven', 'npc:mayor-raven'),
               ('Governor Miat', 'npc:governor-miat'), ('Marshal Vendri', 'npc:marshal-vendri'),
               ('Bakaris the Elder', 'npc:bakaris-the-elder'), ('Bakaris the Younger', 'npc:bakaris-the-younger'),
               ('Wyhan', 'npc:wyhan'), ('Roberto', 'npc:roberto'), ('Fizban', 'npc:fizban'),
               ('Sunscale', 'npc:sunscale'), ('Lord Soth', 'npc:lord-soth'), ('Lucky', 'npc:lucky'),
               ('Cathan Twice-Born', 'npc:cathan-twice-born')],
         places=[('The Vingaard River', 'place:the-vingaard-river'), ('Kalaman', 'place:kalaman')],
         items=[("Becklin's Armor", 'item:becklins-armor'), ('Boilerdrake Heart', 'item:boilerdrake-heart'),
                ('The Emberwake Greataxe', 'item:the-emberwake-greataxe')]),
    dict(num=9, title='The Reliquary of Lost Oaths', level=4, where='Outside Kalaman', video='5olPIXViJD4',
         subtitle='Behind an oath-tested door, a necromancer is raising the knights buried there.',
         synopsis="Sent to hunt meat for Ispin's stew, the party finds a hidden Knights Radiant reliquary behind an oath-tested door. A necromancer serving Lord Soth is raising the knights entombed there. They defeat him and the wraith he raises, and the freed spirit names Aratos and Aeimos children of Cathan.",
         pcs=SIX,
         npcs=[('Sir Cthondor', 'npc:sir-cthondor'), ('The Pale Woman', 'npc:the-pale-woman'),
               ('Fizban', 'npc:fizban'), ('Mayor Raven', 'npc:mayor-raven'),
               ('Darrett Highwater', 'npc:darrett-highwater'), ("Lord Soth's necromancer", 'npc:lord-soth')],
         places=[('The refugee camp', 'place:the-refugee-camp'),
                 ('The reliquary', 'place:the-radiant-reliquary')],
         items=[('Horn of Sir Cthondor', 'item:horn-of-sir-cthondor'), ('Armor of the Fallen', 'item:armor-of-the-fallen')]),
    dict(num=10, title='The Weight of the Axe', level=4, where='Kalaman', video='G0hiBL1WDE0',
         subtitle="A recipe hides a spell. A trophy hides a curse.",
         synopsis="Fizban's stew recipe turns out to be a cipher for a spell. Finbar takes Jasper to meet the head of the Dragon's Eye in Kalaman. In a sparring match the trophy axe's rage overtakes Aratos and he nearly kills a squire. Marshal Vendri sends the party, recorded as the Embers, to find the tinkerer Tatina Rookledust. On the way out, at the reliquary, Aratos holds the axe's fire back through resolve.",
         pcs=FIVE,
         npcs=[('Fizban', 'npc:fizban'), ('Finbar', 'npc:finbar'), ('Seredyn', 'npc:seredyn'),
               ('Wyhan', 'npc:wyhan'), ('Roberto', 'npc:roberto'), ('Marshal Vendri', 'npc:marshal-vendri'),
               ('Darrett Highwater', 'npc:darrett-highwater'), ('Mayor Raven', 'npc:mayor-raven'),
               ('Sir Cthondor', 'npc:sir-cthondor')],
         places=[('The refugee camp', 'place:the-refugee-camp'), ('Kalaman', 'place:kalaman'),
                 ("Finn's Bar", 'place:kalaman'), ('The reliquary', 'place:the-radiant-reliquary')],
         items=[("Fizban's Stew Recipe", 'item:fizbans-stew-recipe'),
                ('The Emberwake Greataxe', 'item:the-emberwake-greataxe'),
                ('Armor of the Fallen', 'item:armor-of-the-fallen')]),
    dict(num=11, title='The Moons Over Bracken Hollow', level=4, where='Bracken Hollow', video='Zuxn5gqO9wQ',
         subtitle='A village no one can leave. An eclipse that takes one of them each time.',
         synopsis="A list from Wyhan draws the Embers to Bracken Hollow, a village under three eclipsed moons. No one has been able to leave it for a month. Sergeant Boyd explains the turn of the white, red and black moons, and the eclipse that takes one villager each time. The party climbs the hill with Corvin and Ked and brings down the stone monument by darkening the three rings on its chest, but the Emberwake's fury takes Aratos and Roshi has to drop him. Beneath the hill are three recesses, and three things to find in the village before the next eclipse.",
         pcs=FIVE,
         npcs=[('Sergeant Boyd', 'npc:sergeant-boyd'), ('Corvin', 'npc:corvin'), ('Ked', 'npc:ked'),
               ('Wyhan', 'npc:wyhan'), ('Gribb Brack', None), ('Marigold', None)],
         places=[('Bracken Hollow', 'place:bracken-hollow'), ('The graveyard', 'place:bracken-hollow'),
                 ('The hill and its monument', 'place:bracken-hollow'),
                 ('The cavern beneath the hill', 'place:bracken-hollow')],
         items=[('The Emberwake Greataxe', 'item:the-emberwake-greataxe'),
                ('The Horn of Sir Cthondor', 'item:horn-of-sir-cthondor'),
                ('Moon-Touched Sword', 'item:moon-touched-sword'),
                ('Leeching Arrows', 'item:leeching-arrows'),
                ('Periapt of Wound Closure', 'item:periapt-of-wound-closure')]),
]

# ---------------------------------------------------------------------------
# THE ATLAS
# ---------------------------------------------------------------------------
# region: kalaman | vogler | beyond
# sites are named spots inside a place that do not need a page of their own.

REGIONS = [
    ('kalaman', 'Kalaman', 'The walled city, its camp, and the hills around it.'),
    ('vogler', 'Vogler', 'The town on the Vingaard that the party could not save.'),
    ('beyond', 'Beyond', 'The roads between, and places known only by name.'),
]

ATLAS_MAP = dict(src=IMG + '1V7_DqsoC7C3KVWuW27c-Um8YASEvQaxm', alt='Map of Ansalon',
                 caption='Ansalon')

PLACES = [
    dict(slug='kalaman', name='Kalaman', kind='Walled city', region='kalaman', where='On the Vingaard',
         last=10, status='Base of operations',
         overview="Kalaman is a walled city a few days downriver from Vogler. It took in Vogler's refugees in exchange for the party's service. It holds a High Sorcery presence, a hidden branch of the Dragon's Eye, and a courtyard of knightly statues that includes Lord Soth.",
         sites=[('The council chambers', "Where Governor Miat granted Vogler refuge."),
                ('The castle training yard', "Where the Emberwake took Aratos in a sparring match."),
                ('The knights\' courtyard', "Statues of knights once honored, Lord Soth among them."),
                ("Wyhan's Apothecary", "Components, potions at steep prices, and High Sorcery's business."),
                ("Peller's Provisions", "A general goods store. Look closely at the sign and it reads Finn's Bar. Knock three times.")],
         links=['npc:governor-miat', 'npc:marshal-vendri', 'npc:wyhan', 'npc:seredyn', 'npc:roberto',
                'npc:bakaris-the-elder', 'place:the-refugee-camp', 'place:the-radiant-reliquary',
                'quest:service-to-kalaman', 'fac:the-dragons-eye'],
         records={
             6: ["Named as the nearest help, a few days away to the northeast across the river",
                 "Lord Bakaris offered a sealed letter for a rider to carry there"],
             8: ["Rose ahead on the river, a few days from Vogler",
                 "Its council heard the party and granted the refugees shelter in exchange for military service",
                 "A Dragon's Eye agent walked out of the council chamber under an illusion"],
             9: ["Let the refugees camp outside its walls"],
             10: ["Finbar brought Jasper through the gates by night to Finn's Bar",
                  "Aratos cut down a squire in the castle training yard",
                  "Its marshal recorded the party as the Embers and sent them out on their first mission"],
         }),
    dict(slug='the-refugee-camp', name='The Refugee Camp', kind='Encampment', region='kalaman',
         where='Outside Kalaman', last=10, status='Home base',
         overview="Tents along the Vingaard River outside Kalaman's walls, where the people of Vogler have settled. Darrett sleeps here among the Voglerans, and the party kept its fire here until it left on its first mission.",
         links=['npc:mayor-raven', 'npc:darrett-highwater', 'npc:fizban', 'place:kalaman', 'place:vogler',
                'quest:refuge-for-vogler'],
         records={
             9: ["Pitched beneath the city's walls with tents and fresh water enough for the moment",
                 "Fed for a night on bear and Ispin's stew"],
             10: ["Lighter after the stew, with warm voices around the fires",
                  "Aratos saw the tree of fire and frost in its campfire",
                  "Kakashi saw three full moons and an elven woman in a pail of water near the tents"],
         }),
    dict(slug='the-radiant-reliquary', name='The Radiant Reliquary', kind='Tomb of fallen knights',
         region='kalaman', where='Hills outside Kalaman', last=10, status='Cleansed',
         overview="A cave outside Kalaman opens onto a stone door marked with the sword of the Knights Radiant, drawn with six points. The door asks for an oath. Behind it, murals show Knights of Solamnia and Knights Radiant fighting together against a floating city, and standing in smaller numbers as it fell. The reliquary is the tomb of the knights who fell in that battle. Their armored dead stand around the walls of a round chamber, and Sir Cthondor stands at its center with a horn in the crook of his arm.",
         sites=[('The oath door', "Lit Valor for Aratos, Resolve and a third spoke for Aeimos, Foresight for Kakashi."),
                ('The mural passage', "Knights of Solamnia and Knights Radiant fighting together against a floating city, then the city falling. The horn-bearer's image is smeared with purplish-black ash."),
                ('The tomb', "A round chamber for the knights who fell in the battle on the murals. Their armored dead stand along the walls. At the center is the statue of Sir Cthondor, whose horn Aratos now carries.")],
         links=['npc:sir-cthondor', 'npc:lord-soth', 'item:horn-of-sir-cthondor', 'item:armor-of-the-fallen',
                'fac:the-knights-radiant', 'quest:meat-for-ispins-stew', 'quest:the-emberwakes-curse',
                'quest:lord-soths-corruption'],
         records={
             9: ["Found at the end of a bear trail, a blue glow pulsing from inside",
                 "Its door opened once four spokes were lit: Valor, Resolve, protection and Foresight",
                 "A necromancer serving Lord Soth was raising its dead over a spectral black rose",
                 "Three of its knights rose before the ritual was cut short",
                 "Went quiet again when Sir Cthondor sounded his horn"],
             10: ["The door opened at the remembered sequence",
                  "Aratos stood before the statue and held the Emberwake's fire back through resolve",
                  "The others saw mist rise as the axe changed shape and changed back"],
         }),
    dict(slug='vogler', name='Vogler', kind='Riverside town', region='vogler', where='On the Vingaard',
         last=7, status='Destroyed', portrait=IMG + '1_IqP61QpZkvN-ugktyUe91hGKDyXiYG0',
         plate=dict(src=IMG + '1A-nxlQT29DGSJkhR2kh0BKrBGIJo_mGo', alt='Map of Vogler', caption='Vogler, before the fire'),
         overview="Vogler was a village on the Vingaard River that knew how to mourn and celebrate in the same breath. It honored Ispin Greenshield, held the Kingfisher Festival, and was burned by the Red Dragon Army's mechanical dragon. Its people are now refugees outside Kalaman.",
         sites=[('The Brass Crab', "Food, drink and stories. Crab ramen, at your own risk."),
                ('High Hill', "Where the festival's mock battle turned into a massacre."),
                ('The docks', "A fish statue touched for luck; later, the last stand."),
                ("Gertrude's smithy", "Where Aratos first spoke with Becklin."),
                ('General Goods', "Old Man Jenkins behind the counter.")],
         links=['npc:mayor-raven', 'npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'npc:than',
                'npc:ispin-greenshield', 'place:thornwall-keep', 'place:crustdurn-isle',
                'place:the-vingaard-river', 'place:the-refugee-camp', 'quest:the-evacuation-of-vogler',
                'quest:the-betrayal-at-high-hill', 'quest:the-vanishing-fish', 'fac:the-red-dragon-army'],
         records={
             2: ["Reached as the village prepared for a festival and for Ispin's celebration of life at the Brass Crab"],
             3: ["Its fishers reported half the usual catch and an odd sound from the water at night",
                 "Kept safe another day when the beast beneath Crustdurn Isle was killed"],
             4: ["Sent Ispin down the river at sunset and told his stories at the Brass Crab",
                 "Betrayed at High Hill when Cudgel's mercenaries attacked with real steel",
                 "A note found on the half-ogre named the Red Army"],
             5: ["Carried its wounded home beneath festival banners",
                 "Learned that one to two hundred soldiers were camped in the woods to the northeast",
                 "Set watches, posted hunters as lookouts and began shoring up its defenses"],
             6: ["Ordered to open its doors by sunset or face slaughter",
                 "Began to pack, repair boats and set traps"],
             7: ["Its villagers were brought to the boats",
                 "Its docks were burned by a dragon that turned out to be a machine",
                 "Occupied by the Red Army as the party's boat left",
                 "Becklin was struck from behind on the docks and fell into the river"],
         }),
    dict(slug='thornwall-keep', name='Thornwall Keep', kind='Keep', region='vogler', where='Vogler',
         last=7, status='Lost with Vogler',
         overview="The keep at Vogler. Becklin gave Roshi Ispin's shield here, Than kept his workshop here, and Becklin left a chest here for Darrett, with plate armor in it. It burned with the town.",
         links=['npc:than', 'npc:becklin-uth-viharin', 'place:vogler', 'item:ispins-green-shield'],
         records={
             2: ["Villagers told Jasper of it as he asked around Vogler"],
             3: ["Becklin stopped Jasper here and told him Ispin's celebration was that evening"],
             4: ["Becklin gave Roshi Ispin's Green Shield here",
                 "Becklin named Than as her lodger here"],
             6: ["Roshi found Than and his unstable explosives",
                 "She learned that the keep was Becklin's home and that a gnome-flinger stood on its roof",
                 "From its window she spotted the messenger's watchers on the cliff",
                 "Becklin named a chest here to be brought to Darrett once things settled"],
             7: ["Aratos and Roshi brought Becklin's chest out during the evacuation",
                 "Four of the party helped Than clear draconians from the keep during the evacuation",
                 "Flames climbed the tower; Than left by gnome-flinger from the roof"],
         }),
    dict(slug='crustdurn-isle', name='Crustdurn Isle', kind='River island', region='vogler',
         where='Vingaard River, near Vogler', last=3, status='Cleared',
         portrait=IMG + '1vo5CCa735IpdEeKIybErdPNBYQ5R5q92',
         overview="A lonely island in the river near Vogler, rumored haunted and avoided by locals. A hatch in its abandoned shack leads down to a cavern littered with fish bones.",
         links=['place:vogler', 'quest:the-vanishing-fish', 'item:moon-touched-sword'],
         records={
             3: ["Found through the eyes of Kakashi's raven, then reached in a fisherman's rowboat paid for with fish",
                 "A journal page in its shack and a faded inscription on the dock statue suggested something had once needed to be fed or appeased",
                 "The beast in the cavern swallowed Roshi and was killed",
                 "Gave up a moon-touched sword and a pair of boots of false tracks",
                 "Becklin knew only of an old man who had lived there before her time"],
         }),
    dict(slug='bracken-hollow', name='Bracken Hollow', kind='Forest village', region='beyond',
         where='Off the road out of Kalaman', last=11, status='Sealed',
         overview="A plain village tucked into the forest, of the same sort as Vogler, with no guard at its gate. For about a month no one has been able to leave it: a person who walks out past its edge walks back in on the far side. The three moons hang over it in eclipse and take turns. Under the white moon people feel a little sick and echoes of the villagers walk the streets. Under the red a battle is fought in the town. Under the black the wolves come, and the farms give food. Then comes the eclipse itself, when the monument on the hill wakes and one of the black-touched vanishes. A few travelers are shut in with the villagers. About two hundred people lived here. Around forty are gone.",
         sites=[('The graveyard', "A short walk from the square. Some of its graves are fresh."),
                ("Boyd's shelter", "A dim, run-down house where Boyd keeps villagers through the dangerous hours."),
                ('The farms', "They give food only under the black moon, when the wolves are out."),
                ('The hill and its monument', "A tall block of stone that wakes and stands during the eclipse. Three rings on its chest: white, red, black."),
                ('The cavern beneath the hill', "Reached by a crevice at the top of the hill. Closed, with three recesses. The spell is bound here."),
                ("Marigold's cottage", "Just outside the village. Home of the healer, who was away the night it closed.")],
         links=['npc:sergeant-boyd', 'npc:corvin', 'npc:ked', 'quest:the-spell-over-bracken-hollow',
                'quest:the-ones-sent-up-the-hill', 'quest:wyhans-list', 'pc:kakashi', 'pc:aratos'],
         records={
             11: ["Seen through the trees from a creek; a flag stirred inside its gate",
                  "Went dark as the party walked in, under three moons standing in eclipse",
                  "Four black wolves came out of the dark at the party in the road",
                  "Boyd explained the turn of the moons and what the eclipse takes",
                  "A few travelers are shut in with the villagers",
                  "Its monument woke, fought, and lost its head on the hill",
                  "A beam of red, white and black light rose from inside the hill",
                  "Kakashi and Jasper found three recesses in a cavern beneath it"],
         }),
    dict(slug='the-vingaard-river', name='The Vingaard River', kind='River', region='beyond',
         where='Vogler to Kalaman', last=8, status='Traveled',
         overview="The river that runs past Vogler and on to Kalaman, a few days downstream. It carried Ispin's funeral boat, and later the whole town.",
         links=['place:vogler', 'place:kalaman', 'place:crustdurn-isle', 'npc:lord-soth'],
         records={
             4: ["Took Ispin Greenshield's boat at sunset"],
             7: ["Carried the party's boat away from the burning docks; Becklin fell into it"],
             8: ["The dead rose from it as Ashen Vigils, each showing a survivor someone different",
                 "Those pulled under were dragged back from the brink"],
         }),
    dict(slug='tower-of-wayreth', name='The Tower of Wayreth', kind='Arcane stronghold', region='beyond',
         where='Moves', last=None, last_note='Not yet reached', status='Target',
         overview="A moving tower guarded by wizards, said to hold the Orb of Dragonkind. Jasper's task is to steal the Orb. Seredyn's counsel is that getting in may prove easier than getting out.",
         links=['quest:the-orb-of-dragonkind', 'npc:wyhan', 'npc:seredyn', 'fac:the-mages-of-high-sorcery'],
         records={
             2: ["Named in Jasper's dream as the place the Orb of Dragonkind is kept"],
             10: ["Seredyn does not know where it is; he named Wyhan as the lead to it, and warned about getting out"],
         }),
]

# Charted by name only. A row in the Atlas, no page behind it.
PLACES_UNLINKED = [
    dict(name="Tatina Rookledust's home", kind='Unknown', region='beyond', where="Several days from Kalaman",
         status='Destination',
         blurb="Where the party is headed. Marshal Vendri gave the direction; nothing else about it is known."),
    dict(name='The road to Vogler', kind='Road', region='beyond', where='Solamnia',
         status='Traveled',
         blurb="Where five strangers met in an ambush, burned the scaled dead, and later met an old wizard inside a creature of living sand."),
]

# ---------------------------------------------------------------------------
# THE ARMORY
# ---------------------------------------------------------------------------
# klass: magic-item | keepsake | document   (the tabs)
# kind:  the Type facet

ITEMS = [
    dict(slug='the-emberwake-greataxe', name='The Emberwake Greataxe', sub='Cursed trophy axe',
         klass='magic-item', kind='Weapon', holder='Aratos', holder_ref='pc:aratos',
         origin="Taken from Theros Flametongue at the Vogler docks", last=11, status='Held; cursed',
         overview="A great axe that runs warm to the touch. Aratos took it from Theros Flametongue's body as Vogler burned. It is cursed. A hit in a sparring match woke a rage in him that was not his own, and it took him again on the hill at Bracken Hollow. He cannot hand it to anyone or part with it, and other weapons now sit wrong in his hand. It went cold once, at the reliquary, when he chose resolve, and for a moment it became the Leviathan Axe.",
         links=['pc:aratos', 'npc:theros-flametongue', 'npc:roberto', 'quest:the-emberwakes-curse',
                'place:the-radiant-reliquary', 'place:bracken-hollow',
                'quest:the-leviathan-axe'],
         records={
             7: ["Carried into Vogler, flaming, by Theros Flametongue",
                 "Taken still warm from his body by Aratos"],
             8: ["Taken up by Aratos on the river to Kalaman"],
             9: ["Drawn in the reliquary as fire and storm rose around Aratos",
                 "Felt heavier in his hands than it should have"],
             10: ["Warmed in his hand after the King's warning",
                  "Took him in a sparring match and came down on the squire Roberto",
                  "Turned toward Darrett before the rage passed",
                  "Aratos took it back from Darrett and could not hand it to Roshi; he cannot part with it",
                  "Went cold at the reliquary when Aratos chose resolve, and for a moment became the Leviathan Axe"],
             11: ["Opened a wolf from shoulder to flank at Bracken Hollow; green flame leapt to the next",
                  "Pulled at Aratos on the hill until every other weapon sat wrong in his hand",
                  "Took him when the monument's darkness struck him mid-rage; its embers became full flame",
                  "Went through the monument's neck, the stone running like lava"],
         }),
    dict(slug='horn-of-sir-cthondor', name='The Horn of Sir Cthondor', sub="Horn from Sir Cthondor's statue",
         klass='magic-item', kind='Wondrous Item', holder='Aratos', holder_ref='pc:aratos',
         origin="The Radiant Reliquary", last=11, status='Held',
         overview="The horn from the statue of Sir Cthondor, at the center of the Radiant Reliquary. Blown, it makes no sound a mortal can hear. Spectral warriors answer it: two knights in the tomb, and five on the hill at Bracken Hollow. It answers once in seven days, and the warriors stay an hour.",
         links=['pc:aratos', 'pc:aeimos', 'npc:sir-cthondor', 'place:the-radiant-reliquary',
                'fac:the-knights-radiant', 'place:bracken-hollow'],
         records={
             9: ["Sir Cthondor's freed spirit blew a spectral horn of his own and sent the risen knights back to rest",
                 "Carved figures moved along it: someone raised the horn, and more knights appeared",
                 "Blown by Aeimos; two spectral knights answered",
                 "Read by Kakashi as a thing made to call aid",
                 "Left with Aratos when Aeimos slipped away"],
             11: ["Blown by Aratos on the hill at Bracken Hollow; five spectral warriors answered",
                  "They dragged the fallen clear and struck the red ring dark",
                  "They took up a defensive position around Aratos when he fell",
                  "Will not answer again for seven days; its warriors stay an hour"],
         }),
    dict(slug='ispins-green-shield', name="Ispin's Green Shield", sub='Shield of a legend',
         klass='keepsake', kind='Shield', holder='Roshi', holder_ref='pc:roshi',
         origin="Ispin Greenshield, by way of Becklin", last=5, status='Held',
         overview="The green shield Ispin Greenshield carried through a life of impossible stories. He left it to Fizban, who declined it and offered it to Ispin's friends. When Roshi took it, it felt as though the shield had come home.",
         links=['pc:roshi', 'npc:ispin-greenshield', 'npc:becklin-uth-viharin', 'place:thornwall-keep'],
         records={
             4: ["Left by Ispin to Fizban, who declined it at the Brass Crab and offered it to Ispin's friends; Roshi asked for it",
                 "Given to her by Becklin at Thornwall Keep the next morning, with the request that she fight in the mock battle",
                 "Showed Roshi it could wrap her in the illusion of a boulder or a tree",
                 "Carried her clear as the half-ogre fell"],
             5: ["Kept near her among the wounded; Ispin's presence felt close"],
         }),
    dict(slug='moon-touched-sword', name='Moon-Touched Sword', sub='Blade from beneath the isle',
         klass='magic-item', kind='Weapon', holder='Roshi', holder_ref='pc:roshi',
         origin="The cavern beneath Crustdurn Isle", last=11, status='Held',
         overview="A moon-touched sword found in the cavern beneath Crustdurn Isle after the beast there was killed.",
         links=['pc:roshi', 'place:crustdurn-isle', 'quest:the-vanishing-fish', 'place:bracken-hollow'],
         records={
             3: ["Recovered from the cavern beneath Crustdurn Isle"],
             4: ["Carried by Roshi at High Hill, where her blade lit with divine fire against the half-ogre"],
             11: ["Hummed in the light of Solinari, the white moon, and flashed with divine fire against the monument"],
         }),
    dict(slug='winged-boots', name='Winged Boots', sub='Boots that carry their wearer into the air',
         klass='magic-item', kind='Wondrous Item', holder='Jasper', holder_ref='pc:jasper',
         origin="Bought from Old Man Jenkins in Vogler", last=9, status='Held',
         overview="A pair of winged boots Jasper bought from Old Man Jenkins with the party's shared gold, and defended to Aratos as a slick deal. Kakashi wore them first.",
         links=['pc:jasper', 'npc:finbar'],
         records={
             4: ["Sold to Jasper at General Goods",
                 "Taken by Kakashi when the party divided its gear",
                 "Worn by Kakashi over the mock battle at High Hill"],
             6: ["Carried Jasper up to the cliff above the gate"],
             7: ["Carried Jasper over the docks, where he saw that the dragon was a machine"],
             9: ["Let Jasper glide down the broken stair into the tomb"],
         }),
    dict(slug='boots-of-false-tracks', name='Boots of False Tracks', sub="Boots that disguise their wearer's trail",
         klass='magic-item', kind='Wondrous Item', holder='Jasper', holder_ref='pc:jasper',
         origin="Found in the cavern beneath Crustdurn Isle", last=4, status='Held',
         overview="A pair of boots found unworn in the cavern beneath Crustdurn Isle. Whoever wears them can make their tracks look like something else's to anyone trying to follow. Jasper took them when the party divided its gear.",
         links=['pc:jasper', 'place:crustdurn-isle'],
         records={
             3: ["Found unworn in the cavern beneath Crustdurn Isle, beside the Moon-Touched Sword"],
             4: ["Taken by Jasper when the party divided its gear"],
         }),
    dict(slug='dragon-vessel', name='Dragon Vessel', sub='A vessel that serves as a potion in reserve',
         klass='magic-item', kind='Wondrous Item', holder='Jasper', holder_ref='pc:jasper',
         origin="Shared out with the party's spoils at Vogler", last=11, status='Held',
         overview="A vessel that can be used as a potion, a drinking horn or any other container. The party counts on it as a healing draught in reserve. Jasper carries it.",
         links=['pc:jasper', 'place:vogler'],
         records={
             7: ["Shared out with the party's spoils before the fight at the docks"],
             10: ["Counted in again when the party shared out its finds after the reliquary; Jasper carries it"],
             11: ["Still in reserve on the hill at Bracken Hollow, with one healing potion left"],
         }),
    dict(slug='javelin-of-lightning', name='Javelin of Lightning', sub='A javelin that strikes as a bolt of lightning',
         klass='magic-item', kind='Weapon', holder='Aratos', holder_ref='pc:aratos',
         origin="Carried since before the road to Vogler", last=11, status='Held',
         overview="Aratos's javelin. Thrown with its command word, it becomes a streak of lightning that passes through whatever stands in its path. It brought down the dragon machine over Vogler.",
         links=['pc:aratos', 'quest:the-leviathan-axe', 'npc:theros-flametongue', 'place:vogler', 'place:bracken-hollow'],
         records={
             2: ["Hurled through the creature of living sand in a streak of lightning"],
             6: ["Thrown as a bolt of lightning that tore through two of the enemy on the cliff above Vogler"],
             7: ["Brought down the dragon machine over the docks",
                 "On a later throw it changed shape for a moment, changed back, and missed"],
             11: ["Thrown at the monument on the hill; the bolt ran harmlessly into the ground"],
         }),
    dict(slug='spear-of-warning', name='Spear of Warning', sub="Jasper's spear, a weapon of warning",
         klass='magic-item', kind='Weapon', holder='Jasper', holder_ref='pc:jasper',
         origin="Carried since before the road to Vogler", last=11, status='Left on the hill',
         overview="Jasper's spear, a weapon of warning like Mayariel's longbow. He threw it at the monument at Bracken Hollow and missed, and it still lies on the hillside.",
         links=['pc:jasper', 'item:longbow-of-warning', 'place:bracken-hollow'],
         records={
             2: ["Tore an opening in the creature of living sand and showed the old man inside"],
             11: ["Thrown at the monument, missed, and stayed where it landed on the hillside"],
         }),
    dict(slug='longbow-of-warning', name='Longbow of Warning', sub='A longbow that hums when danger is near',
         klass='magic-item', kind='Weapon', holder='Mayariel', holder_ref='pc:mayariel',
         origin="Carried since before the road to Vogler", last=11, status='Held',
         overview="Mayariel's longbow. It hums when danger is close, and it has done so before an ambush on the road and before the wolves at Bracken Hollow.",
         links=['pc:mayariel', 'item:spear-of-warning', 'place:bracken-hollow'],
         records={
             1: ["Began to hum as the elves' caravan rested, a moment before the scream"],
             11: ["Hummed its warning against her back before the wolves came out of the trees"],
         }),
    dict(slug='leeching-arrows', name='Leeching Arrows', sub='Arrows that draw life from their target',
         klass='magic-item', kind='Ammunition', holder='Jasper', holder_ref='pc:jasper',
         origin="Given by Old Man Jenkins", last=11, status='Held',
         overview="Arrows with dried leeches fixed to the heads, meant to latch on and draw life from whatever they strike. Nobody had wanted to buy them. Jenkins handed them over, grudgingly, when Jasper chose to stay and defend Vogler.",
         links=['pc:jasper', 'npc:finbar'],
         records={
             5: ["Given to Jasper along with two healing potions"],
             6: ["One loosed from the cliff in the fight at the gate; the petrified leech came alive as it was nocked"],
             11: ["One loosed at the monument; Jasper woke the dried leech with a touch of magic and it bored into the stone"],
         }),
    dict(slug='dragons-eye-coin', name="The Dragon's Eye Coin", sub="Mark of the guild",
         klass='magic-item', kind='Wondrous Item', holder='Jasper', holder_ref='pc:jasper',
         origin="The Dragon's Eye", last=5, status='Held; binding',
         overview="The golden coin, set into Jasper's hand, by which the Dragon's Eye marked and bound him. It will kill him if he does not do as the guild master says. It lets him see through the disguises of other guild members, and it can lend him another face.",
         links=['pc:jasper', 'npc:lucky', 'fac:the-dragons-eye', 'quest:the-orb-of-dragonkind'],
         records={
             2: ["Remembered in Jasper's dream of the guild that marked him",
                 "Showed Jasper a small figure inside a hunched old man in Vogler's market square"],
             3: ["Showed Jasper a shimmer around an older figure on the way to Thornwall Keep; he told no one"],
             4: ["Showed Jasper a small figure inside Old Man Jenkins's shape",
                 "Jenkins warned that it will kill him if he does not do as Lucky says"],
             5: ["Used to pass as a soldier at the edge of the camp in the woods"],
         }),
    dict(slug='boilerdrake-heart', name='Boilerdrake Heart', sub='Fire gem from the war machine',
         klass='magic-item', kind='Gem', holder='Kakashi', holder_ref='pc:kakashi',
         origin="The wreck of the mechanical dragon", last=9, status='Held; attuned',
         overview="A hot, glowing gem pulled from the wreckage of the mechanical dragon that burned Vogler. It was the source of the machine's fire.",
         links=['pc:kakashi', 'fac:the-red-dragon-army', 'place:vogler', 'quest:the-first-mission'],
         records={
             7: ["Pulled from the dragon machine's wreck by Kakashi; it burned his hand",
                 "He judged it to be where the machine's fire had come from"],
             8: ["Attuned on the river"],
             9: ["Forced beyond its limits to add fire to his lightning against the wraith"],
         }),
    dict(slug='moon-marked-spellbook', name='Moon-Marked Spellbook', sub='Reward of the mage trial',
         klass='magic-item', kind='Wondrous Item', holder='Kakashi', holder_ref='pc:kakashi',
         origin="The mage trial", last=1, status='Held',
         overview="A spellbook marked with the moons, handed over by a red-robed proctor when Kakashi and Jasper passed the entry exam of the Mages of High Sorcery.",
         links=['pc:kakashi', 'pc:jasper', 'fac:the-mages-of-high-sorcery'],
         records={
             1: ["Handed over by a red-robed proctor when Kakashi and Jasper passed the entry exam at the Barb"],
         }),
    dict(slug='periapt-of-wound-closure', name='Periapt of Wound Closure', sub='Amulet that holds off death',
         klass='magic-item', kind='Wondrous Item', holder='Roshi', holder_ref='pc:roshi',
         origin="Taken from the Red Army's fallen at Vogler", last=11, status='Worn',
         overview="A magical amulet found on one of the Red Army dead at Vogler, on the same body as the blue-gemmed ring. Identified as a Periapt of Wound Closure, which preserves its wearer from death when they fall.",
         links=['place:vogler', 'pc:roshi', 'place:bracken-hollow'],
         records={
             6: ["Found on one of the fallen, on the same body as the blue-gemmed ring",
                 "Identified as a Periapt of Wound Closure, which preserves its wearer from death when they fall"],
             7: ["Worn by Roshi; kept her from death when the dragon machine crashed"],
             11: ["Worn by Roshi; held her from death when the moons' light struck her down"],
         }),
    dict(slug='ring-of-protection', name='Ring of Protection', sub='A blue-gemmed ring of protective magic',
         klass='magic-item', kind='Ring', holder='Kakashi', holder_ref='pc:kakashi',
         origin="Taken from the Red Army's fallen at Vogler", last=6, status='Worn',
         overview="A blue-gemmed ring found on one of the Red Army dead at Vogler, on the same body as the periapt. Identified as a Ring of Protection. Kakashi wears it.",
         links=['pc:kakashi', 'place:vogler'],
         records={
             6: ["Found on the same body as the periapt",
                 "Identified as a Ring of Protection"],
         }),
    dict(slug='armor-of-the-fallen', name='Armor of the Fallen', sub="The necromancer's armor",
         klass='magic-item', kind='Armor', holder='Kakashi', holder_ref='pc:kakashi',
         origin="The necromancer in the reliquary", last=10, status='Worn; bound',
         overview="An intricate armor of bone, heavy with necrotic energy, taken from the body of the necromancer who served Lord Soth. Kakashi wears it. It fitted itself to him and bound to his soul, and if he dies it is lost.",
         links=['pc:kakashi', 'place:the-radiant-reliquary', 'npc:lord-soth'],
         records={
             9: ["Taken from the necromancer's body with 25 gold pieces",
                 "Read by Kakashi as steeped in necrotic energy"],
             10: ["Taken by Kakashi when the reliquary's finds were shared out",
                  "Fitted itself to him and bound to his soul; if he dies, it is lost"],
         }),
    dict(slug='storm-charged-gauntlets', name='Storm-Charged Gauntlets', sub="Aeimos's gauntlets",
         klass='magic-item', kind='Weapon', holder='Aeimos', holder_ref='pc:aeimos',
         origin="Unknown", last=9, status='Held',
         overview="The gauntlets Aeimos fights with. Activated, they strike with lightning, even from a distance.",
         links=['pc:aeimos'],
         records={
             3: ["Lit with lightning in the cavern beneath Crustdurn Isle and landed the blow that killed the beast"],
             9: ["Dropped a risen knight with lightning from across the tomb; it rose again",
                 "Spent their full charge against the wraith"],
         }),
    dict(slug='amulet-of-paladine', name='Amulet of Paladine', sub='A gift that came with the canary',
         klass='keepsake', kind='Wondrous Item', holder='Mayariel', holder_ref='pc:mayariel',
         origin="Appeared in Vogler with the golden canary", last=4, status='Held',
         overview="The Amulet of Paladine is a silver pendant Mayariel woke to in Vogler alongside a golden canary. A voice speaking through the bird said clerics had used it before her, that some call it the Amulet of the Faithful, and that it might aid her divine path.",
         links=['pc:mayariel', 'npc:sunscale'],
         records={
             4: ["Found on waking in Mayor Raven's home, with the canary",
                 "A voice speaking through the bird said clerics had used it before her, and that some call it the Amulet of the Faithful"],
         }),
    dict(slug='mayariels-signet-ring', name="Mayariel's Signet Ring", sub='Family signet, pledged to Paladine',
         klass='keepsake', kind='Ring', holder='Mayariel', holder_ref='pc:mayariel',
         origin="Her family", last=7, status='Pledged',
         overview="Mayariel's family signet ring. On the burning docks of Vogler she offered it to Paladine, with a promise of obedience when the god one day asks something of her. It took on a faint divine glow and stayed on her hand.",
         links=['pc:mayariel', 'npc:sunscale'],
         records={
             7: ["Offered to Paladine with an oath to do what he asks when the time comes",
                 "Took on a faint divine glow and stayed on her hand",
                 "The golden canary came, and its light healed the party"],
         }),
    dict(slug='becklins-armor', name="Becklin's Armor", sub='Plate left for Darrett',
         klass='keepsake', kind='Armor', holder='Darrett Highwater', holder_ref='npc:darrett-highwater',
         origin="Becklin's chest at Thornwall Keep", last=10, status='Worn by Darrett',
         overview="Plate armor that Becklin Uth Viharin left for Darrett in a chest at Thornwall Keep. Darrett would not take it at first. He wears it now as a promise to grow into the burden.",
         links=['npc:becklin-uth-viharin', 'npc:darrett-highwater', 'place:thornwall-keep', 'pc:aratos', 'pc:roshi'],
         records={
             6: ["Becklin asked Aratos to bring the chest that held it to Darrett once things settled"],
             7: ["Carried out of Thornwall Keep in Becklin's chest by Aratos and Roshi during the evacuation"],
             8: ["Offered to Darrett on the river by Roshi and refused",
                 "Accepted and put on at the gates of Kalaman"],
             10: ["Polished and unscathed on Darrett as he headed to training before dawn"],
         }),
    dict(slug='fizbans-stew-recipe', name="Fizban's Stew Recipe", sub="Ispin's campfire stew, in Fizban's hand",
         klass='document', kind='Document', holder='Burned away', holder_ref=None,
         origin="Dropped by Fizban at the refugee camp", last=10, status='Spent',
         overview="A scrap of parchment recording Ispin Greenshield's campfire stew, each ingredient in an absurd quantity. The numbers were a cipher pointing to words in the recipe itself, and the words were an incantation. Spoken aloud, it taught all five of the party the Green Flame Blade and burned to nothing.",
         links=['npc:fizban', 'npc:wyhan', 'npc:ispin-greenshield', 'quest:fizbans-recipe', 'pc:roshi', 'pc:kakashi'],
         records={
             10: ["Fell from where Fizban had been sitting; Roshi picked it up",
                  "Its reminder: do not forget the fire, the blade, or the green bits",
                  "Kakashi suspected the quantities were not measurements",
                  "Wyhan, given only the numbers, judged that they decipher part of the recipe into an incantation",
                  "Roshi worked out the words and spoke them: blade made bright, let emerald fire arise, strike one foe, then leap before their eyes",
                  "Green flame touched each of the five and the parchment burned away"],
         }),
]

ITEM_TABS = [
    ('all', 'All Items'),
    ('magic-item', 'Magic Items'),
    ('keepsake', 'Keepsakes'),
    ('document', 'Documents'),
]

# ---------------------------------------------------------------------------
# WAR INTEL
# ---------------------------------------------------------------------------
# band: threat | order | guild   (grouping on the index)

FACTIONS = [
    dict(slug='takhisis-the-shadow-queen', name='Takhisis, the Dragon Queen', band='threat',
         kind='The power behind the invasion', relation='Overarching enemy', last=8, status='Active',
         aliases=['Shadow Queen', 'Dragon Queen'],
         overview="Takhisis is the queen the enemy serves. Her soldiers call her the Shadow Queen and the Dragon Queen and say they are reclaiming the realm for her. Mayariel has seen her in vision as a horned woman in dark regalia who unfolds into a five-headed dragon.",
         links=['fac:the-red-dragon-army', 'fac:draconians', 'pc:mayariel', 'quest:the-sword-of-the-dragon-queen'],
         records={
             1: ["A scaled soldier told Roshi the Shadow Queen sent them, and only Mayariel understood",
                 "Its captive spoke of reclaiming the realm for its queen: the east already fallen, the shadow coming fast"],
             3: ["Seen by Mayariel commanding slaughter beneath the moons, then as a five-headed dragon; platinum fire rose to shield her"],
             6: ["The Red Dragon Army's scroll named her and demanded Vogler's surrender"],
             7: ["The charred woman called after the boat: you will not escape the flames of the Dragon Queen"],
             8: ["Appeared to Mayariel in the river and promised that her sword would find her"],
         }),
    dict(slug='the-red-dragon-army', name='The Red Dragon Army', band='threat',
         kind='Enemy army', relation='Primary enemy force', last=8, status='Active',
         aliases=['Red Army'],
         overview="An invading army serving the Dragon Queen, organized and well supplied. It fields armored soldiers, draconians and a war machine built like a dragon, and it paid mercenaries to turn on Vogler. It burned Vogler and is pressing other villages too.",
         links=['fac:takhisis-the-shadow-queen', 'fac:draconians', 'npc:theros-flametongue',
                'npc:the-charred-swordswoman', 'npc:gragonis', 'place:vogler', 'item:boilerdrake-heart',
                'quest:the-first-mission', 'quest:the-betrayal-at-high-hill'],
         records={
             1: ["Scaled soldiers ambushed a caravan on the road to Vogler, in the name of a queen"],
             4: ["A note on the dead half-ogre read: For your services from the Red Army"],
             5: ["One to two hundred soldiers found camped in the woods northeast of Vogler",
                 "Aratos saw one broad figure on patrol there, built like the creatures from the road"],
             6: ["A rider in black and red delivered its terms: open the doors by sunset or face slaughter",
                 "Four watchers covered the rider from the cliff: three human soldiers and one that looked reptilian",
                 "The rider and all four watchers were killed"],
             7: ["Burned Vogler's docks with a mechanical dragon, crewed from within, that cast its fire from a glowing gem",
                 "The machine's fire caught Theros Flametongue along with the party",
                 "Occupied Vogler",
                 "Raised Theros Flametongue again by fire"],
             8: ["Governor Miat confirmed other villages have come under attack"],
         }),
    dict(slug='draconians', name='Draconians', band='threat',
         kind='Creature', relation="Soldiers of the Dragon Queen", last=7, status='Active',
         overview="Reptilian humanoids with scaled hides, sharp claws and brutal weapons. They speak Draconic and fight in coordination. A captured one killed itself sooner than talk. Their bodies decay with unnatural speed, and a red one exploded when it was killed.",
         links=['fac:the-red-dragon-army', 'fac:takhisis-the-shadow-queen'],
         records={
             1: ["Ambushed a caravan on the road; one knight fell with an arrow in his throat",
                 "A captive spoke of its queen, then swallowed its own tongue when asked whether more were near",
                 "The party burned the bodies"],
             5: ["Aratos saw one broad figure on patrol at the camp in the woods, built like the creatures from the road"],
             6: ["A reptilian figure stood among the messenger's four watchers on the cliff"],
             7: ["Broke into Thornwall Keep and fought on the Vogler waterfront",
                 "A red one, shot by Than, convulsed and exploded as it died",
                 "A second creature threw lightning from its hand and burst apart when Jasper killed it"],
         }),
    dict(slug='the-knights-of-solamnia', name='The Knights of Solamnia', band='order',
         kind='Knightly order', relation='Sought as allies', last=9, status='Active',
         overview="The knighthood Aratos set out to reach and warn of what his vision showed. Becklin Uth Viharin was a retired knight of the order. Lord Soth was once one of its most celebrated knights and fell into disgrace. His statue still stands in Kalaman's courtyard.",
         links=['npc:becklin-uth-viharin', 'npc:lord-soth', 'npc:darrett-highwater', 'pc:aratos',
                'fac:the-knights-radiant', 'place:kalaman'],
         records={
             1: ["Knights died in the ambush on the road to Vogler"],
             2: ["Aratos recognized the dead knights' armor as the order's",
                 "A briefing on one body showed they had been sent to look into attacks on local farmers"],
             3: ["Aratos told Becklin, a retired knight, that he carried a warning for the order",
                 "Becklin said she was the only knight in Vogler"],
             6: ["Named as the garrison at Kalaman, the nearest help for Vogler"],
             7: ["Becklin Uth Viharin held the docks, was struck from behind and fell into the river"],
             8: ["Statues of knights once honored stand in Kalaman's courtyard, Lord Soth among them"],
             9: ["Shown in the reliquary murals fighting beside the Knights Radiant against a floating city"],
         }),
    dict(slug='the-knights-radiant', name='The Knights Radiant', band='order',
         kind='Ancient knightly order', relation="Aratos's and Aeimos's heritage", last=10, status='Active',
         overview="An order tied to hidden reliquaries. Its symbol is a sword. The door of its reliquary outside Kalaman asked for oaths and answered with the virtues of knighthood: Valor, Resolve, protection and Foresight. Aratos and Aeimos have been named children of Cathan by one of its dead. A necromancer serving Lord Soth was found corrupting that reliquary. The pale woman told Aeimos alone that Soth wishes to corrupt all knights and their legacies.",
         links=['pc:aratos', 'pc:aeimos', 'npc:sir-cthondor', 'npc:lord-soth',
                'place:the-radiant-reliquary', 'item:horn-of-sir-cthondor',
                'quest:lord-soths-corruption', 'quest:the-leviathan-axe', 'fac:the-knights-of-solamnia'],
         records={
             1: ["Aratos's own order; he set out to carry his warning to the larger Knights of Solamnia"],
             8: ["Aratos identified himself as a Knight Radiant before Kalaman's council; Marshal Vendri acknowledged the title"],
             9: ["A reliquary of the order was found outside Kalaman behind an oath-tested door",
                 "Its murals show the order fighting beside the Knights of Solamnia against a floating city, then the city falling",
                 "The image of the horn-bearer who led them had been smeared with purplish-black ash",
                 "Sir Cthondor named Aratos and Aeimos children of Cathan"],
             10: ["Aratos returned to the reliquary to ask its dead for help"],
         }),
    dict(slug='the-mages-of-high-sorcery', name='The Mages of High Sorcery', band='order',
         kind='Order of wizards', relation='Neutral; Kakashi and Jasper are candidates', last=10, status='Active',
         aliases=['High Sorcery', 'White Robes'],
         overview="An order of wizards. Kakashi and Jasper carry its scrolls and are to test for its White Robes. Its towers are built to keep powerful magical things safe from those who would misuse them. In Kalaman its business runs through Wyhan, an apothecary.",
         links=['npc:wyhan', 'pc:kakashi', 'pc:jasper', 'place:tower-of-wayreth', 'quest:the-white-robes',
                'quest:kakashis-tower-vision', 'item:moon-marked-spellbook'],
         records={
             1: ["Kakashi and Jasper passed its entry exam at the Barb on the Night of the Eye: an invisible maze, a spell carved in runes, and a key they left alone",
                 "A red-robed proctor sent them on to Kalaman by scroll"],
             2: ["Fizban called its Test terrifying and cutthroat, and said he had never cared to join"],
             8: ["Wyhan read their scrolls and set both to test for the White Robes"],
             10: ["Kakashi saw an elven woman warding a round room of relics, the kind of room its towers are built for",
                  "Seredyn warned that the wizards guarding Wayreth are more secretive than the guild itself"],
         }),
    dict(slug='the-dragons-eye', name="The Dragon's Eye", band='guild',
         kind="Thieves' guild", relation="Jasper's entanglement", last=10, status='Active',
         overview="A secretive thieves' guild that marks and binds its members with a coin. Its phrase is: none shall hide from the Dragon's Eye. Its guild master is Lucky Leppomanto. It keeps a hidden branch in Kalaman behind the sign of Peller's Provisions.",
         links=['pc:jasper', 'npc:lucky', 'npc:seredyn', 'npc:finbar', 'item:dragons-eye-coin',
                'quest:the-orb-of-dragonkind', 'place:kalaman'],
         records={
             2: ["Jasper dreamed of the guild that marked him and the task it set"],
             4: ["Old Man Jenkins made contact in Vogler and gave the phrase"],
             8: ["One of its agents left Kalaman's council chamber under an illusion"],
             9: ["A note in Thieves' Cant reached Jasper at the camp: We need to talk"],
             10: ["Its Kalaman branch received Jasper at Finn's Bar, behind a back door in Peller's Provisions",
                  "Seredyn made clear that Lucky had told him nothing",
                  "Seredyn said the guild has other branches and that he answers only to Lucky"],
         }),
]

FACTION_BANDS = [
    ('threat', 'The Enemy', 'Who is marching, and in whose name.'),
    ('order', 'Orders', 'Knights and wizards, living and lost.'),
    ('guild', 'Guilds', 'Those who work out of sight.'),
]

# ---------------------------------------------------------------------------
# THE QUEST BOARD
# ---------------------------------------------------------------------------
# kind:   quest | thread
# status: open | closed
# parent: slug of the quest this hangs under (shown indented on the board)
# objectives: (text, done)

QUESTS = [
    dict(slug='the-spell-over-bracken-hollow', name='The Spell Over Bracken Hollow', kind='quest', status='open', last=11,
         overview=[
             "Bracken Hollow has been shut for about a month. Nobody can walk out of it, the three moons hang over it in eclipse, and each eclipse takes one of its people. The Embers walked in and are shut in with them.",
             "As he fell on the hill, Kakashi saw a lattice of spellwork laid over the whole village, the true sun beyond it, and three knots in the weave. The monument's three rings were receivers for that working. With all three darkened it could be killed, but what is bound this way can come back unless the binding itself is undone.",
             "Beneath the hill is a closed cavern with three recesses. That is where the spell is bound. Three rings, three recesses, three phases: three things are needed there to break it, and they are somewhere in the village. Kakashi is sure they are something other than the monument's rings.",
         ],
         objectives=[("Bring down the monument on the hill", True),
                     ("Find where the spell is bound", True),
                     ("Find the three things the spell needs, somewhere in the village", False),
                     ("Break the spell before the next eclipse", False)],
         links=['place:bracken-hollow', 'npc:sergeant-boyd', 'npc:corvin', 'npc:ked', 'pc:kakashi',
                'quest:the-ones-sent-up-the-hill', 'quest:the-first-mission'],
         records={
             11: ["The party walked in under an eclipse of the three moons. The last was a month ago, and it should come once a year",
                  "Boyd explained the white, red and black moons and the hour of the eclipse",
                  "Boyd said the monument stays on its hill and does not come into the village",
                  "Kakashi saw the lattice over the village and its three knots",
                  "The black, white and red rings were struck dark, and Aratos took the monument's head",
                  "Light rose from inside the hill; a crevice led down to a cavern with three recesses",
                  "Kakashi is sure the three missing things are something other than the monument's rings",
                  "A little less than a day remains until the next eclipse"],
         }),
    dict(slug='the-first-mission', name='The First Mission', kind='quest', status='open',
         giver='npc:marshal-vendri', last=11,
         overview="Marshal Vendri has sent the Embers to find a tinkerer named Tatina Rookledust, several days' travel from Kalaman. Darrett told him that the dragon that burned Vogler was a machine, and he believes she may be able to give some insight into it.",
         objectives=[("Accept the mission from Marshal Vendri", True),
                     ("Reach Tatina Rookledust, several days from Kalaman", False),
                     ("Learn what she knows about the mechanical dragon", False)],
         rewards=["Two healing potions, given at the outset"],
         links=['npc:marshal-vendri', 'npc:darrett-highwater', 'item:boilerdrake-heart',
                'fac:the-red-dragon-army', 'place:kalaman', 'quest:service-to-kalaman',
                'quest:the-spell-over-bracken-hollow'],
         records={
             7: ["The dragon over Vogler proved to be a machine, crewed from within"],
             10: ["Vendri asked the Embers to track down the tinkerer and gave them a map",
                  "Darrett had told him the dragon at Vogler was a machine",
                  "Most of his soldiers are committed elsewhere; he asked the party to leave as soon as it could",
                  "The party set out by way of the reliquary"],
             11: ["Turned aside from the road at Bracken Hollow, where Boyd says no one can leave"],
         }),
    dict(slug='service-to-kalaman', name='Service to Kalaman', kind='quest', status='open',
         giver='npc:governor-miat', last=10,
         overview="Kalaman sheltered the people of Vogler in exchange for the party's aid in its military efforts. Darrett Highwater stands as their proxy, so the Embers serve without being formally conscripted. Missions come from Marshal Vendri, and each of them draws a stipend of five gold a week.",
         objectives=[("Win refuge for the people of Vogler", True),
                     ("Give Kalaman a name to record the party under", True),
                     ("Carry out the missions Marshal Vendri assigns", False)],
         links=['npc:governor-miat', 'npc:marshal-vendri', 'npc:darrett-highwater', 'place:kalaman',
                'place:the-refugee-camp', 'quest:the-first-mission', 'quest:refuge-for-vogler'],
         records={
             8: ["Governor Miat granted refuge on the condition of service",
                 "Darrett stepped forward as intermediary",
                 "Vendri asked for a name for the record"],
             10: ["Aratos said a Knight Radiant can hold no allegiance to a single order",
                  "Darrett offered to carry the formal obligation as proxy; Vendri accepted",
                  "The party took the stipend it had declined: five gold a week each",
                  "The party gave its name: the Embers"],
         }),
    dict(slug='the-orb-of-dragonkind', name='The Orb of Dragonkind', kind='quest', status='open',
         giver='npc:lucky', last=10,
         overview="The Dragon's Eye bound Jasper with a deadly coin. Its guild master, Lucky, set the task: find the moving Tower of Wayreth and steal the Orb of Dragonkind. In the river's apparitions, Lucky warned that time is running out.",
         objectives=[("Make contact with the guild in Kalaman", True),
                     ("Approach Wyhan about reaching the Tower of Wayreth", False),
                     ("Find a way out of the tower as well as a way in", False),
                     ("Steal the Orb of Dragonkind", False)],
         links=['pc:jasper', 'npc:lucky', 'npc:seredyn', 'npc:finbar', 'npc:wyhan', 'item:dragons-eye-coin',
                'place:tower-of-wayreth', 'fac:the-dragons-eye'],
         records={
             2: ["Jasper dreamed of the guildmaster, the coin and the task"],
             4: ["Old Man Jenkins called the job insane: the tower never stays in one place, and only the wizards know how to reach it",
                 "He said there were others like them in Kalaman"],
             8: ["Lucky appeared in the river: time is running out"],
             9: ["A note in Thieves' Cant: We need to talk"],
             10: ["Seredyn judged the task reckless and advised Jasper not to fail",
                  "He does not know where the tower is, and named Wyhan as the best lead",
                  "He warned that getting in might prove easier than getting out"],
         }),
    dict(slug='finbar', name='Finbar', kind='thread', status='open', parent='the-orb-of-dragonkind', last=10,
         overview="Old Man Jenkins of Vogler was a disguise. Underneath is Finbar, a kender of the Dragon's Eye who can turn invisible. Jasper's coin showed him the figure inside the disguise, and he had the name before Vogler fell. The rest of the party still does not know. Finbar gave Jasper potions and leeching arrows in Vogler, and took him to Seredyn in Kalaman.",
         links=['npc:finbar', 'pc:jasper', 'npc:seredyn'],
         records={
             2: ["Jasper saw a small figure inside a hunched old man in Vogler's market square"],
             4: ["Held a blade to Jasper's throat at General Goods, then taught him the guild's phrase",
                 "Had feared that Lucky sent Jasper to kill him"],
             5: ["Gave Jasper potions and leeching arrows as he packed to leave Vogler",
                 "Told him to remember that old Finbar always takes care of him"],
             7: ["Boarded the party's boat, seen only by Jasper; the others heard a voice from nowhere"],
             10: ["Brought Jasper to Finn's Bar behind a new human face, and showed his own inside the guild's door"],
         }),
    dict(slug='the-white-robes', name='The Test for the White Robes', kind='quest', status='open',
         giver='npc:wyhan', last=10,
         overview="Wyhan read the High Sorcery scrolls Kakashi and Jasper carried and determined that both would test for the White Robes. The practical exam was set several weeks out.",
         objectives=[("Present the scrolls to Wyhan", True),
                     ("Sit the practical exam", False)],
         links=['pc:kakashi', 'pc:jasper', 'npc:wyhan', 'fac:the-mages-of-high-sorcery'],
         records={
             1: ["Kakashi and Jasper passed the entry exam and were sent on to Kalaman to continue the apprenticeship"],
             8: ["Wyhan set both on the path of the White Robes"],
             10: ["Wyhan received Kakashi with dry tolerance and sold him components",
                  "She allowed that she could use a hand or two around the shop"],
         }),
    dict(slug='wyhans-list', name="Wyhan's List", kind='quest', status='open', giver='npc:wyhan', last=11,
         overview="A note from Wyhan reached Kakashi on the road with a list of things to gather. Three were easy to come by. The fourth, frostlace, is the one she wants: a small pale flower that comes into bloom with the cold. In Bracken Hollow, Boyd says the farmer Gribb Brack would be the one to ask.",
         objectives=[("Willowbark, from any stream", True),
                     ("Pine resin", True),
                     ("Graveyard moss", True),
                     ("Frostlace", False),
                     ("Bring it all back to Wyhan in Kalaman", False)],
         links=['npc:wyhan', 'pc:kakashi', 'place:bracken-hollow', 'place:kalaman', 'npc:sergeant-boyd'],
         records={
             11: ["Willowbark cut from the roots at a creek outside Bracken Hollow",
                  "Resin tapped from a stand of pines on the way in",
                  "Moss taken from the headstones in the graveyard",
                  "Roshi knew frostlace as a pale flower that blooms with the cold",
                  "Boyd pointed to Gribb Brack, and offered to take the party there under the white moon"],
         }),
    dict(slug='the-leviathan-axe', name='The Leviathan Axe', kind='quest', status='open', last=11,
         overview=[
             "Aratos has made his choice. Shown a tree that burns on one side and is glazed with frost on the other, and offered blades bound in fury or an axe marked by cold restraint, he reached for the cold.",
             "The one testing him is the elder warrior who stood at the foot of the tree and told him to choose. His has been the voice in Aratos's ear since: prove, good, are you worthy?",
             "At the reliquary the Emberwake took the shape of the axe from his vision, the Leviathan Axe, for a moment. Then it turned back.",
             "The King, one of the ancestral spirits who appear when he rages, has come to him three times. At the campfire he gave a warning: the same blood, the same weakness. In Kalaman he stood among the party and said: don't let it overtake you. At the reliquary he told Aratos to test his resolve, and the axe's fire rose at once. Aratos held.",
             "At Bracken Hollow he did not hold. The fury took him in the middle of a fight, and Roshi had to bring him down.",
         ],
         objectives=[("Choose between fury and restraint", True),
                     ("Hold to that choice when the axe's fire rises", False)],
         links=['pc:aratos', 'item:the-emberwake-greataxe', 'npc:lord-soth', 'npc:theros-flametongue',
                'place:the-radiant-reliquary', 'fac:the-knights-radiant',
                'quest:the-emberwakes-curse', 'place:bracken-hollow'],
         records={
             5: ["A stern, ancient warrior at the foot of a tree split between flame and frost offered blades bound in fury, or an axe marked by cold restraint: choose, boy. The gods are watching"],
             6: ["On the cliff above Vogler his axe ran cold, his swing missed, and the elder warrior's voice said one word: prove"],
             7: ["The elder warrior's rough old voice said one word in his ear, good, as his javelin brought down the dragon machine",
                 "On a later throw cold crept from his chest down his arm and the elder warrior's voice asked: are you worthy?",
                 "The javelin changed shape for a moment; he could not hold the connection, and it changed back and missed",
                 "He took Theros Flametongue's still-warm axe from beside the body"],
             8: ["Cathan Twice-Born and Lord Soth stood in the river as opposing shadows of legacy and choice: he would have to choose soon"],
             9: ["Spectral figures stood with him in the reliquary: a towering bald warrior, a kingly hooded figure, and a slim blue-hued guardian with a spear"],
             10: ["The tree appeared in the campfire, a black rose at its base; the King said: the same blood flows through my veins. The same weakness. Don't let it take you",
                  "In Kalaman the King stood among his companions: don't let it overtake you",
                  "At the reliquary the King laid a hand on his shoulder: you must test your resolve",
                  "He remembered the tree and chose resolve. The flames died, and for a moment he held the Leviathan Axe",
                  "He thinks he can control it, and he will have to be ready"],
             11: ["On the hill at Bracken Hollow the Emberwake pulled at him, and every other weapon sat wrong in his hand",
                  "Struck by the monument's darkness while raging, he lost himself to a fury that was not his own",
                  "Roshi had to drop him before he turned on his friends"],
         }),

    # -- threads --
    dict(slug='the-ones-sent-up-the-hill', name='The Ones Sent Up the Hill', kind='thread', status='open',
         parent='the-spell-over-bracken-hollow', last=11,
         overview="Each eclipse takes one of the black-touched. Corvin says the village has a choice in it: another of the black-touched can be sent up the hill in the chosen one's place, and that one is taken. He holds that some people's skills are still needed. Boyd says no one should have to make that choice for another. On the hill Corvin kept Ked from leaving at dagger-point, knocked him senseless, and ran. Ked and Aratos had both been marked with the black, and the eclipse was not yet over.",
         links=['npc:corvin', 'npc:ked', 'npc:sergeant-boyd', 'pc:aratos', 'place:bracken-hollow'],
         records={
             11: ["Corvin told the party what Boyd had left out",
                  "Jasper judged that Corvin wanted Boyd out of the house and was working toward something",
                  "The monument's black ring flared and marked Aratos black when he challenged it",
                  "Corvin held Ked on the hill with a dagger, then struck him down and fled",
                  "Whether the eclipse took anyone this time is not yet known"],
         }),
    dict(slug='the-emberwakes-curse', name="The Emberwake's Curse", kind='thread', status='open',
         parent='the-leviathan-axe', last=11,
         overview="The axe Aratos took from Theros Flametongue is cursed. A real blow can wake a rage in him that feels like his own but comes from outside, and he cannot hand the weapon to anyone or part with it. Other weapons sit wrong in his hand. Resolve held it back once, at the reliquary. Kakashi judges that a spell to lift the curse most likely lies with clerics and paladins such as Roshi and Mayariel. The party has agreed that Aratos does no sparring and goes nowhere alone.",
         links=['pc:aratos', 'item:the-emberwake-greataxe', 'npc:roberto', 'pc:roshi', 'pc:mayariel',
                'place:the-radiant-reliquary', 'npc:marshal-vendri'],
         records={
             10: ["The axe took him in the training yard and nearly killed Roberto",
                  "He took it back from Darrett, could not hand it to Roshi, and cannot part with it",
                  "Kakashi judged it cursed; a spell to lift it most likely lies with clerics and paladins",
                  "The party agreed: no more sparring, and Aratos goes nowhere alone",
                  "Marshal Vendri promised to see what Kalaman has",
                  "At the reliquary he chose resolve and the flames died"],
             11: ["Any weapon but the Emberwake now sits wrong in his hand",
                  "Harm taken while raging woke the fury: he took the monument's head and stayed lost to it",
                  "Roshi struck him senseless before he could turn on the party"],
         }),
    dict(slug='the-sword-of-the-dragon-queen', name='The Sword of the Dragon Queen', kind='thread', status='open', last=10,
         overview="The Dragon Queen has told Mayariel that her sword will find her. Aratos has wondered whether that means a blade or someone who carries one, perhaps the party itself. She has had no new vision since the river, and the silence makes her suspicious.",
         links=['pc:mayariel', 'fac:takhisis-the-shadow-queen', 'item:mayariels-signet-ring'],
         records={
             3: ["A horned woman in dark regalia told Mayariel that the followers of Paladine would fall to her hand"],
             7: ["Mayariel pledged Paladine her signet and her obedience"],
             8: ["The Dragon Queen in the river: her sword will find her"],
             10: ["No new vision since the river; the silence feels suspicious to Mayariel",
                  "Aratos wondered whether the sword might be a person, even the party itself"],
         }),
    dict(slug='kakashis-tower-vision', name="Kakashi's Tower Vision", kind='thread', status='open', last=10,
         overview="On watch, Kakashi saw three full moons in a pail of water though the sky above did not show them so, and in place of his reflection a frightened elven woman. She went down a circular stair to a room of altars, each holding something that pulsed with magic, and began to ward them. Then she looked at him and said: you have to fight. Keep them safe.",
         links=['pc:kakashi', 'fac:the-mages-of-high-sorcery'],
         records={
             2: ["The moons aligned on his watch; voices said he was not strong enough, not yet"],
             10: ["The woman said: I have to keep them safe. I have to make sure they're okay",
                  "Fire erupted, and the vision ended",
                  "He did not know her or the place; he knows High Sorcery builds its towers to guard such things",
                  "He told no one"],
         }),
    dict(slug='kakashis-buried-past', name="Kakashi's Buried Past", kind='thread', status='open', last=7,
         overview="When the dragon machine's last explosion dropped him, Kakashi remembered a village burning and people crying. It is a past he had tried to bury.",
         links=['pc:kakashi'],
         records={
             7: ["The memory surfaced in the wreck at Vogler's docks"],
         }),
    dict(slug='lord-soths-corruption', name="Lord Soth's Corruption of Knights", kind='thread', status='open', last=9,
         overview="The pale woman told Aeimos, and only Aeimos, that Lord Soth wishes to corrupt all knights, their image and their legacies, in vengeance for how they portrayed him, and will continue until his curse is lifted. Aeimos told no one before he left. A necromancer in his service was found at work in the Radiant Reliquary. A whisper told Aeimos there are more, and that Soth wishes to take them. He has left in the direction the pale woman pointed.",
         links=['npc:lord-soth', 'pc:aeimos', 'pc:aratos', 'npc:the-pale-woman', 'npc:sir-cthondor',
                'place:the-radiant-reliquary', 'fac:the-knights-radiant'],
         records={
             8: ["Aratos saw Lord Soth in the river, standing opposite Cathan Twice-Born"],
             9: ["His necromancer raised Sir Cthondor as a wraith over a black rose",
                 "A whisper told Aeimos alone: there are more, and he wishes to take them",
                 "The pale woman told Aeimos what Soth wants and pointed him onward; he told no one"],
         }),
    dict(slug='theros-flametongue', name='Theros Flametongue', kind='thread', status='open', last=7,
         overview="Mayariel killed Theros Flametongue on the docks of Vogler. As the boats pulled away, a figure stood over his body, flame passed across him, and he rose. Aratos is carrying his axe.",
         links=['npc:theros-flametongue', 'pc:aratos', 'item:the-emberwake-greataxe', 'fac:the-red-dragon-army'],
         records={
             7: ["Killed, then raised by fire as Vogler burned"],
         }),
    dict(slug='the-bakarises', name='The Bakarises', kind='thread', status='open', last=8,
         overview="Lord Bakaris forced his way into Vogler's planning and then reached Kalaman's council ahead of the refugees. His son mocked Ispin's funeral and dismissed the refugees as fishfolk. The party does not trust either of them. Governor Miat does not seem moved by them.",
         links=['npc:bakaris-the-elder', 'npc:bakaris-the-younger', 'npc:governor-miat', 'place:kalaman'],
         records={
             4: ["The Younger heckled Ispin's wake until Becklin sent him off",
                 "The Elder stood among the spectators at High Hill as the mock battle's judge"],
             6: ["The Elder preferred a sealed letter to a ride for help",
                 "He pressed Mayor Raven to decide while the crowd panicked"],
             8: ["Both suggested more might have been done for Vogler",
                 "The Younger blocked the council door; the Elder tried to twist the hearing"],
         }),

    # -- closed --
    dict(slug='the-vanishing-fish', name='The Vanishing Fish of Vogler', kind='quest', status='closed', last=3,
         outcome="The beast beneath Crustdurn Isle was killed.",
         overview="Vogler's fishermen reported poor catches and strange sounds from the river. The trail led to an island the locals avoided.",
         objectives=[("Find what is taking the fish", True), ("Deal with it", True)],
         links=['place:crustdurn-isle', 'place:vogler', 'npc:becklin-uth-viharin', 'item:moon-touched-sword'],
         records={
             3: ["Fishers reported half the usual catch and an odd sound from the water at night",
                 "A tentacled frog-beast in the cavern beneath Crustdurn Isle swallowed Roshi and was brought down",
                 "Aeimos cut out its tongue and the party carried it back to Vogler"],
         }),
    dict(slug='the-betrayal-at-high-hill', name='The Betrayal at High Hill', kind='quest', status='closed', last=5,
         outcome="Gragonis took Red Army gold. The army behind him was found.",
         overview="The Kingfisher Festival's mock battle became a massacre when part of Cudgel's company struck with real steel. Someone paid them.",
         objectives=[("Survive the ambush", True), ("Learn who paid the mercenaries", True),
                     ("Find out what waits beyond the woods", True)],
         links=['npc:cudgel-ironsmile', 'npc:gragonis', 'fac:the-red-dragon-army', 'place:vogler'],
         records={
             4: ["Cudgel's mercenaries attacked the militia with real steel and went for Darrett first",
                 "One mercenary was taken alive and locked in Vogler's jail",
                 "A note on the half-ogre: For your services from the Red Army"],
             5: ["The captive named Cudgel's lieutenant Gragonis, the half-ogre killed on the hill",
                 "Jasper estimated one to two hundred soldiers at a camp in the woods"],
         }),
    dict(slug='the-evacuation-of-vogler', name='The Evacuation of Vogler', kind='quest', status='closed', last=7,
         giver='npc:becklin-uth-viharin',
         outcome="The people got out. The town, Becklin and Cudgel did not.",
         overview="The Red Dragon Army gave Vogler until sunset. Becklin and Cudgel took the front line and gave the party the villagers.",
         objectives=[("Buy time: get Jeyev out past the messenger", True),
                     ("Get the boats repaired and loaded", True),
                     ("See the people of Vogler onto the river", True)],
         links=['npc:becklin-uth-viharin', 'npc:cudgel-ironsmile', 'npc:mayor-raven', 'npc:than',
                'place:vogler', 'place:the-vingaard-river', 'fac:the-red-dragon-army'],
         records={
             6: ["Jeyev rode out for Cudgel's mercenaries while the party held the messenger and his watchers",
                 "The messenger and his four watchers were killed",
                 "Becklin gave the party their charge"],
             7: ["The villagers were brought to the boats; four of the party helped Than clear draconians from Thornwall Keep",
                 "The party's boat left after the dragon machine was brought down",
                 "Jeyev carried Darrett out on Becklin's and Cudgel's orders",
                 "Becklin fell into the river; Cudgel was kicked through a building"],
         }),
    dict(slug='refuge-for-vogler', name='Refuge for Vogler', kind='quest', status='closed', last=9,
         giver='npc:mayor-raven',
         outcome="Refuge granted, in exchange for the party's service.",
         overview="Mayor Raven asked the party to speak before Kalaman's council on behalf of her people.",
         objectives=[("Bring the refugees down the river alive", True),
                     ("Get a hearing before the council", True),
                     ("Win shelter for the people of Vogler", True)],
         links=['npc:mayor-raven', 'npc:governor-miat', 'npc:darrett-highwater', 'place:kalaman',
                'place:the-refugee-camp', 'quest:service-to-kalaman'],
         records={
             8: ["The Ashen Vigils were broken on the river",
                 "Governor Miat granted refuge; Darrett stood as intermediary"],
             9: ["Raven named the party honorary Voglerans"],
         }),
    dict(slug='meat-for-ispins-stew', name="Meat for Ispin's Stew", kind='quest', status='closed', last=9,
         giver='npc:fizban',
         outcome="A bear, eventually. Also a reliquary, a wraith and a horn.",
         overview="Fizban claimed to know one of Ispin's old recipes and needed meat. Bear, deer, hare, anything the wilds might offer.",
         objectives=[("Hunt something for the pot", True)],
         links=['npc:fizban', 'npc:sir-cthondor', 'place:the-radiant-reliquary',
                'place:the-refugee-camp', 'item:horn-of-sir-cthondor'],
         records={
             9: ["The bear trail led to a cave with a blue glow",
                 "The party found a bear after all and brought it back to camp"],
         }),
    dict(slug='fizbans-recipe', name="Fizban's Recipe", kind='quest', status='closed', last=10,
         outcome="All five learned the Green Flame Blade.",
         overview="A recipe for stew with quantities too absurd to be quantities.",
         objectives=[("Work out what the numbers mean", True), ("Speak the incantation", True)],
         links=['npc:fizban', 'npc:wyhan', 'item:fizbans-stew-recipe', 'pc:kakashi', 'pc:roshi'],
         records={
             10: ["Roshi read the spell's name in Fizban's reminder; Kakashi suspected a cipher",
                  "Wyhan, given only the numbers, said they would decipher the recipe into an incantation",
                  "Roshi spoke the words and the parchment burned away"],
         }),
]

# ---------------------------------------------------------------------------
# WHERE THE PARTY STANDS  (the command bar and The Road So Far)
# ---------------------------------------------------------------------------

STANDING = dict(
    journey=11,
    position='Bracken Hollow',
    pos_note="shut in, with less than a day until the next eclipse",
    pos_ref='place:bracken-hollow',
    pos_blurb="The Embers are inside a village no one can walk out of. The monument on the hill is down and headless, and a beam of red, white and black light is rising from inside the hill. The eclipse that woke it has not yet ended.",
    outstanding='Find the three things that break the spell',
    consequence="The Emberwake's fury took Aratos in the middle of the fight, and Roshi had to strike him senseless. The monument marked him black before it fell. He lies on the hill, guarded by the horn's spectral warriors. Ked lies senseless nearby. Corvin has run.",
    last_text="A list from Wyhan led the party into Bracken Hollow, shut for a month under three eclipsed moons. Boyd explained the turn of the moons and Corvin the part Boyd left out. On the hill the monument fell once its three rings were darkened. Beneath it is a cavern with three recesses.",
    quests=['the-spell-over-bracken-hollow', 'the-leviathan-axe', 'the-first-mission', 'wyhans-list',
            'the-orb-of-dragonkind', 'the-white-robes', 'service-to-kalaman'],
    met=['npc:sergeant-boyd', 'npc:corvin', 'npc:ked'],   # who mattered in the latest journey
    unanswered=['the-ones-sent-up-the-hill', 'the-emberwakes-curse', 'the-sword-of-the-dragon-queen',
                'kakashis-tower-vision', 'lord-soths-corruption', 'theros-flametongue'],
)

# Names a player might only have heard spoken. Added to the vocabulary the
# search uses to repair a misspelled query. Titles and names from the records
# above are harvested automatically; this list is for everything else.
EXTRA_VOCAB = [
    'Ansalon', 'Krynn', 'Solamnia', 'Solamnic', 'Vingaard', 'Kingfisher', 'Istarian', 'Paladine',
    'Kiri-Jolith', 'Draconic', 'Draconian', 'Leppomanto',
    'Voglerans', 'Jenkins', 'Jeyev', 'Tatina', 'Rookledust', 'Cathan', 'Gertrude', 'Wraith',
    'Necromancer', 'Reliquary', 'Ashen', 'Vigils', 'Orb', 'Dragonkind',
    'Emberwake', 'Boilerdrake', 'Periapt', 'Finn', 'Peller', 'Apothecary',
    'Takhisis', 'Bracken', 'Hollow', 'Frostlace', 'Willowbark', 'Gribb', 'Brack', 'Marigold', 'Boyd', 'Corvin', 'Ked',
    'Eclipse', 'Monument', 'Leviathan',
]
